// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 7e5af5d66397a8a1 "Velt", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { routes } from "./chunks/chunk-K34BXH3K.js";
import "./chunks/chunk-WSFCRVEQ.js";

// virtual:vertical-grid-line
import { Fragment } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/sl5mHhygEIZitmtfrfFz/v1yfD9S8WzlOAf6A1PR1/jelCKWnNR.js
import { jsx as _jsx } from "react/jsx-runtime";
import { addFonts, cx, useVariantState, withCSS } from "unframer";
import { LayoutGroup, motion } from "unframer";
import * as React from "react";
var cycleOrder = ["qzu_i39s1"];
var variantClassNames = {
	qzu_i39s1: "framer-v-1ahc657",
};
var humanReadableVariantMap = {};
var transitions = {
	default: {
		damping: 60,
		delay: 0,
		duration: 0.3,
		ease: [0.44, 0, 0.56, 1],
		mass: 1,
		stiffness: 500,
		type: "spring",
	},
};
var Component = /* @__PURE__ */ React.forwardRef(function (
	{
		id,
		style,
		className,
		width,
		height,
		layoutId,
		variant: outerVariant = "qzu_i39s1",
		...restProps
	},
	ref,
) {
	const outerVariantId = humanReadableVariantMap[outerVariant];
	const variant = outerVariantId || outerVariant;
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		transition,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "qzu_i39s1",
		transitions,
		variant,
		variantClassNames,
	});
	const layoutDependency = variants.join("-") + restProps.layoutDependency;
	const defaultLayoutId = React.useId();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<motion.div
				initial={variant}
				animate={variants}
				onHoverStart={() =>
					setGestureState({
						isHovered: true,
					})
				}
				onHoverEnd={() =>
					setGestureState({
						isHovered: false,
					})
				}
				onTapStart={() =>
					setGestureState({
						isPressed: true,
					})
				}
				onTap={() =>
					setGestureState({
						isPressed: false,
					})
				}
				onTapCancel={() =>
					setGestureState({
						isPressed: false,
					})
				}
				className={cx("framer-KFgIX", classNames)}
				style={{
					display: "contents",
				}}
			>
				<motion.div
					{...restProps}
					className={cx("framer-1ahc657", className)}
					data-framer-name={"Variant 1"}
					layoutDependency={layoutDependency}
					layoutId={"qzu_i39s1"}
					ref={ref}
					style={{
						backgroundColor: "rgba(255, 255, 255, 0.1)",
						...style,
					}}
					transition={transition}
				/>
			</motion.div>
		</LayoutGroup>
	);
});
var css = [
	'.framer-KFgIX [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-KFgIX .framer-s2bdlo { display: block; }",
	".framer-KFgIX .framer-1ahc657 { height: 253px; overflow: hidden; position: relative; width: 1px; }",
];
var FramerjelCKWnNR = withCSS(Component, css, "framer-KFgIX");
var stdin_default = FramerjelCKWnNR;
FramerjelCKWnNR.displayName = "Vertical Grid Line";
FramerjelCKWnNR.defaultProps = {
	height: 253,
	width: 1,
};
addFonts(FramerjelCKWnNR, []);

// virtual:vertical-grid-line
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7e5af5d66397a8a15ce8ab3401cf6b1aee707f00a906595a26b5cba8a8c88d97"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders VerticalGridLineFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7e5af5d66397a8a15ce8ab3401cf6b1aee707f00a906595a26b5cba8a8c88d97"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var vertical_grid_line_default = ComponentWithRoot;
export { vertical_grid_line_default as default };
