// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 7e5af5d66397a8a1 "Velt", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant 1' | 'Variant 2' // Variant
 * _1/Text?: string // 1 / Text
 * _2/Text?: string // 2 / Text
}} Props

 */
import { stdin_default } from "./chunks/chunk-DXOJNOVS.js";
import "./chunks/chunk-MVCYWFK6.js";
import { Video } from "./chunks/chunk-RUD6RUOD.js";
import "./chunks/chunk-TQMZLZEO.js";
import { routes } from "./chunks/chunk-K34BXH3K.js";
import "./chunks/chunk-WSFCRVEQ.js";

// virtual:blueprint-styling-switcher
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/08CsyggVkWPo1pQdvmtZ/AeAqdgw6WgAo1DXS0pud/gwwXaZllG.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useOnVariantChange,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var BlueprintSwitcherPillFonts = getFonts(stdin_default);
var VideoFonts = getFonts(Video);
var cycleOrder = ["IrLkve9rC", "eCl77qEbq"];
var serializationHash = "framer-YGdf3";
var variantClassNames = {
	eCl77qEbq: "framer-v-1cjv1g3",
	IrLkve9rC: "framer-v-16y2t6n",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Variant 1": "IrLkve9rC",
	"Variant 2": "eCl77qEbq",
};
var getProps = ({ _1Text, _2Text, height, id, width, ...props }) => {
	return {
		...props,
		jkY5FMJP_: _2Text ?? props.jkY5FMJP_ ?? "Reorder Elements",
		QCXMJbdlk: _1Text ?? props.QCXMJbdlk ?? "Add/Remove Elements",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "IrLkve9rC",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		QCXMJbdlk,
		jkY5FMJP_,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "IrLkve9rC",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onAppearpu34if = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("eCl77qEbq"), 10500);
	});
	const onAppear1wdwa1o = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("IrLkve9rC"), 10500);
	});
	const tsECi3tcm157ut1 = activeVariantCallback(async (...args) => {
		setVariant("IrLkve9rC");
	});
	const tsECi3tcm1qovut7 = activeVariantCallback(async (...args) => {
		setVariant("eCl77qEbq");
	});
	useOnVariantChange(baseVariant, {
		default: onAppearpu34if,
		eCl77qEbq: onAppear1wdwa1o,
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-16y2t6n",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"IrLkve9rC"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								eCl77qEbq: {
									"data-framer-name": "Variant 2",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-188hovt"}
							data-border={true}
							data-framer-name={"Frame 1707481187"}
							layoutDependency={layoutDependency}
							layoutId={"sJ55ezmID"}
							style={{
								"--border-bottom-width": "2px",
								"--border-color": "rgb(239, 243, 254)",
								"--border-left-width": "2px",
								"--border-right-width": "2px",
								"--border-style": "solid",
								"--border-top-width": "2px",
								borderBottomLeftRadius: 32,
								borderBottomRightRadius: 32,
								borderTopLeftRadius: 32,
								borderTopRightRadius: 32,
							}}
						>
							<ComponentViewportProvider
								height={31}
								y={
									(componentViewport?.y || 0) +
									0 +
									(((componentViewport?.height || 200) - 0 - 455) / 2 + 0 + 0) +
									6
								}
							>
								<SmartComponentScopedContainer
									className={"framer-1hvkk64-container"}
									layoutDependency={layoutDependency}
									layoutId={"wZXkQmEcC-container"}
									nodeId={"wZXkQmEcC"}
									rendersWithMotion={true}
									scopeId={"gwwXaZllG"}
								>
									{_jsx(stdin_default, {
										height: "100%",
										id: "wZXkQmEcC",
										l99FMpBCj: QCXMJbdlk,
										layoutId: "wZXkQmEcC",
										variant: "UCpdKfwkm",
										width: "100%",
										...addPropertyOverrides(
											{
												eCl77qEbq: {
													tsECi3tcm: tsECi3tcm157ut1,
													variant: "ZJPmXhM_u",
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
							<ComponentViewportProvider
								height={31}
								y={
									(componentViewport?.y || 0) +
									0 +
									(((componentViewport?.height || 200) - 0 - 455) / 2 + 0 + 0) +
									6
								}
							>
								<SmartComponentScopedContainer
									className={"framer-1dlxi0e-container"}
									layoutDependency={layoutDependency}
									layoutId={"VVg_CuVSC-container"}
									nodeId={"VVg_CuVSC"}
									rendersWithMotion={true}
									scopeId={"gwwXaZllG"}
								>
									{_jsx(stdin_default, {
										height: "100%",
										id: "VVg_CuVSC",
										l99FMpBCj: jkY5FMJP_,
										layoutId: "VVg_CuVSC",
										tsECi3tcm: tsECi3tcm1qovut7,
										variant: "ZJPmXhM_u",
										width: "100%",
										...addPropertyOverrides(
											{
												eCl77qEbq: {
													variant: "UCpdKfwkm",
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						</motion.div>
						<motion.div
							className={"framer-pc4loa"}
							data-border={true}
							data-framer-name={"Frame 1707481171"}
							layoutDependency={layoutDependency}
							layoutId={"zmgPsvo_O"}
							style={{
								"--border-bottom-width": "4px",
								"--border-color": "rgb(237, 242, 255)",
								"--border-left-width": "4px",
								"--border-right-width": "4px",
								"--border-style": "solid",
								"--border-top-width": "4px",
								backgroundColor: "rgb(255, 255, 255)",
								borderTopLeftRadius: 12,
								borderTopRightRadius: 12,
								boxShadow: "0px -4px 52px 0px rgba(52, 106, 243, 0.08)",
							}}
						>
							<ComponentViewportProvider>
								<SmartComponentScopedContainer
									className={"framer-1cxh87z-container"}
									isAuthoredByUser={true}
									isModuleExternal={true}
									layoutDependency={layoutDependency}
									layoutId={"qO9WxaQ8v-container"}
									nodeId={"qO9WxaQ8v"}
									rendersWithMotion={true}
									scopeId={"gwwXaZllG"}
								>
									<Video
										backgroundColor={"rgb(255, 255, 255)"}
										borderRadius={0}
										bottomLeftRadius={0}
										bottomRightRadius={0}
										controls={false}
										height={"100%"}
										id={"qO9WxaQ8v"}
										isMixedBorderRadius={false}
										layoutId={"qO9WxaQ8v"}
										loop={true}
										muted={true}
										objectFit={"cover"}
										playing={true}
										posterEnabled={true}
										srcFile={
											"https://framerusercontent.com/assets/4OEUYQJWKLAs4EEB4AKlRYjuag0.mp4"
										}
										srcType={"Upload"}
										srcUrl={
											"https://framerusercontent.com/assets/MLWPbW1dUQawJLhhun3dBwpgJak.mp4"
										}
										startTime={0}
										style={{
											height: "100%",
											width: "100%",
										}}
										topLeftRadius={0}
										topRightRadius={0}
										volume={25}
										width={"100%"}
									/>
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
							<ComponentViewportProvider>
								<SmartComponentScopedContainer
									className={"framer-c79gf-container"}
									isAuthoredByUser={true}
									isModuleExternal={true}
									layoutDependency={layoutDependency}
									layoutId={"HPSD8kpNg-container"}
									nodeId={"HPSD8kpNg"}
									rendersWithMotion={true}
									scopeId={"gwwXaZllG"}
									style={{
										opacity: 1,
									}}
									transformTemplate={transformTemplate1}
									variants={{
										eCl77qEbq: {
											opacity: 0,
										},
									}}
								>
									<Video
										backgroundColor={"rgb(255, 255, 255)"}
										borderRadius={0}
										bottomLeftRadius={0}
										bottomRightRadius={0}
										controls={false}
										height={"100%"}
										id={"HPSD8kpNg"}
										isMixedBorderRadius={false}
										layoutId={"HPSD8kpNg"}
										loop={true}
										muted={true}
										objectFit={"cover"}
										playing={true}
										posterEnabled={true}
										srcFile={
											"https://framerusercontent.com/assets/tKMKWJjFtZrbv7S0bX8b5txRZIo.mp4"
										}
										srcType={"Upload"}
										srcUrl={
											"https://framerusercontent.com/assets/MLWPbW1dUQawJLhhun3dBwpgJak.mp4"
										}
										startTime={0}
										style={{
											height: "100%",
											width: "100%",
										}}
										topLeftRadius={0}
										topRightRadius={0}
										volume={25}
										width={"100%"}
									/>
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-YGdf3.framer-1j1ts9c, .framer-YGdf3 .framer-1j1ts9c { display: block; }",
	".framer-YGdf3.framer-16y2t6n { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 960px; }",
	".framer-YGdf3 .framer-188hovt { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: flex-start; overflow: visible; padding: 6px; position: relative; width: min-content; }",
	".framer-YGdf3 .framer-1hvkk64-container, .framer-YGdf3 .framer-1dlxi0e-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-YGdf3 .framer-pc4loa { aspect-ratio: 2.526315789473684 / 1; flex: none; gap: 0px; height: var(--framer-aspect-ratio-supported, 79px); overflow: hidden; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
	".framer-YGdf3 .framer-1cxh87z-container { aspect-ratio: 2.2301136363636362 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 90px); left: 0px; position: absolute; top: 0px; width: 100%; }",
	".framer-YGdf3 .framer-c79gf-container { aspect-ratio: 2.2301136363636362 / 1; bottom: var(--framer-aspect-ratio-supported, -50px); flex: none; left: 50%; position: absolute; top: 0px; width: 100%; }",
	'.framer-YGdf3[data-border="true"]::after, .framer-YGdf3 [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramergwwXaZllG = withCSS(Component, css, "framer-YGdf3");
var stdin_default2 = FramergwwXaZllG;
FramergwwXaZllG.displayName = "Blueprint - Styling Switcher";
FramergwwXaZllG.defaultProps = {
	height: 455,
	width: 960,
};
addPropertyControls(FramergwwXaZllG, {
	variant: {
		options: ["IrLkve9rC", "eCl77qEbq"],
		optionTitles: ["Variant 1", "Variant 2"],
		title: "Variant",
		type: ControlType.Enum,
	},
	QCXMJbdlk: {
		defaultValue: "Add/Remove Elements",
		description: "",
		displayTextArea: false,
		title: "1 / Text",
		type: ControlType.String,
	},
	jkY5FMJP_: {
		defaultValue: "Reorder Elements",
		description: "",
		displayTextArea: false,
		title: "2 / Text",
		type: ControlType.String,
	},
});
addFonts(
	FramergwwXaZllG,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...BlueprintSwitcherPillFonts,
		...VideoFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:blueprint-styling-switcher
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7e5af5d66397a8a15ce8ab3401cf6b1aee707f00a906595a26b5cba8a8c88d97"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders BlueprintStylingSwitcherFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7e5af5d66397a8a15ce8ab3401cf6b1aee707f00a906595a26b5cba8a8c88d97"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var blueprint_styling_switcher_default = ComponentWithRoot;
export { blueprint_styling_switcher_default as default };
