// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 7e5af5d66397a8a1 "Velt", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * ⚙️BasicSettings?: {theme: 'auto' | 'light' | 'dark', isActive: boolean // ⚙️ Basic Settings
 * 🖱️PointerSettings?: {size: number, color: string, direction: 'left' | 'right' // 🖱️ Pointer Settings
 * 💬ChatSettings?: {dockedMessage: string, thinkingMessage: string, activeMessage: string, exitButtonLabel: string, maxVisibleActions: number, scrollableList: boolean // 💬 Chat Settings
 * ⌨️UserInputSettings?: {enabled: boolean, placeholder: string, maxLength: number // ⌨️ User Input Settings
 * 🤖AISettings?: {serverUrl: string, authToken: string // 🤖 AI Settings
 * 📍PositionSettings?: {offsetX: number, offsetY: number // 📍 Position Settings
 * 🎯BehaviorSettings?: {textSelectionMode: boolean, inactivityTimeoutSeconds: number, hotKey: string, restoreAfterNavigation: boolean // 🎯 Behavior Settings
 * 🔗NavigationLinks?: {title: string, link: string[] // 🔗 Navigation Links
}} Props

 */
import { routes } from "./chunks/chunk-K34BXH3K.js";
import "./chunks/chunk-WSFCRVEQ.js";

// virtual:chotu-cursor
import { Fragment } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/wC44L92RmQVzgbt4sXiA/hydqlvK8Q9tIpJc1kdTO/ChotuCursor.js
import { jsx as _jsx } from "react/jsx-runtime";
import { useEffect, useState } from "react";
import { addPropertyControls, ControlType } from "unframer";
var __unframerWindow = typeof window !== "undefined" ? window : void 0;
function ChotuCursor({
	basicSettings = {
		theme: "auto",
		isActive: true,
	},
	pointerSettings = {
		size: 28,
		color: "#000000",
		direction: "right",
		customSvgSource: "none",
		customSvgFile: "",
		customSvgCode: "",
	},
	chatSettings = {
		dockedMessage: "Hi! Press '/' to chat",
		thinkingMessage: "Thinking...",
		activeMessage: "How can I help you navigate?",
		exitButtonLabel: "Close",
		maxVisibleActions: 3,
		scrollableList: false,
	},
	userInputSettings = {
		enabled: true,
		placeholder: "Press '/' to talk to Chotu",
		maxLength: 500,
	},
	aiSettings = {
		serverUrl: "",
		authToken: "",
	},
	positionSettings = {
		offsetX: 24,
		offsetY: 24,
	},
	behaviorSettings = {
		textSelectionMode: true,
		inactivityTimeoutSeconds: 30,
		hotKey: "/",
		restoreAfterNavigation: false,
	},
	navigationLinks = [
		{
			title: "pricing",
			link: "",
		},
		{
			title: "contact",
			link: "",
		},
	],
}) {
	const [scriptsLoaded, setScriptsLoaded] = useState(false);
	const [loadingError, setLoadingError] = useState(null);
	const [customSvgContent, setCustomSvgContent] = useState("");
	useEffect(() => {
		const loadScript = (src) => {
			return new Promise((resolve, reject) => {
				if (document.querySelector(`script[src="${src}"]`)) {
					resolve();
					return;
				}
				const script = document.createElement("script");
				script.type = "module";
				script.src = src;
				script.onload = () => resolve();
				script.onerror = () =>
					reject(new Error(`Failed to load script: ${src}`));
				document.head.appendChild(script);
			});
		};
		const loadAllScripts = async () => {
			try {
				setLoadingError(null);
				await loadScript(
					"https://cdn.jsdelivr.net/npm/@chotu-cursor/web@latest/browser/polyfills.js",
				);
				await loadScript(
					"https://cdn.jsdelivr.net/npm/@chotu-cursor/web@latest/browser/main.js",
				);
				setScriptsLoaded(true);
			} catch (error) {
				console.error("Error loading Chotu Cursor scripts:", error);
				setLoadingError(
					error instanceof Error ? error.message : "Failed to load scripts",
				);
			}
		};
		loadAllScripts();
	}, []);
	useEffect(() => {
		const processSvg = async () => {
			try {
				if (pointerSettings.customSvgSource === "none") {
					setCustomSvgContent("");
					return;
				}
				if (
					pointerSettings.customSvgSource === "upload" &&
					pointerSettings.customSvgFile
				) {
					const response = await fetch(pointerSettings.customSvgFile);
					if (response.ok) {
						const svgText = await response.text();
						setCustomSvgContent(svgText);
					} else {
						console.error("\u274C Failed to fetch SVG:", response.statusText);
						setCustomSvgContent("");
					}
				} else if (
					pointerSettings.customSvgSource === "paste" &&
					pointerSettings.customSvgCode
				) {
					const sanitized = pointerSettings.customSvgCode
						.replace(/\n/g, " ")
						.replace(/\s+/g, " ")
						.replace(/>\s+</g, "><")
						.trim();
					setCustomSvgContent(sanitized);
				} else {
					setCustomSvgContent("");
				}
			} catch (error) {
				console.error("\u274C Error processing custom SVG:", error);
				setCustomSvgContent("");
			}
		};
		processSvg();
	}, [
		pointerSettings.customSvgSource,
		pointerSettings.customSvgFile,
		pointerSettings.customSvgCode,
	]);
	useEffect(() => {
		if (!scriptsLoaded) return;
		if (!document.getElementById("chotu-cursor")) {
			const chotuElement = document.createElement("chotu-cursor");
			chotuElement.id = "chotu-cursor";
			document.body.appendChild(chotuElement);
		}
		const initializeCursor = async () => {
			try {
				await customElements.whenDefined("chotu-cursor");
				const el = document.getElementById("chotu-cursor");
				if (el) {
					const linksObject = navigationLinks.reduce((acc, linkItem) => {
						if (linkItem.title && linkItem.link) {
							acc[linkItem.title.toLowerCase()] = linkItem.link;
						}
						return acc;
					}, {});
					const pointerConfig = {
						size: {
							width: pointerSettings.size,
							height: pointerSettings.size,
						},
						color: pointerSettings.color,
						direction: pointerSettings.direction,
					};
					if (customSvgContent.trim()) {
						pointerConfig.customSvg = customSvgContent;
					}
					const aiConfig = aiSettings.serverUrl.trim()
						? {
								provider: "remote",
								model: "gemini-2.5-flash-lite",
								serverUrl: aiSettings.serverUrl,
								...(aiSettings.authToken.trim() && {
									headers: {
										Authorization: aiSettings.authToken,
									},
								}),
							}
						: void 0;
					const inactivityTimeoutMs =
						behaviorSettings.inactivityTimeoutSeconds * 1e3;
					const config = {
						state: basicSettings.isActive ? "active" : "docked",
						exposeApisGlobally: true,
						theme: basicSettings.theme,
						pointer: pointerConfig,
						// ✅ Chat config with state property (as per docs)
						chat: {
							state: "active",
							dockedMessage: chatSettings.dockedMessage,
							thinkingMessage: chatSettings.thinkingMessage,
							activeMessage: chatSettings.activeMessage,
							maxVisibleActions: chatSettings.maxVisibleActions,
							scrollableList: chatSettings.scrollableList,
							labels: {
								exitButton: chatSettings.exitButtonLabel,
							},
						},
						userInput: {
							enabled: userInputSettings.enabled,
							placeholder: userInputSettings.placeholder,
							maxLength: userInputSettings.maxLength,
						},
						position: {
							startPosition: "bottom-left",
							offsetX: positionSettings.offsetX,
							offsetY: positionSettings.offsetY,
						},
						behavior: {
							userTextSelectionMode: behaviorSettings.textSelectionMode,
							autoNavigate: true,
							restoreToCenterAfterNavigating:
								behaviorSettings.restoreAfterNavigation,
							inactivityTimeout: inactivityTimeoutMs,
							activationHotKey: behaviorSettings.hotKey,
							positionOnHotKeyActivation: "to-center",
						},
						navigation: {
							links: linksObject,
							preserveHistory: true,
							preserveQueryParams: true,
						},
						...(aiConfig && {
							ai: aiConfig,
						}),
					};
					el.config = config;
					requestAnimationFrame(() => {
						if (__unframerWindow.chotuCursor && basicSettings.isActive) {
							__unframerWindow.chotuCursor.activate(0, true);
						}
					});
				}
			} catch (error) {
				console.error("\u274C Error initializing chotu-cursor:", error);
				setLoadingError("Failed to initialize cursor");
			}
		};
		if (document.readyState === "loading") {
			document.addEventListener("DOMContentLoaded", initializeCursor);
		} else {
			initializeCursor();
		}
		return () => {
			if (__unframerWindow.chotuCursor) {
				__unframerWindow.chotuCursor.deactivate?.();
			}
		};
	}, [
		scriptsLoaded,
		basicSettings,
		pointerSettings,
		chatSettings,
		userInputSettings,
		aiSettings,
		positionSettings,
		behaviorSettings,
		navigationLinks,
		customSvgContent,
	]);
	const showDebugInfo =
		typeof __unframerWindow !== "undefined" &&
		__unframerWindow.location.pathname.includes("/edit");
	return (
		<div
			style={{
				width: 1,
				height: 1,
				backgroundColor: "transparent",
				position: "absolute",
				pointerEvents: "none",
				...(showDebugInfo &&
					!scriptsLoaded && {
						width: 120,
						height: 40,
						backgroundColor: loadingError ? "#fee" : "#f0f0f0",
						border: "2px dashed #ccc",
						borderRadius: 8,
						display: "flex",
						alignItems: "center",
						justifyContent: "center",
						fontSize: 10,
						color: loadingError ? "#d00" : "#666",
						fontFamily: "system-ui, sans-serif",
						opacity: 0.8,
						pointerEvents: "auto",
					}),
			}}
			title={showDebugInfo ? loadingError || "Loading Chotu Cursor..." : void 0}
		>
			{showDebugInfo &&
				!scriptsLoaded &&
				(loadingError ? "\u274C Load Error" : "\u23F3 Loading...")}
		</div>
	);
}
addPropertyControls(ChotuCursor, {
	basicSettings: {
		type: ControlType.Object,
		title: "\u2699\uFE0F Basic Settings",
		controls: {
			theme: {
				type: ControlType.Enum,
				options: ["auto", "light", "dark"],
				defaultValue: "auto",
				title: "Theme",
				description: "Color scheme for the cursor interface",
			},
			isActive: {
				type: ControlType.Boolean,
				defaultValue: true,
				title: "Active on Load",
				description: "Start cursor in active state when page loads",
			},
		},
	},
	pointerSettings: {
		type: ControlType.Object,
		title: "\u{1F5B1}\uFE0F Pointer Settings",
		controls: {
			size: {
				type: ControlType.Number,
				defaultValue: 28,
				min: 10,
				max: 100,
				step: 2,
				unit: "px",
				title: "Size",
				description: "Width and height of the cursor pointer",
			},
			color: {
				type: ControlType.Color,
				defaultValue: "#000000",
				title: "Color",
				description: "Main color of the cursor pointer",
			},
			direction: {
				type: ControlType.Enum,
				options: ["left", "right"],
				defaultValue: "right",
				title: "Direction",
				description: "Which side the pointer arrow faces",
			},
		},
	},
	chatSettings: {
		type: ControlType.Object,
		title: "\u{1F4AC} Chat Settings",
		controls: {
			dockedMessage: {
				type: ControlType.String,
				defaultValue: "Hi! Press '/' to chat",
				title: "Docked Message",
				description: "Text shown when cursor is in docked state",
			},
			thinkingMessage: {
				type: ControlType.String,
				defaultValue: "Thinking...",
				title: "Thinking Message",
				description: "Text shown while AI is processing",
			},
			activeMessage: {
				type: ControlType.String,
				defaultValue: "How can I help you navigate?",
				title: "Active Message",
				description: "Default prompt when chat is active",
			},
			exitButtonLabel: {
				type: ControlType.String,
				defaultValue: "Close",
				title: "Exit Button Label",
				description: "Text for the close/exit button",
			},
			maxVisibleActions: {
				type: ControlType.Number,
				defaultValue: 3,
				min: 1,
				max: 20,
				step: 1,
				title: "Max Visible Actions",
				description: "Number of action items to show before requiring scroll",
			},
			scrollableList: {
				type: ControlType.Boolean,
				defaultValue: false,
				title: "Scrollable List",
				description: "Enable scrolling with fade effect for long action lists",
			},
		},
	},
	userInputSettings: {
		type: ControlType.Object,
		title: "\u2328\uFE0F User Input Settings",
		controls: {
			enabled: {
				type: ControlType.Boolean,
				defaultValue: true,
				title: "Enable User Input",
				description: "Allow users to type messages to the AI",
			},
			placeholder: {
				type: ControlType.String,
				defaultValue: "Press '/' to talk to Chotu",
				title: "Placeholder",
				description: "Placeholder text in the input field",
			},
			maxLength: {
				type: ControlType.Number,
				defaultValue: 500,
				min: 50,
				max: 2e3,
				step: 50,
				title: "Max Length",
				description: "Maximum characters allowed in user messages",
			},
		},
	},
	aiSettings: {
		type: ControlType.Object,
		title: "\u{1F916} AI Settings",
		controls: {
			serverUrl: {
				type: ControlType.String,
				defaultValue: "",
				title: "Server URL",
				placeholder: "https://your-api.com/ai/generate",
				description: "Your AI backend endpoint URL",
			},
			authToken: {
				type: ControlType.String,
				defaultValue: "",
				title: "Authorization Token",
				placeholder: "Bearer your-token-here",
				description: "Auth token for your AI API (optional)",
			},
		},
	},
	positionSettings: {
		type: ControlType.Object,
		title: "\u{1F4CD} Position Settings",
		controls: {
			offsetX: {
				type: ControlType.Number,
				defaultValue: 24,
				min: 0,
				max: 200,
				step: 4,
				unit: "px",
				title: "Horizontal Offset",
				description: "Distance from left/right edge of screen",
			},
			offsetY: {
				type: ControlType.Number,
				defaultValue: 24,
				min: 0,
				max: 200,
				step: 4,
				unit: "px",
				title: "Vertical Offset",
				description: "Distance from top/bottom edge of screen",
			},
		},
	},
	behaviorSettings: {
		type: ControlType.Object,
		title: "\u{1F3AF} Behavior Settings",
		controls: {
			textSelectionMode: {
				type: ControlType.Boolean,
				defaultValue: true,
				title: "Text Selection Mode",
				description: "Capture selected text for AI context",
			},
			inactivityTimeoutSeconds: {
				type: ControlType.Number,
				defaultValue: 30,
				min: 5,
				max: 120,
				step: 5,
				unit: "sec",
				title: "Inactivity Timeout",
				description: "Auto-dock cursor after this many seconds of inactivity",
			},
			hotKey: {
				type: ControlType.String,
				defaultValue: "/",
				title: "Activation Hotkey",
				description: "Key to activate cursor (e.g. '/', 's', 'ctrl+k')",
			},
			restoreAfterNavigation: {
				type: ControlType.Boolean,
				defaultValue: false,
				title: "Restore to Center After Nav",
				description: "Move cursor to center after navigating to a page",
			},
		},
	},
	navigationLinks: {
		type: ControlType.Array,
		title: "\u{1F517} Navigation Links",
		control: {
			type: ControlType.Object,
			controls: {
				title: {
					type: ControlType.String,
					title: "Link Title",
					placeholder: "e.g. pricing, contact, about",
					description: "Name the AI will use to reference this page",
				},
				link: {
					type: ControlType.Link,
					title: "Page",
					description: "Select destination page from your project",
				},
			},
		},
		defaultValue: [
			{
				title: "pricing",
				link: "",
			},
			{
				title: "contact",
				link: "",
			},
		],
		maxCount: 20,
	},
});

// virtual:chotu-cursor
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7e5af5d66397a8a15ce8ab3401cf6b1aee707f00a906595a26b5cba8a8c88d97"
			}
			locale={locale}
			locales={locales}
		>
			<ChotuCursor {...rest} />
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ChotuCursorFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7e5af5d66397a8a15ce8ab3401cf6b1aee707f00a906595a26b5cba8a8c88d97"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={ChotuCursor}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, ChotuCursor);
var chotu_cursor_default = ComponentWithRoot;
export { chotu_cursor_default as default };
