// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 7e5af5d66397a8a1 "Velt", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant 1' | 'Laptop' | 'Mobile' | 'Tablet' // Variant
}} Props

 */
import { stdin_default as stdin_default3 } from "./chunks/chunk-ISFTUOCL.js";
import { stdin_default as stdin_default2 } from "./chunks/chunk-I25H4GDK.js";
import { stdin_default } from "./chunks/chunk-5LC26QJ6.js";
import "./chunks/chunk-E4GQ7TZ3.js";
import { routes } from "./chunks/chunk-K34BXH3K.js";
import "./chunks/chunk-WSFCRVEQ.js";

// virtual:footer
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/6fBAwxRkYAPqMOOQwW9n/pBccJTct1pMb4IrS4NHG/W5b36eoio.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getLoadingLazyAtYPosition,
	Image,
	Link,
	ResolveLinks,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useRouter,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var CTAFooterFonts = getFonts(stdin_default3);
var LinkFooterFonts = getFonts(stdin_default2);
var SocialLinkFonts = getFonts(stdin_default);
var cycleOrder = ["BOykjNCQl", "eNjnGbQHl", "vviNX4lu4", "k9tsmr0E5"];
var serializationHash = "framer-SFunB";
var variantClassNames = {
	BOykjNCQl: "framer-v-v47ety",
	eNjnGbQHl: "framer-v-gq86z4",
	k9tsmr0E5: "framer-v-18prbo",
	vviNX4lu4: "framer-v-fh7ru4",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Variant 1": "BOykjNCQl",
	Laptop: "eNjnGbQHl",
	Mobile: "vviNX4lu4",
	Tablet: "k9tsmr0E5",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "BOykjNCQl",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "BOykjNCQl",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "vviNX4lu4") return false;
		return true;
	};
	const isDisplayed1 = () => {
		if (baseVariant === "k9tsmr0E5") return false;
		return true;
	};
	const router = useRouter();
	const isDisplayed2 = () => {
		if (baseVariant === "k9tsmr0E5") return true;
		return false;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-v47ety",
							className,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"BOykjNCQl"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "0px",
							"--border-color": "rgba(255, 255, 255, 0.05)",
							"--border-left-width": "0px",
							"--border-right-width": "0px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							...style,
						}}
						{...addPropertyOverrides(
							{
								eNjnGbQHl: {
									"data-framer-name": "Laptop",
								},
								k9tsmr0E5: {
									"data-framer-name": "Tablet",
								},
								vviNX4lu4: {
									"data-framer-name": "Mobile",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-dnia2x"}
							layoutDependency={layoutDependency}
							layoutId={"SYwrg0Z6Y"}
						>
							<motion.div
								className={"framer-1rcaj4n"}
								layoutDependency={layoutDependency}
								layoutId={"Z9N3yp3HT"}
							>
								<motion.div
									className={"framer-ojc78b"}
									layoutDependency={layoutDependency}
									layoutId={"hFXjyJ2xL"}
								>
									<motion.div
										className={"framer-6vwql5"}
										data-framer-name={"Logo"}
										layoutDependency={layoutDependency}
										layoutId={"WCx8eZiw_"}
									>
										<Link
											href={{
												webPageId: "augiA20Il",
											}}
											motionChild={true}
											nodeId={"PDjzjA_NF"}
											scopeId={"W5b36eoio"}
										>
											<Image
												as={"a"}
												background={{
													alt: "",
													fit: "fit",
													intrinsicHeight: 288,
													intrinsicWidth: 675,
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															64 +
															(((componentViewport?.height || 488) -
																128 -
																420) /
																2 +
																0 +
																0) +
															0 +
															0 +
															0 +
															0 +
															0 +
															0,
													),
													pixelHeight: 288,
													pixelWidth: 675,
													positionX: "center",
													positionY: "center",
													sizes: "100px",
													src: "https://framerusercontent.com/images/dIC08gnx4q6ah14XC0m5I9e1KJ0.svg?width=675&height=288",
													srcSet:
														"https://framerusercontent.com/images/dIC08gnx4q6ah14XC0m5I9e1KJ0.svg?scale-down-to=512&width=675&height=288 512w,https://framerusercontent.com/images/dIC08gnx4q6ah14XC0m5I9e1KJ0.svg?width=675&height=288 675w",
												}}
												className={"framer-tk11ek framer-1uuhhx4"}
												data-framer-name={"Logo"}
												layoutDependency={layoutDependency}
												layoutId={"PDjzjA_NF"}
												{...addPropertyOverrides(
													{
														eNjnGbQHl: {
															background: {
																alt: "",
																fit: "fit",
																intrinsicHeight: 288,
																intrinsicWidth: 675,
																loading: getLoadingLazyAtYPosition(
																	(componentViewport?.y || 0) +
																		64 +
																		(((componentViewport?.height || 200) -
																			128 -
																			420) /
																			2 +
																			0 +
																			0) +
																		0 +
																		0 +
																		0 +
																		0 +
																		0 +
																		0,
																),
																pixelHeight: 288,
																pixelWidth: 675,
																positionX: "center",
																positionY: "center",
																sizes: "100px",
																src: "https://framerusercontent.com/images/dIC08gnx4q6ah14XC0m5I9e1KJ0.svg?width=675&height=288",
																srcSet:
																	"https://framerusercontent.com/images/dIC08gnx4q6ah14XC0m5I9e1KJ0.svg?scale-down-to=512&width=675&height=288 512w,https://framerusercontent.com/images/dIC08gnx4q6ah14XC0m5I9e1KJ0.svg?width=675&height=288 675w",
															},
														},
														k9tsmr0E5: {
															background: {
																alt: "",
																fit: "fit",
																intrinsicHeight: 288,
																intrinsicWidth: 675,
																loading: getLoadingLazyAtYPosition(
																	(componentViewport?.y || 0) +
																		42 +
																		(((componentViewport?.height || 200) -
																			84 -
																			419.4) /
																			2 +
																			0 +
																			0) +
																		0 +
																		0 +
																		0 +
																		0 +
																		0 +
																		0,
																),
																pixelHeight: 288,
																pixelWidth: 675,
																positionX: "center",
																positionY: "center",
																sizes: "100px",
																src: "https://framerusercontent.com/images/dIC08gnx4q6ah14XC0m5I9e1KJ0.svg?width=675&height=288",
																srcSet:
																	"https://framerusercontent.com/images/dIC08gnx4q6ah14XC0m5I9e1KJ0.svg?scale-down-to=512&width=675&height=288 512w,https://framerusercontent.com/images/dIC08gnx4q6ah14XC0m5I9e1KJ0.svg?width=675&height=288 675w",
															},
														},
														vviNX4lu4: {
															background: {
																alt: "",
																fit: "fit",
																intrinsicHeight: 288,
																intrinsicWidth: 675,
																loading: getLoadingLazyAtYPosition(
																	(componentViewport?.y || 0) +
																		32 +
																		(((componentViewport?.height || 200) -
																			64 -
																			419.4) /
																			2 +
																			0 +
																			0) +
																		0 +
																		0 +
																		0 +
																		0 +
																		0 +
																		0,
																),
																pixelHeight: 288,
																pixelWidth: 675,
																positionX: "center",
																positionY: "center",
																sizes: "100px",
																src: "https://framerusercontent.com/images/dIC08gnx4q6ah14XC0m5I9e1KJ0.svg?width=675&height=288",
																srcSet:
																	"https://framerusercontent.com/images/dIC08gnx4q6ah14XC0m5I9e1KJ0.svg?scale-down-to=512&width=675&height=288 512w,https://framerusercontent.com/images/dIC08gnx4q6ah14XC0m5I9e1KJ0.svg?width=675&height=288 675w",
															},
														},
													},
													baseVariant,
													gestureVariant,
												)}
											/>
										</Link>
									</motion.div>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-mo8jw7"}
										data-framer-name={
											"Lorem ipsum dolor sit amet, consectetur adipiscing elit,"
										}
										fonts={["GF;Urbanist-500"]}
										layoutDependency={layoutDependency}
										layoutId={"vSB48XFdg"}
										style={{
											"--extracted-r6o4lv": "rgb(255, 255, 255)",
											opacity: 0.4,
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector": "R0Y7VXJiYW5pc3QtNTAw",
													"--framer-font-family":
														'"Urbanist", "Urbanist Placeholder", sans-serif',
													"--framer-font-weight": "500",
													"--framer-line-height": "20px",
													"--framer-text-color":
														"var(--extracted-r6o4lv, rgb(255, 255, 255))",
												}}
											>
												{"Build powerful collaboration experiences, fast."}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
								{isDisplayed() && (
									<ComponentViewportProvider
										height={47}
										y={
											(componentViewport?.y || 0) +
											64 +
											(((componentViewport?.height || 488) - 128 - 420) / 2 +
												0 +
												0) +
											0 +
											0 +
											220
										}
										{...addPropertyOverrides(
											{
												eNjnGbQHl: {
													y:
														(componentViewport?.y || 0) +
														64 +
														(((componentViewport?.height || 200) - 128 - 420) /
															2 +
															0 +
															0) +
														0 +
														0 +
														220,
												},
												k9tsmr0E5: {
													y:
														(componentViewport?.y || 0) +
														42 +
														(((componentViewport?.height || 200) - 84 - 419.4) /
															2 +
															0 +
															0) +
														0 +
														0 +
														54.5,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer
											className={"framer-lj1a6v-container"}
											layoutDependency={layoutDependency}
											layoutId={"a0r3yXtX9-container"}
											nodeId={"a0r3yXtX9"}
											rendersWithMotion={true}
											scopeId={"W5b36eoio"}
										>
											{_jsx(stdin_default3, {
												height: "100%",
												id: "a0r3yXtX9",
												layoutId: "a0r3yXtX9",
												piCpkfCcC: "Get started",
												variant: "EAbhmfbvw",
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								)}
							</motion.div>
							<motion.div
								className={"framer-opjwi2"}
								layoutDependency={layoutDependency}
								layoutId={"QGZ1UzyRq"}
							>
								{isDisplayed1() && (
									<motion.div
										className={"framer-quvic9"}
										data-framer-name={"Menu"}
										layoutDependency={layoutDependency}
										layoutId={"dNOiSkO1E"}
									>
										<motion.div
											className={"framer-94qjw0"}
											data-framer-name={"Realtime Collaboration"}
											layoutDependency={layoutDependency}
											layoutId={"pptkC3HRf"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-17kasns"}
												data-framer-name={"Title"}
												fonts={["GF;Manrope-700"]}
												layoutDependency={layoutDependency}
												layoutId={"wdecMYuO1"}
												style={{
													"--extracted-r6o4lv": "rgb(255, 255, 255)",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
												{...addPropertyOverrides(
													{
														vviNX4lu4: {
															children: (
																<React.Fragment>
																	<motion.p
																		style={{
																			"--font-selector": "R0Y7TWFucm9wZS03MDA=",
																			"--framer-font-family":
																				'"Manrope", "Manrope Placeholder", sans-serif',
																			"--framer-font-weight": "700",
																			"--framer-line-height": "20px",
																			"--framer-text-color":
																				"var(--extracted-r6o4lv, rgb(255, 255, 255))",
																		}}
																	>
																		{"Legal"}
																	</motion.p>
																</React.Fragment>
															),
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<React.Fragment>
													<motion.p
														style={{
															"--font-selector": "R0Y7TWFucm9wZS03MDA=",
															"--framer-font-family":
																'"Manrope", "Manrope Placeholder", sans-serif',
															"--framer-font-weight": "700",
															"--framer-line-height": "26px",
															"--framer-text-color":
																"var(--extracted-r6o4lv, rgb(255, 255, 255))",
														}}
													>
														{"Legal"}
													</motion.p>
												</React.Fragment>
											</RichText>
											<motion.div
												className={"framer-1d529vn"}
												data-framer-name={"Links"}
												layoutDependency={layoutDependency}
												layoutId={"q201O_HiS"}
											>
												<ResolveLinks
													links={[
														{
															href: {
																webPageId: "Jl8tdzEAi",
															},
															implicitPathVariables: void 0,
														},
														{
															href: {
																webPageId: "Jl8tdzEAi",
															},
															implicitPathVariables: void 0,
														},
														{
															href: {
																webPageId: "Jl8tdzEAi",
															},
															implicitPathVariables: void 0,
														},
													]}
												>
													{(resolvedLinks) => (
														<ComponentViewportProvider
															height={24}
															y={
																(componentViewport?.y || 0) +
																64 +
																(((componentViewport?.height || 488) -
																	128 -
																	420) /
																	2 +
																	0 +
																	0) +
																0 +
																0 +
																0 +
																0 +
																46 +
																0 +
																0
															}
															{...addPropertyOverrides(
																{
																	eNjnGbQHl: {
																		y:
																			(componentViewport?.y || 0) +
																			64 +
																			(((componentViewport?.height || 200) -
																				128 -
																				420) /
																				2 +
																				0 +
																				0) +
																			0 +
																			0 +
																			0 +
																			0 +
																			46 +
																			0 +
																			0,
																	},
																	vviNX4lu4: {
																		y:
																			(componentViewport?.y || 0) +
																			32 +
																			(((componentViewport?.height || 200) -
																				64 -
																				419.4) /
																				2 +
																				0 +
																				0) +
																			0 +
																			220 +
																			0 +
																			0 +
																			0 +
																			0 +
																			40 +
																			0 +
																			0,
																	},
																},
																baseVariant,
																gestureVariant,
															)}
														>
															<SmartComponentScopedContainer
																className={"framer-jbps88-container"}
																layoutDependency={layoutDependency}
																layoutId={"rZbmus0cO-container"}
																nodeId={"rZbmus0cO"}
																rendersWithMotion={true}
																scopeId={"W5b36eoio"}
															>
																{_jsx(stdin_default2, {
																	AqNtismxp: 16,
																	height: "100%",
																	id: "rZbmus0cO",
																	JNiWYQZlC: "Privacy Policy",
																	layoutId: "rZbmus0cO",
																	QWEejlC0d: resolvedLinks[0],
																	variant: "RqrS4CsFz",
																	width: "100%",
																	y3L1AXO7A: false,
																	...addPropertyOverrides(
																		{
																			eNjnGbQHl: {
																				QWEejlC0d: resolvedLinks[1],
																			},
																			vviNX4lu4: {
																				QWEejlC0d: resolvedLinks[2],
																			},
																		},
																		baseVariant,
																		gestureVariant,
																	),
																})}
															</SmartComponentScopedContainer>
														</ComponentViewportProvider>
													)}
												</ResolveLinks>
												<ResolveLinks
													links={[
														{
															href: {
																webPageId: "qL6P5ttnp",
															},
															implicitPathVariables: void 0,
														},
														{
															href: {
																webPageId: "qL6P5ttnp",
															},
															implicitPathVariables: void 0,
														},
														{
															href: {
																webPageId: "qL6P5ttnp",
															},
															implicitPathVariables: void 0,
														},
													]}
												>
													{(resolvedLinks1) => (
														<ComponentViewportProvider
															height={24}
															y={
																(componentViewport?.y || 0) +
																64 +
																(((componentViewport?.height || 488) -
																	128 -
																	420) /
																	2 +
																	0 +
																	0) +
																0 +
																0 +
																0 +
																0 +
																46 +
																0 +
																32
															}
															{...addPropertyOverrides(
																{
																	eNjnGbQHl: {
																		y:
																			(componentViewport?.y || 0) +
																			64 +
																			(((componentViewport?.height || 200) -
																				128 -
																				420) /
																				2 +
																				0 +
																				0) +
																			0 +
																			0 +
																			0 +
																			0 +
																			46 +
																			0 +
																			32,
																	},
																	vviNX4lu4: {
																		y:
																			(componentViewport?.y || 0) +
																			32 +
																			(((componentViewport?.height || 200) -
																				64 -
																				419.4) /
																				2 +
																				0 +
																				0) +
																			0 +
																			220 +
																			0 +
																			0 +
																			0 +
																			0 +
																			40 +
																			0 +
																			32,
																	},
																},
																baseVariant,
																gestureVariant,
															)}
														>
															<SmartComponentScopedContainer
																className={"framer-17kufm4-container"}
																layoutDependency={layoutDependency}
																layoutId={"N3mo2232i-container"}
																nodeId={"N3mo2232i"}
																rendersWithMotion={true}
																scopeId={"W5b36eoio"}
															>
																{_jsx(stdin_default2, {
																	AqNtismxp: 16,
																	height: "100%",
																	id: "N3mo2232i",
																	JNiWYQZlC: "Terms",
																	layoutId: "N3mo2232i",
																	QWEejlC0d: resolvedLinks1[0],
																	variant: "RqrS4CsFz",
																	width: "100%",
																	y3L1AXO7A: false,
																	...addPropertyOverrides(
																		{
																			eNjnGbQHl: {
																				QWEejlC0d: resolvedLinks1[1],
																			},
																			vviNX4lu4: {
																				QWEejlC0d: resolvedLinks1[2],
																			},
																		},
																		baseVariant,
																		gestureVariant,
																	),
																})}
															</SmartComponentScopedContainer>
														</ComponentViewportProvider>
													)}
												</ResolveLinks>
											</motion.div>
										</motion.div>
									</motion.div>
								)}
								{isDisplayed2() && (
									<motion.div
										className={"framer-1u502jz"}
										data-framer-name={"Tablet"}
										layoutDependency={layoutDependency}
										layoutId={"r8GmxLsL4"}
									>
										<motion.div
											className={"framer-1d1bwiw"}
											data-framer-name={"Realtime Collaboration"}
											layoutDependency={layoutDependency}
											layoutId={"MbnCv4vo9"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-fy05ku"}
												data-framer-name={"Title"}
												fonts={["GF;Manrope-700"]}
												layoutDependency={layoutDependency}
												layoutId={"i5RLha2P2"}
												style={{
													"--extracted-r6o4lv": "rgb(255, 255, 255)",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														style={{
															"--font-selector": "R0Y7TWFucm9wZS03MDA=",
															"--framer-font-family":
																'"Manrope", "Manrope Placeholder", sans-serif',
															"--framer-font-weight": "700",
															"--framer-line-height": "20px",
															"--framer-text-color":
																"var(--extracted-r6o4lv, rgb(255, 255, 255))",
														}}
													>
														{"Legal"}
													</motion.p>
												</React.Fragment>
											</RichText>
											<motion.div
												className={"framer-1y4eo3v"}
												data-framer-name={"Links"}
												layoutDependency={layoutDependency}
												layoutId={"FMYpfJHHW"}
											>
												<ResolveLinks
													links={[
														{
															href: {
																webPageId: "Jl8tdzEAi",
															},
															implicitPathVariables: void 0,
														},
														{
															href: {
																webPageId: "Jl8tdzEAi",
															},
															implicitPathVariables: void 0,
														},
													]}
												>
													{(resolvedLinks2) => (
														<ComponentViewportProvider
															height={24}
															{...addPropertyOverrides(
																{
																	k9tsmr0E5: {
																		y:
																			(componentViewport?.y || 0) +
																			42 +
																			(((componentViewport?.height || 200) -
																				84 -
																				419.4) /
																				2 +
																				0 +
																				0) +
																			0 +
																			220 +
																			0 +
																			0 +
																			0 +
																			0 +
																			40 +
																			0 +
																			0,
																	},
																},
																baseVariant,
																gestureVariant,
															)}
														>
															<SmartComponentScopedContainer
																className={"framer-1b1vax3-container"}
																layoutDependency={layoutDependency}
																layoutId={"StTCYXLzw-container"}
																nodeId={"StTCYXLzw"}
																rendersWithMotion={true}
																scopeId={"W5b36eoio"}
															>
																{_jsx(stdin_default2, {
																	AqNtismxp: 16,
																	height: "100%",
																	id: "StTCYXLzw",
																	JNiWYQZlC: "Privacy Policy",
																	layoutId: "StTCYXLzw",
																	QWEejlC0d: resolvedLinks2[0],
																	variant: "RqrS4CsFz",
																	width: "100%",
																	y3L1AXO7A: false,
																	...addPropertyOverrides(
																		{
																			k9tsmr0E5: {
																				QWEejlC0d: resolvedLinks2[1],
																			},
																		},
																		baseVariant,
																		gestureVariant,
																	),
																})}
															</SmartComponentScopedContainer>
														</ComponentViewportProvider>
													)}
												</ResolveLinks>
												<ResolveLinks
													links={[
														{
															href: {
																webPageId: "qL6P5ttnp",
															},
															implicitPathVariables: void 0,
														},
														{
															href: {
																webPageId: "qL6P5ttnp",
															},
															implicitPathVariables: void 0,
														},
													]}
												>
													{(resolvedLinks3) => (
														<ComponentViewportProvider
															height={24}
															{...addPropertyOverrides(
																{
																	k9tsmr0E5: {
																		y:
																			(componentViewport?.y || 0) +
																			42 +
																			(((componentViewport?.height || 200) -
																				84 -
																				419.4) /
																				2 +
																				0 +
																				0) +
																			0 +
																			220 +
																			0 +
																			0 +
																			0 +
																			0 +
																			40 +
																			0 +
																			32,
																	},
																},
																baseVariant,
																gestureVariant,
															)}
														>
															<SmartComponentScopedContainer
																className={"framer-1er91t8-container"}
																layoutDependency={layoutDependency}
																layoutId={"kcLeaxWYk-container"}
																nodeId={"kcLeaxWYk"}
																rendersWithMotion={true}
																scopeId={"W5b36eoio"}
															>
																{_jsx(stdin_default2, {
																	AqNtismxp: 16,
																	height: "100%",
																	id: "kcLeaxWYk",
																	JNiWYQZlC: "Terms",
																	layoutId: "kcLeaxWYk",
																	QWEejlC0d: resolvedLinks3[0],
																	variant: "RqrS4CsFz",
																	width: "100%",
																	y3L1AXO7A: false,
																	...addPropertyOverrides(
																		{
																			k9tsmr0E5: {
																				QWEejlC0d: resolvedLinks3[1],
																			},
																		},
																		baseVariant,
																		gestureVariant,
																	),
																})}
															</SmartComponentScopedContainer>
														</ComponentViewportProvider>
													)}
												</ResolveLinks>
												{isDisplayed1() && (
													<ComponentViewportProvider height={24}>
														<SmartComponentScopedContainer
															className={"framer-zg55p4-container"}
															layoutDependency={layoutDependency}
															layoutId={"GLPZoQKkE-container"}
															nodeId={"GLPZoQKkE"}
															rendersWithMotion={true}
															scopeId={"W5b36eoio"}
														>
															{_jsx(stdin_default2, {
																AqNtismxp: 16,
																height: "100%",
																id: "GLPZoQKkE",
																JNiWYQZlC: "Flock mode",
																layoutId: "GLPZoQKkE",
																variant: "RqrS4CsFz",
																width: "100%",
																y3L1AXO7A: false,
															})}
														</SmartComponentScopedContainer>
													</ComponentViewportProvider>
												)}
												{isDisplayed1() && (
													<ComponentViewportProvider height={24}>
														<SmartComponentScopedContainer
															className={"framer-17ktn89-container"}
															layoutDependency={layoutDependency}
															layoutId={"RdoYqZNJp-container"}
															nodeId={"RdoYqZNJp"}
															rendersWithMotion={true}
															scopeId={"W5b36eoio"}
														>
															{_jsx(stdin_default2, {
																AqNtismxp: 16,
																height: "100%",
																id: "RdoYqZNJp",
																JNiWYQZlC: "Presence",
																layoutId: "RdoYqZNJp",
																variant: "RqrS4CsFz",
																width: "100%",
																y3L1AXO7A: false,
															})}
														</SmartComponentScopedContainer>
													</ComponentViewportProvider>
												)}
												{isDisplayed1() && (
													<ComponentViewportProvider height={24}>
														<SmartComponentScopedContainer
															className={"framer-1yt812y-container"}
															layoutDependency={layoutDependency}
															layoutId={"WERrXBTKa-container"}
															nodeId={"WERrXBTKa"}
															rendersWithMotion={true}
															scopeId={"W5b36eoio"}
														>
															{_jsx(stdin_default2, {
																AqNtismxp: 16,
																height: "100%",
																id: "WERrXBTKa",
																JNiWYQZlC: "Cursor",
																layoutId: "WERrXBTKa",
																variant: "RqrS4CsFz",
																width: "100%",
																y3L1AXO7A: false,
															})}
														</SmartComponentScopedContainer>
													</ComponentViewportProvider>
												)}
												{isDisplayed1() && (
													<ComponentViewportProvider height={24}>
														<SmartComponentScopedContainer
															className={"framer-z7wkz3-container"}
															layoutDependency={layoutDependency}
															layoutId={"qAtTLeZ7h-container"}
															nodeId={"qAtTLeZ7h"}
															rendersWithMotion={true}
															scopeId={"W5b36eoio"}
														>
															{_jsx(stdin_default2, {
																AqNtismxp: 16,
																height: "100%",
																id: "qAtTLeZ7h",
																JNiWYQZlC: "Huddle",
																layoutId: "qAtTLeZ7h",
																variant: "RqrS4CsFz",
																width: "100%",
																y3L1AXO7A: false,
															})}
														</SmartComponentScopedContainer>
													</ComponentViewportProvider>
												)}
											</motion.div>
										</motion.div>
										{isDisplayed1() && (
											<motion.div
												className={"framer-2sfok9"}
												layoutDependency={layoutDependency}
												layoutId={"ID0dz0O3k"}
											>
												<motion.div
													className={"framer-1z0d3ft"}
													data-framer-name={"Async Collaboration"}
													layoutDependency={layoutDependency}
													layoutId={"eyoJLVKaM"}
												>
													<RichText
														__fromCanvasComponent={true}
														className={"framer-gcn2t8"}
														data-framer-name={"Title"}
														fonts={["GF;Manrope-700"]}
														layoutDependency={layoutDependency}
														layoutId={"j5WA_4z7f"}
														style={{
															"--extracted-2gxw0f": "rgb(255, 255, 255)",
															"--extracted-r6o4lv": "rgb(255, 255, 255)",
														}}
														verticalAlignment={"top"}
														withExternalLayout={true}
													>
														<React.Fragment>
															<motion.p
																style={{
																	"--font-selector": "R0Y7TWFucm9wZS03MDA=",
																	"--framer-font-family":
																		'"Manrope", "Manrope Placeholder", sans-serif',
																	"--framer-font-size": "20px",
																	"--framer-font-weight": "700",
																	"--framer-line-height": "26px",
																	"--framer-text-color":
																		"var(--extracted-r6o4lv, rgb(255, 255, 255))",
																}}
															>
																{"Async "}
															</motion.p>
															<motion.p
																style={{
																	"--font-selector": "R0Y7TWFucm9wZS03MDA=",
																	"--framer-font-family":
																		'"Manrope", "Manrope Placeholder", sans-serif',
																	"--framer-font-size": "20px",
																	"--framer-font-weight": "700",
																	"--framer-line-height": "26px",
																	"--framer-text-color":
																		"var(--extracted-2gxw0f, rgb(255, 255, 255))",
																}}
															>
																{"Collaboration"}
															</motion.p>
														</React.Fragment>
													</RichText>
													<motion.div
														className={"framer-1020k78"}
														data-framer-name={"Links"}
														layoutDependency={layoutDependency}
														layoutId={"QXrzBAItN"}
													>
														<ComponentViewportProvider height={24}>
															<SmartComponentScopedContainer
																className={"framer-tdlwtm-container"}
																layoutDependency={layoutDependency}
																layoutId={"JDFePM9lc-container"}
																nodeId={"JDFePM9lc"}
																rendersWithMotion={true}
																scopeId={"W5b36eoio"}
															>
																{_jsx(stdin_default2, {
																	AqNtismxp: 16,
																	height: "100%",
																	id: "JDFePM9lc",
																	JNiWYQZlC: "Tag & assign user",
																	layoutId: "JDFePM9lc",
																	variant: "RqrS4CsFz",
																	width: "100%",
																	y3L1AXO7A: false,
																})}
															</SmartComponentScopedContainer>
														</ComponentViewportProvider>
														<ComponentViewportProvider height={24}>
															<SmartComponentScopedContainer
																className={"framer-1ulxriy-container"}
																layoutDependency={layoutDependency}
																layoutId={"YQL0nIEy1-container"}
																nodeId={"YQL0nIEy1"}
																rendersWithMotion={true}
																scopeId={"W5b36eoio"}
															>
																{_jsx(stdin_default2, {
																	AqNtismxp: 16,
																	height: "100%",
																	id: "YQL0nIEy1",
																	JNiWYQZlC: "Comments",
																	layoutId: "YQL0nIEy1",
																	variant: "RqrS4CsFz",
																	width: "100%",
																	y3L1AXO7A: false,
																})}
															</SmartComponentScopedContainer>
														</ComponentViewportProvider>
														<ComponentViewportProvider height={24}>
															<SmartComponentScopedContainer
																className={"framer-oi8yde-container"}
																layoutDependency={layoutDependency}
																layoutId={"ounpdTkZc-container"}
																nodeId={"ounpdTkZc"}
																rendersWithMotion={true}
																scopeId={"W5b36eoio"}
															>
																{_jsx(stdin_default2, {
																	AqNtismxp: 16,
																	height: "100%",
																	id: "ounpdTkZc",
																	JNiWYQZlC: "Recording",
																	layoutId: "ounpdTkZc",
																	variant: "RqrS4CsFz",
																	width: "100%",
																	y3L1AXO7A: false,
																})}
															</SmartComponentScopedContainer>
														</ComponentViewportProvider>
														<ComponentViewportProvider height={24}>
															<SmartComponentScopedContainer
																className={"framer-1enonub-container"}
																layoutDependency={layoutDependency}
																layoutId={"TJ27Ikqzb-container"}
																nodeId={"TJ27Ikqzb"}
																rendersWithMotion={true}
																scopeId={"W5b36eoio"}
															>
																{_jsx(stdin_default2, {
																	AqNtismxp: 16,
																	height: "100%",
																	id: "TJ27Ikqzb",
																	JNiWYQZlC: "Arrow",
																	layoutId: "TJ27Ikqzb",
																	variant: "RqrS4CsFz",
																	width: "100%",
																	y3L1AXO7A: false,
																})}
															</SmartComponentScopedContainer>
														</ComponentViewportProvider>
													</motion.div>
												</motion.div>
												<motion.div
													className={"framer-1h12i0n"}
													data-framer-name={"Ai Co"}
													layoutDependency={layoutDependency}
													layoutId={"w3CWJg2cT"}
												>
													<RichText
														__fromCanvasComponent={true}
														className={"framer-1sdzgnj"}
														data-framer-name={"Title"}
														fonts={["GF;Manrope-700"]}
														layoutDependency={layoutDependency}
														layoutId={"uD7MuwyhD"}
														style={{
															"--extracted-r6o4lv": "rgb(255, 255, 255)",
														}}
														verticalAlignment={"top"}
														withExternalLayout={true}
													>
														<React.Fragment>
															<motion.p
																style={{
																	"--font-selector": "R0Y7TWFucm9wZS03MDA=",
																	"--framer-font-family":
																		'"Manrope", "Manrope Placeholder", sans-serif',
																	"--framer-font-size": "20px",
																	"--framer-font-weight": "700",
																	"--framer-line-height": "26px",
																	"--framer-text-color":
																		"var(--extracted-r6o4lv, rgb(255, 255, 255))",
																}}
															>
																{"AI Copilot"}
															</motion.p>
														</React.Fragment>
													</RichText>
													<motion.div
														className={"framer-1jsf415"}
														data-framer-name={"Links"}
														layoutDependency={layoutDependency}
														layoutId={"fb7Q9tcAw"}
													>
														<ComponentViewportProvider height={24}>
															<SmartComponentScopedContainer
																className={"framer-15g5vxl-container"}
																layoutDependency={layoutDependency}
																layoutId={"Dtr0iG7uF-container"}
																nodeId={"Dtr0iG7uF"}
																rendersWithMotion={true}
																scopeId={"W5b36eoio"}
															>
																{_jsx(stdin_default2, {
																	AqNtismxp: 16,
																	height: "100%",
																	id: "Dtr0iG7uF",
																	JNiWYQZlC: "Design",
																	layoutId: "Dtr0iG7uF",
																	variant: "RqrS4CsFz",
																	width: "100%",
																	y3L1AXO7A: false,
																})}
															</SmartComponentScopedContainer>
														</ComponentViewportProvider>
														<ComponentViewportProvider height={24}>
															<SmartComponentScopedContainer
																className={"framer-1pr6n1n-container"}
																layoutDependency={layoutDependency}
																layoutId={"tz4QP_ssd-container"}
																nodeId={"tz4QP_ssd"}
																rendersWithMotion={true}
																scopeId={"W5b36eoio"}
															>
																{_jsx(stdin_default2, {
																	AqNtismxp: 16,
																	height: "100%",
																	id: "tz4QP_ssd",
																	JNiWYQZlC: "Data",
																	layoutId: "tz4QP_ssd",
																	variant: "RqrS4CsFz",
																	width: "100%",
																	y3L1AXO7A: false,
																})}
															</SmartComponentScopedContainer>
														</ComponentViewportProvider>
													</motion.div>
												</motion.div>
											</motion.div>
										)}
										{isDisplayed1() && (
											<motion.div
												className={"framer-1rcfwly"}
												layoutDependency={layoutDependency}
												layoutId={"uOrV2mWCd"}
											>
												<motion.div
													className={"framer-1pzphbd"}
													data-framer-name={"Async Collaboration"}
													layoutDependency={layoutDependency}
													layoutId={"ltuE5Dgp9"}
												>
													<RichText
														__fromCanvasComponent={true}
														className={"framer-1o8obxg"}
														data-framer-name={"Title"}
														fonts={["GF;Manrope-700"]}
														layoutDependency={layoutDependency}
														layoutId={"gXsynfgQd"}
														style={{
															"--extracted-2gxw0f": "rgb(255, 255, 255)",
															"--extracted-r6o4lv": "rgb(255, 255, 255)",
														}}
														verticalAlignment={"top"}
														withExternalLayout={true}
													>
														<React.Fragment>
															<motion.p
																style={{
																	"--font-selector": "R0Y7TWFucm9wZS03MDA=",
																	"--framer-font-family":
																		'"Manrope", "Manrope Placeholder", sans-serif',
																	"--framer-font-size": "20px",
																	"--framer-font-weight": "700",
																	"--framer-line-height": "26px",
																	"--framer-text-color":
																		"var(--extracted-r6o4lv, rgb(255, 255, 255))",
																}}
															>
																{"In-app "}
															</motion.p>
															<motion.p
																style={{
																	"--font-selector": "R0Y7TWFucm9wZS03MDA=",
																	"--framer-font-family":
																		'"Manrope", "Manrope Placeholder", sans-serif',
																	"--framer-font-size": "20px",
																	"--framer-font-weight": "700",
																	"--framer-line-height": "26px",
																	"--framer-text-color":
																		"var(--extracted-2gxw0f, rgb(255, 255, 255))",
																}}
															>
																{"User Feedback"}
															</motion.p>
														</React.Fragment>
													</RichText>
													<motion.div
														className={"framer-od3349"}
														data-framer-name={"Links"}
														layoutDependency={layoutDependency}
														layoutId={"fmceDzVLT"}
													>
														<ComponentViewportProvider height={24}>
															<SmartComponentScopedContainer
																className={"framer-1j48qhk-container"}
																layoutDependency={layoutDependency}
																layoutId={"Q_MxdU8Fv-container"}
																nodeId={"Q_MxdU8Fv"}
																rendersWithMotion={true}
																scopeId={"W5b36eoio"}
															>
																{_jsx(stdin_default2, {
																	AqNtismxp: 16,
																	height: "100%",
																	id: "Q_MxdU8Fv",
																	JNiWYQZlC: "Feeback",
																	layoutId: "Q_MxdU8Fv",
																	variant: "RqrS4CsFz",
																	width: "100%",
																	y3L1AXO7A: false,
																})}
															</SmartComponentScopedContainer>
														</ComponentViewportProvider>
														<ComponentViewportProvider height={24}>
															<SmartComponentScopedContainer
																className={"framer-t8fs5f-container"}
																layoutDependency={layoutDependency}
																layoutId={"g3DOd5LI5-container"}
																nodeId={"g3DOd5LI5"}
																rendersWithMotion={true}
																scopeId={"W5b36eoio"}
															>
																{_jsx(stdin_default2, {
																	AqNtismxp: 16,
																	height: "100%",
																	id: "g3DOd5LI5",
																	JNiWYQZlC: "Bug",
																	layoutId: "g3DOd5LI5",
																	variant: "RqrS4CsFz",
																	width: "100%",
																	y3L1AXO7A: false,
																})}
															</SmartComponentScopedContainer>
														</ComponentViewportProvider>
														<ComponentViewportProvider height={24}>
															<SmartComponentScopedContainer
																className={"framer-ja0xsk-container"}
																layoutDependency={layoutDependency}
																layoutId={"uHd1nHDDf-container"}
																nodeId={"uHd1nHDDf"}
																rendersWithMotion={true}
																scopeId={"W5b36eoio"}
															>
																{_jsx(stdin_default2, {
																	AqNtismxp: 16,
																	height: "100%",
																	id: "uHd1nHDDf",
																	JNiWYQZlC: "Contact",
																	layoutId: "uHd1nHDDf",
																	variant: "RqrS4CsFz",
																	width: "100%",
																	y3L1AXO7A: false,
																})}
															</SmartComponentScopedContainer>
														</ComponentViewportProvider>
													</motion.div>
												</motion.div>
												<motion.div
													className={"framer-1hh3csd"}
													data-framer-name={"Permission"}
													layoutDependency={layoutDependency}
													layoutId={"sLZid7iTp"}
												>
													<RichText
														__fromCanvasComponent={true}
														className={"framer-888q4k"}
														data-framer-name={"Title"}
														fonts={["GF;Manrope-700"]}
														layoutDependency={layoutDependency}
														layoutId={"yaM8Y3zRJ"}
														style={{
															"--extracted-2gxw0f": "rgb(255, 255, 255)",
															"--extracted-r6o4lv": "rgb(255, 255, 255)",
														}}
														verticalAlignment={"top"}
														withExternalLayout={true}
													>
														<React.Fragment>
															<motion.p
																style={{
																	"--font-selector": "R0Y7TWFucm9wZS03MDA=",
																	"--framer-font-family":
																		'"Manrope", "Manrope Placeholder", sans-serif',
																	"--framer-font-size": "20px",
																	"--framer-font-weight": "700",
																	"--framer-line-height": "26px",
																	"--framer-text-color":
																		"var(--extracted-r6o4lv, rgb(255, 255, 255))",
																}}
															>
																{"Permission "}
															</motion.p>
															<motion.p
																style={{
																	"--font-selector": "R0Y7TWFucm9wZS03MDA=",
																	"--framer-font-family":
																		'"Manrope", "Manrope Placeholder", sans-serif',
																	"--framer-font-size": "20px",
																	"--framer-font-weight": "700",
																	"--framer-line-height": "26px",
																	"--framer-text-color":
																		"var(--extracted-2gxw0f, rgb(255, 255, 255))",
																}}
															>
																{"Management"}
															</motion.p>
														</React.Fragment>
													</RichText>
													<motion.div
														className={"framer-uugmev"}
														data-framer-name={"Links"}
														layoutDependency={layoutDependency}
														layoutId={"oCKaKimZj"}
													>
														<ComponentViewportProvider height={24}>
															<SmartComponentScopedContainer
																className={"framer-aalc6e-container"}
																layoutDependency={layoutDependency}
																layoutId={"e9Dg9h_hT-container"}
																nodeId={"e9Dg9h_hT"}
																rendersWithMotion={true}
																scopeId={"W5b36eoio"}
															>
																{_jsx(stdin_default2, {
																	AqNtismxp: 16,
																	height: "100%",
																	id: "e9Dg9h_hT",
																	JNiWYQZlC: "Cloud infrastructure",
																	layoutId: "e9Dg9h_hT",
																	variant: "RqrS4CsFz",
																	width: "100%",
																	y3L1AXO7A: false,
																})}
															</SmartComponentScopedContainer>
														</ComponentViewportProvider>
													</motion.div>
												</motion.div>
											</motion.div>
										)}
									</motion.div>
								)}
							</motion.div>
						</motion.div>
						<motion.div
							className={"framer-ae5owd"}
							layoutDependency={layoutDependency}
							layoutId={"p7TuCOP7E"}
							style={{
								background:
									"radial-gradient(72.2% 72.2% at 50% 50%, rgb(255, 255, 255) 0%, rgba(255, 255, 255, 0) 100%)",
								opacity: 0.2,
							}}
							variants={{
								k9tsmr0E5: {
									background:
										"radial-gradient(48.9% 77.42499999999998% at 50% 50%, rgb(255, 255, 255) 0%, rgba(255, 255, 255, 0) 100%)",
								},
								vviNX4lu4: {
									background:
										"radial-gradient(48.9% 77.42499999999998% at 50% 50%, rgb(255, 255, 255) 0%, rgba(255, 255, 255, 0) 100%)",
								},
							}}
						/>
						<motion.div
							className={"framer-1yvjvi5"}
							layoutDependency={layoutDependency}
							layoutId={"u2R0IOI9u"}
						>
							<motion.div
								className={"framer-fx6nin"}
								layoutDependency={layoutDependency}
								layoutId={"QxQBdn5u7"}
							>
								<ComponentViewportProvider>
									<SmartComponentScopedContainer
										className={"framer-ruhh7u-container"}
										layoutDependency={layoutDependency}
										layoutId={"Su53Oh9_f-container"}
										nodeId={"Su53Oh9_f"}
										rendersWithMotion={true}
										scopeId={"W5b36eoio"}
									>
										{_jsx(stdin_default, {
											height: "100%",
											id: "Su53Oh9_f",
											layoutId: "Su53Oh9_f",
											link: "https://discord.gg/GupvcYH27h",
											social: "CRLlXLyWP",
											style: {
												height: "100%",
												width: "100%",
											},
											variant: "Zv3rBwSg4",
											width: "100%",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
								<ComponentViewportProvider>
									<SmartComponentScopedContainer
										className={"framer-rdtbep-container"}
										layoutDependency={layoutDependency}
										layoutId={"RXiWngqLS-container"}
										nodeId={"RXiWngqLS"}
										rendersWithMotion={true}
										scopeId={"W5b36eoio"}
									>
										{_jsx(stdin_default, {
											height: "100%",
											id: "RXiWngqLS",
											layoutId: "RXiWngqLS",
											link: "https://twitter.com/veltjs",
											social: "m8hL1EvWO",
											style: {
												height: "100%",
												width: "100%",
											},
											variant: "Zv3rBwSg4",
											width: "100%",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
								<ComponentViewportProvider>
									<SmartComponentScopedContainer
										className={"framer-1vctie0-container"}
										layoutDependency={layoutDependency}
										layoutId={"fzQnQXW0z-container"}
										nodeId={"fzQnQXW0z"}
										rendersWithMotion={true}
										scopeId={"W5b36eoio"}
									>
										{_jsx(stdin_default, {
											height: "100%",
											id: "fzQnQXW0z",
											layoutId: "fzQnQXW0z",
											link: "https://www.linkedin.com/company/veltjs",
											social: "sDTNNiYpL",
											style: {
												height: "100%",
												width: "100%",
											},
											variant: "Zv3rBwSg4",
											width: "100%",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							</motion.div>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-vno1iw"}
								data-framer-name={"All rights reserved \xA9 2023 Velt"}
								fonts={["GF;Urbanist-500"]}
								layoutDependency={layoutDependency}
								layoutId={"HrSomjH7d"}
								style={{
									"--extracted-r6o4lv": "rgb(255, 255, 255)",
									opacity: 0.4,
								}}
								variants={{
									k9tsmr0E5: {
										"--extracted-2gxw0f": "rgb(255, 255, 255)",
									},
									vviNX4lu4: {
										"--extracted-2gxw0f": "rgb(255, 255, 255)",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										k9tsmr0E5: {
											children: (
												<React.Fragment>
													<motion.p
														style={{
															"--font-selector": "R0Y7VXJiYW5pc3QtNTAw",
															"--framer-font-family": '"Urbanist", sans-serif',
															"--framer-font-weight": "500",
															"--framer-text-alignment": "right",
															"--framer-text-color":
																"var(--extracted-r6o4lv, rgb(255, 255, 255))",
														}}
													>
														{"All rights reserved "}
													</motion.p>
													<motion.p
														style={{
															"--font-selector": "R0Y7VXJiYW5pc3QtNTAw",
															"--framer-font-family": '"Urbanist", sans-serif',
															"--framer-font-weight": "500",
															"--framer-text-alignment": "right",
															"--framer-text-color":
																"var(--extracted-2gxw0f, rgb(255, 255, 255))",
														}}
													>
														{"\xA9 2023 Velt"}
													</motion.p>
												</React.Fragment>
											),
										},
										vviNX4lu4: {
											children: (
												<React.Fragment>
													<motion.p
														style={{
															"--font-selector": "R0Y7VXJiYW5pc3QtNTAw",
															"--framer-font-family": '"Urbanist", sans-serif',
															"--framer-font-weight": "500",
															"--framer-text-alignment": "right",
															"--framer-text-color":
																"var(--extracted-r6o4lv, rgb(255, 255, 255))",
														}}
													>
														{"All rights reserved "}
													</motion.p>
													<motion.p
														style={{
															"--font-selector": "R0Y7VXJiYW5pc3QtNTAw",
															"--framer-font-family": '"Urbanist", sans-serif',
															"--framer-font-weight": "500",
															"--framer-text-alignment": "right",
															"--framer-text-color":
																"var(--extracted-2gxw0f, rgb(255, 255, 255))",
														}}
													>
														{"\xA9 2023 Velt"}
													</motion.p>
												</React.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.p
										style={{
											"--font-selector": "R0Y7VXJiYW5pc3QtNTAw",
											"--framer-font-family":
												'"Urbanist", "Urbanist Placeholder", sans-serif',
											"--framer-font-weight": "500",
											"--framer-text-alignment": "right",
											"--framer-text-color":
												"var(--extracted-r6o4lv, rgb(255, 255, 255))",
										}}
									>
										{"All rights reserved \xA9 2023 Velt"}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
						<motion.div
							className={"framer-89vtgb"}
							layoutDependency={layoutDependency}
							layoutId={"lCoBWjtXv"}
							style={{
								backgroundColor: "rgba(255, 255, 255, 0.03)",
							}}
						/>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-SFunB.framer-1uuhhx4, .framer-SFunB .framer-1uuhhx4 { display: block; }",
	".framer-SFunB.framer-v47ety { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 64px; height: min-content; justify-content: center; overflow: hidden; padding: 64px 240px 64px 240px; position: relative; width: 1676px; }",
	".framer-SFunB .framer-dnia2x { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; max-width: 1440px; overflow: hidden; padding: 0px; position: relative; width: 100%; z-index: 2; }",
	".framer-SFunB .framer-1rcaj4n { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 64px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 340px; }",
	".framer-SFunB .framer-ojc78b { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-SFunB .framer-6vwql5 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-SFunB .framer-tk11ek { aspect-ratio: 2.5 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 40px); overflow: visible; position: relative; text-decoration: none; width: 100px; }",
	".framer-SFunB .framer-mo8jw7 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 232px; word-break: break-word; word-wrap: break-word; }",
	".framer-SFunB .framer-lj1a6v-container, .framer-SFunB .framer-jbps88-container, .framer-SFunB .framer-17kufm4-container, .framer-SFunB .framer-1b1vax3-container, .framer-SFunB .framer-1er91t8-container, .framer-SFunB .framer-zg55p4-container, .framer-SFunB .framer-17ktn89-container, .framer-SFunB .framer-1yt812y-container, .framer-SFunB .framer-z7wkz3-container, .framer-SFunB .framer-tdlwtm-container, .framer-SFunB .framer-1ulxriy-container, .framer-SFunB .framer-oi8yde-container, .framer-SFunB .framer-1enonub-container, .framer-SFunB .framer-15g5vxl-container, .framer-SFunB .framer-1pr6n1n-container, .framer-SFunB .framer-1j48qhk-container, .framer-SFunB .framer-t8fs5f-container, .framer-SFunB .framer-ja0xsk-container, .framer-SFunB .framer-aalc6e-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-SFunB .framer-opjwi2 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; max-width: 850px; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-SFunB .framer-quvic9, .framer-SFunB .framer-1u502jz { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-SFunB .framer-94qjw0, .framer-SFunB .framer-1d1bwiw, .framer-SFunB .framer-1z0d3ft, .framer-SFunB .framer-1h12i0n, .framer-SFunB .framer-1pzphbd, .framer-SFunB .framer-1hh3csd { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-SFunB .framer-17kasns, .framer-SFunB .framer-fy05ku, .framer-SFunB .framer-gcn2t8, .framer-SFunB .framer-1sdzgnj, .framer-SFunB .framer-1o8obxg, .framer-SFunB .framer-888q4k, .framer-SFunB .framer-vno1iw { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-SFunB .framer-1d529vn, .framer-SFunB .framer-1y4eo3v, .framer-SFunB .framer-1020k78, .framer-SFunB .framer-1jsf415, .framer-SFunB .framer-od3349, .framer-SFunB .framer-uugmev { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-SFunB .framer-2sfok9, .framer-SFunB .framer-1rcfwly { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 48px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-SFunB .framer-ae5owd { flex: none; height: 1px; max-width: 1440px; overflow: hidden; position: relative; width: 100%; z-index: 2; }",
	".framer-SFunB .framer-1yvjvi5 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: 24px; justify-content: space-between; max-width: 1440px; overflow: hidden; padding: 0px; position: relative; width: 100%; z-index: 2; }",
	".framer-SFunB .framer-fx6nin { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 36px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-SFunB .framer-ruhh7u-container, .framer-SFunB .framer-rdtbep-container, .framer-SFunB .framer-1vctie0-container { flex: none; height: 25px; position: relative; width: 24px; }",
	".framer-SFunB .framer-89vtgb { bottom: 0px; flex: none; left: 0px; overflow: hidden; position: absolute; right: 0px; top: 0px; z-index: 0; }",
	".framer-SFunB.framer-v-gq86z4.framer-v47ety { padding: 64px 60px 64px 60px; }",
	".framer-SFunB.framer-v-fh7ru4.framer-v47ety { gap: 32px; padding: 32px 20px 32px 20px; width: 400px; }",
	".framer-SFunB.framer-v-fh7ru4 .framer-dnia2x, .framer-SFunB.framer-v-18prbo .framer-dnia2x { flex-direction: column; gap: 64px; justify-content: flex-start; }",
	".framer-SFunB.framer-v-fh7ru4 .framer-1rcaj4n, .framer-SFunB.framer-v-18prbo .framer-1rcaj4n { align-content: center; align-items: center; flex-direction: row; gap: unset; justify-content: space-between; width: 100%; }",
	".framer-SFunB.framer-v-fh7ru4 .framer-ojc78b, .framer-SFunB.framer-v-18prbo .framer-ojc78b { flex: 1 0 0px; width: 1px; }",
	".framer-SFunB.framer-v-fh7ru4 .framer-mo8jw7, .framer-SFunB.framer-v-18prbo .framer-mo8jw7 { max-width: 200px; width: 100%; }",
	".framer-SFunB.framer-v-fh7ru4 .framer-opjwi2 { align-content: flex-start; align-items: flex-start; flex: none; width: 100%; }",
	".framer-SFunB.framer-v-fh7ru4 .framer-quvic9 { flex-direction: column; gap: 36px; justify-content: flex-start; }",
	".framer-SFunB.framer-v-fh7ru4 .framer-94qjw0, .framer-SFunB.framer-v-18prbo .framer-1d1bwiw { order: 0; }",
	".framer-SFunB.framer-v-fh7ru4 .framer-1yvjvi5, .framer-SFunB.framer-v-18prbo .framer-1yvjvi5 { height: min-content; }",
	".framer-SFunB.framer-v-18prbo.framer-v47ety { gap: 32px; padding: 42px; width: 800px; }",
	".framer-SFunB.framer-v-18prbo .framer-opjwi2 { align-content: flex-start; align-items: flex-start; flex: none; flex-direction: column; width: 100%; }",
	".framer-SFunB.framer-v-18prbo .framer-1u502jz { flex: none; width: 100%; }",
	'.framer-SFunB[data-border="true"]::after, .framer-SFunB [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerW5b36eoio = withCSS(Component, css, "framer-SFunB");
var stdin_default4 = FramerW5b36eoio;
FramerW5b36eoio.displayName = "Footer";
FramerW5b36eoio.defaultProps = {
	height: 488,
	width: 1676,
};
addPropertyControls(FramerW5b36eoio, {
	variant: {
		options: ["BOykjNCQl", "eNjnGbQHl", "vviNX4lu4", "k9tsmr0E5"],
		optionTitles: ["Variant 1", "Laptop", "Mobile", "Tablet"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerW5b36eoio,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Urbanist",
					source: "google",
					style: "normal",
					url: "https://fonts.gstatic.com/s/urbanist/v18/L0xjDF02iFML4hGCyOCpRdycFsGxSrqD-R4fE5OrS8SlKw.woff2",
					weight: "500",
				},
				{
					family: "Manrope",
					source: "google",
					style: "normal",
					url: "https://fonts.gstatic.com/s/manrope/v20/xn7_YHE41ni1AdIRqAuZuw1Bx9mbZk4aE-_A87jxeN7B.woff2",
					weight: "700",
				},
			],
		},
		...CTAFooterFonts,
		...LinkFooterFonts,
		...SocialLinkFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:footer
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "vviNX4lu4",
	md: "k9tsmr0E5",
	xl: "eNjnGbQHl",
	"2xl": "BOykjNCQl",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7e5af5d66397a8a15ce8ab3401cf6b1aee707f00a906595a26b5cba8a8c88d97"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default4, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FooterFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7e5af5d66397a8a15ce8ab3401cf6b1aee707f00a906595a26b5cba8a8c88d97"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default4}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default4);
var footer_default = ComponentWithRoot;
export { footer_default as default };
