// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 7e5af5d66397a8a1 "Velt", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * title?: string // Title
}} Props

 */
import { routes } from "../chunks/chunk-K34BXH3K.js";
import "../chunks/chunk-WSFCRVEQ.js";

// virtual:new/grey-image
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/jexkE5PP3RE8a0TQbxam/A8q78CknU7AidQj1eEon/lLF8nXABI.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var enabledGestures = {
	Ek3wsobUU: {
		hover: true,
	},
};
var serializationHash = "framer-zFGqH";
var variantClassNames = {
	Ek3wsobUU: "framer-v-1c1t56k",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, image, title, width, ...props }) => {
	return {
		...props,
		DeTdFgEQf: title ?? props.DeTdFgEQf ?? "name",
		Ke1zHvmZR: image ?? props.Ke1zHvmZR,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		Ke1zHvmZR,
		DeTdFgEQf,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "Ek3wsobUU",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1c1t56k",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"Ek3wsobUU"}
						ref={refBinding}
						style={{
							borderBottomLeftRadius: 4,
							borderBottomRightRadius: 4,
							borderTopLeftRadius: 4,
							borderTopRightRadius: 4,
							...style,
						}}
						{...addPropertyOverrides(
							{
								"Ek3wsobUU-hover": {
									"data-framer-name": void 0,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-3yont0"}
							layoutDependency={layoutDependency}
							layoutId={"ZiOMHl_p_"}
							style={{
								"--border-bottom-width": "0px",
								"--border-color": "rgba(0, 0, 0, 0)",
								"--border-left-width": "0px",
								"--border-right-width": "0px",
								"--border-style": "solid",
								"--border-top-width": "0px",
								borderBottomLeftRadius: 4,
								borderBottomRightRadius: 4,
								borderTopLeftRadius: 4,
								borderTopRightRadius: 4,
							}}
							variants={{
								"Ek3wsobUU-hover": {
									"--border-bottom-width": "1px",
									"--border-color": "rgba(255, 255, 255, 0.12)",
									"--border-left-width": "1px",
									"--border-right-width": "1px",
									"--border-style": "solid",
									"--border-top-width": "1px",
								},
							}}
							{...addPropertyOverrides(
								{
									"Ek3wsobUU-hover": {
										"data-border": true,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<Image
								background={{
									alt: "",
									fit: "fill",
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 200) - 0 - 269.2) / 2 +
												0 +
												0) +
											-0.1051,
									),
									sizes: `calc(${componentViewport?.width || "100vw"} * 0.9963)`,
									...toResponsiveImage(Ke1zHvmZR),
								}}
								className={"framer-14cvsd4"}
								layoutDependency={layoutDependency}
								layoutId={"oFPug0Q_G"}
							/>
							<motion.div
								className={"framer-itiqvi"}
								layoutDependency={layoutDependency}
								layoutId={"cQsMhd9JO"}
								style={{
									backgroundColor: "rgb(0, 0, 0)",
									opacity: 1,
								}}
								variants={{
									"Ek3wsobUU-hover": {
										opacity: 0,
									},
								}}
							/>
						</motion.div>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-1pkwmxn"}
							fonts={["GF;Urbanist-500"]}
							layoutDependency={layoutDependency}
							layoutId={"dwoITrwe_"}
							style={{
								"--extracted-r6o4lv": "rgb(255, 255, 255)",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							text={DeTdFgEQf}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									style={{
										"--font-selector": "R0Y7VXJiYW5pc3QtNTAw",
										"--framer-font-family":
											'"Urbanist", "Urbanist Placeholder", sans-serif',
										"--framer-font-size": "14px",
										"--framer-font-weight": "500",
										"--framer-letter-spacing": "0.15em",
										"--framer-line-height": "130%",
										"--framer-text-color":
											"var(--extracted-r6o4lv, rgb(255, 255, 255))",
										"--framer-text-transform": "uppercase",
									}}
								>
									{"name"}
								</motion.p>
							</React.Fragment>
						</RichText>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-zFGqH.framer-ix1p4u, .framer-zFGqH .framer-ix1p4u { display: block; }",
	".framer-zFGqH.framer-1c1t56k { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; padding: 0px; position: relative; width: 404px; }",
	".framer-zFGqH .framer-3yont0 { aspect-ratio: 1.777533039647577 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 113px); overflow: visible; position: relative; width: 100%; }",
	".framer-zFGqH .framer-14cvsd4 { flex: none; height: 100%; left: calc(49.81412639405207% - 99.62825278810409% / 2); overflow: visible; position: absolute; top: calc(49.70873786407769% - 99.51456310679612% / 2); width: 100%; }",
	".framer-zFGqH .framer-itiqvi { flex: none; height: 100%; left: calc(49.81412639405207% - 99.62825278810409% / 2); mix-blend-mode: color; overflow: visible; position: absolute; top: calc(49.70873786407769% - 99.6116504854369% / 2); width: 100%; }",
	".framer-zFGqH .framer-1pkwmxn { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	'.framer-zFGqH[data-border="true"]::after, .framer-zFGqH [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerlLF8nXABI = withCSS(Component, css, "framer-zFGqH");
var stdin_default = FramerlLF8nXABI;
FramerlLF8nXABI.displayName = "New / Grey Image";
FramerlLF8nXABI.defaultProps = {
	height: 269,
	width: 403,
};
addPropertyControls(FramerlLF8nXABI, {
	Ke1zHvmZR: {
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	DeTdFgEQf: {
		defaultValue: "name",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
});
addFonts(
	FramerlLF8nXABI,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Urbanist",
					source: "google",
					style: "normal",
					url: "https://fonts.gstatic.com/s/urbanist/v18/L0xjDF02iFML4hGCyOCpRdycFsGxSrqD-R4fE5OrS8SlKw.woff2",
					weight: "500",
				},
			],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:new/grey-image
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7e5af5d66397a8a15ce8ab3401cf6b1aee707f00a906595a26b5cba8a8c88d97"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders GreyImageFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7e5af5d66397a8a15ce8ab3401cf6b1aee707f00a906595a26b5cba8a8c88d97"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var grey_image_default = ComponentWithRoot;
export { grey_image_default as default };
