// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 7e5af5d66397a8a1 "Velt", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Mobile' | 'Tablet' // Variant
 * image?: {src: string, srcSet?: string, alt?: string} // Image
}} Props

 */
import { routes } from "../chunks/chunk-K34BXH3K.js";
import "../chunks/chunk-WSFCRVEQ.js";

// virtual:new/docs
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/1PUgbwEWVDdi88bClBfx/8Kdfe0auP7I7EJq0Uwrc/b1FF1OSoZ.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	Image,
	Link,
	RichText,
	SVG,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var ImageWithFX = withFX(Image);
var cycleOrder = ["JZBdb6dZt", "GNTRH2pIC", "yMPc50SXr"];
var serializationHash = "framer-VAuK9";
var variantClassNames = {
	GNTRH2pIC: "framer-v-1nbyqef",
	JZBdb6dZt: "framer-v-fuymxz",
	yMPc50SXr: "framer-v-1jlveax",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transitions = {
	default: {
		damping: 60,
		delay: 0,
		mass: 1,
		stiffness: 500,
		type: "spring",
	},
};
var transformTemplate1 = (_, t) => `translateY(-50%) ${t}`;
var transition1 = {
	damping: 30,
	delay: 0,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var animation = {
	opacity: 1,
	rotate: 0,
	scale: 1,
	transition: transition1,
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var animation1 = {
	opacity: 0,
	rotate: 0,
	scale: 1,
	x: 150,
	y: 0,
};
var animation2 = {
	opacity: 0,
	rotate: 0,
	scale: 1,
	transition: transition1,
	x: 150,
	y: 0,
};
var transformTemplate2 = (_, t) => `perspective(1200px) ${t}`;
var transformTemplate3 = (_, t) => `perspective(1200px) translateX(-50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "JZBdb6dZt",
	Mobile: "GNTRH2pIC",
	Tablet: "yMPc50SXr",
};
var getProps = ({ height, id, image, width, ...props }) => {
	var _ref, _humanReadableVariantMap_props_variant, _ref1;
	return {
		...props,
		JdNxW81k2:
			(_ref = image !== null && image !== void 0 ? image : props.JdNxW81k2) !==
				null && _ref !== void 0
				? _ref
				: {
						src: "https://framerusercontent.com/images/III6HelzIbYe8CCUgwM08HcUsA.png?scale-down-to=1024",
						srcSet:
							"https://framerusercontent.com/images/III6HelzIbYe8CCUgwM08HcUsA.png?scale-down-to=512 512w, https://framerusercontent.com/images/III6HelzIbYe8CCUgwM08HcUsA.png?scale-down-to=1024 1024w, https://framerusercontent.com/images/III6HelzIbYe8CCUgwM08HcUsA.png?scale-down-to=2048 2048w, https://framerusercontent.com/images/III6HelzIbYe8CCUgwM08HcUsA.png 3024w",
					},
		variant:
			(_ref1 =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref1 !== void 0
				? _ref1
				: "JZBdb6dZt",
	};
};
var createLayoutDependency = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const { style, className, layoutId, variant, JdNxW81k2, ...restProps } =
		getProps(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		transition,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "JZBdb6dZt",
		transitions,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const ref1 = React.useRef(null);
	const isDisplayed = () => {
		if (baseVariant === "GNTRH2pIC") return false;
		return true;
	};
	const isDisplayed1 = () => {
		if (baseVariant === "GNTRH2pIC") return true;
		return false;
	};
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [];
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition}>
					<motion.div
						{...restProps}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-fuymxz",
							className,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"JZBdb6dZt"}
						onHoverEnd={() =>
							setGestureState({
								isHovered: false,
							})
						}
						onHoverStart={() =>
							setGestureState({
								isHovered: true,
							})
						}
						onTap={() =>
							setGestureState({
								isPressed: false,
							})
						}
						onTapCancel={() =>
							setGestureState({
								isPressed: false,
							})
						}
						onTapStart={() =>
							setGestureState({
								isPressed: true,
							})
						}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							"--border-bottom-width": "0px",
							"--border-color": "rgba(0, 0, 0, 0)",
							"--border-left-width": "0px",
							"--border-right-width": "0px",
							"--border-style": "solid",
							"--border-top-width": "0px",
							background:
								"linear-gradient(124deg, rgb(24, 24, 24) 0%, rgb(0, 0, 0) 100%)",
							borderBottomLeftRadius: 32,
							borderBottomRightRadius: 32,
							borderTopLeftRadius: 32,
							borderTopRightRadius: 32,
							...style,
						}}
						variants={{
							GNTRH2pIC: {
								"--border-bottom-width": "1px",
								"--border-color": "rgb(37, 37, 37)",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
								borderBottomLeftRadius: 24,
								borderBottomRightRadius: 24,
								borderTopLeftRadius: 24,
								borderTopRightRadius: 24,
							},
						}}
						{...addPropertyOverrides(
							{
								GNTRH2pIC: {
									"data-border": true,
									"data-framer-name": "Mobile",
								},
								yMPc50SXr: {
									"data-framer-name": "Tablet",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						{isDisplayed() && (
							<motion.div
								className={"framer-1rvrywd"}
								layoutDependency={layoutDependency}
								layoutId={"cig3kgHTO"}
								style={{
									background:
										"radial-gradient(183.9% 75% at 38.800000000000004% 67.10000000000001%, rgba(255, 255, 255, 0) 0%, rgba(255, 255, 255, 0.24) 100%)",
								}}
							/>
						)}
						{isDisplayed() && (
							<motion.div
								className={"framer-idz00w"}
								layoutDependency={layoutDependency}
								layoutId={"Tusf25h0E"}
								style={{
									background:
										"linear-gradient(90deg, rgba(0, 0, 0, 0.24) -3.1463004023979635%, rgba(0, 0, 0, 0.9) 100%)",
								}}
							/>
						)}
						{isDisplayed() && (
							<motion.div
								className={"framer-o4eszn"}
								layoutDependency={layoutDependency}
								layoutId={"GOwOGKKtk"}
								style={{
									background:
										"linear-gradient(124deg, rgba(0, 0, 0, 0.42) 0%, rgb(0, 0, 0) 100%)",
									borderBottomLeftRadius: 28,
									borderBottomRightRadius: 28,
									borderTopLeftRadius: 28,
									borderTopRightRadius: 28,
								}}
							/>
						)}
						<motion.div
							className={"framer-giwkua"}
							data-framer-name={"Frame 1707478692"}
							layoutDependency={layoutDependency}
							layoutId={"WXGxb9VAr"}
						>
							{isDisplayed() && (
								<motion.div
									className={"framer-k2kym6"}
									layoutDependency={layoutDependency}
									layoutId={"e96gpOss1"}
								>
									<motion.div
										className={"framer-814kjm"}
										layoutDependency={layoutDependency}
										layoutId={"EQhV667Ch"}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-1ab36qn"}
											data-framer-name={"Simple Docs & 24x7 Support"}
											fonts={["GF;Urbanist-700"]}
											layoutDependency={layoutDependency}
											layoutId={"q1sjfsMM9"}
											style={{
												"--extracted-1of0zx5": "rgb(22, 22, 22)",
												"--extracted-1orxqtn": "rgb(255, 255, 255)",
												"--extracted-hi0pf5": "rgb(22, 22, 22)",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
											{...addPropertyOverrides(
												{
													yMPc50SXr: {
														children: (
															<React.Fragment>
																<motion.h2
																	style={{
																		"--font-selector": "R0Y7VXJiYW5pc3QtNzAw",
																		"--framer-font-family":
																			'"Urbanist", "Urbanist Placeholder", sans-serif',
																		"--framer-font-size": "32px",
																		"--framer-font-weight": "700",
																		"--framer-letter-spacing": "-0.01em",
																		"--framer-line-height": "120%",
																		"--framer-text-color":
																			"var(--extracted-1of0zx5, rgb(22, 22, 22))",
																	}}
																>
																	{"Simple & "}
																</motion.h2>
																<motion.h2
																	style={{
																		"--font-selector": "R0Y7VXJiYW5pc3QtNzAw",
																		"--framer-font-family":
																			'"Urbanist", "Urbanist Placeholder", sans-serif',
																		"--framer-font-size": "32px",
																		"--framer-font-weight": "700",
																		"--framer-letter-spacing": "-0.01em",
																		"--framer-line-height": "120%",
																		"--framer-text-color":
																			"var(--extracted-hi0pf5, rgb(22, 22, 22))",
																	}}
																>
																	{"Beautiful"}
																	<motion.span
																		style={{
																			"--framer-text-color":
																				"var(--extracted-1orxqtn, rgb(255, 255, 255))",
																		}}
																	>
																		{" Docs"}
																	</motion.span>
																</motion.h2>
															</React.Fragment>
														),
														transformTemplate: transformTemplate1,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<React.Fragment>
												<motion.h2
													style={{
														"--font-selector": "R0Y7VXJiYW5pc3QtNzAw",
														"--framer-font-family":
															'"Urbanist", "Urbanist Placeholder", sans-serif',
														"--framer-font-size": "48px",
														"--framer-font-weight": "700",
														"--framer-letter-spacing": "-0.01em",
														"--framer-line-height": "120%",
														"--framer-text-color":
															"var(--extracted-1of0zx5, rgb(22, 22, 22))",
													}}
												>
													{"Simple & "}
												</motion.h2>
												<motion.h2
													style={{
														"--font-selector": "R0Y7VXJiYW5pc3QtNzAw",
														"--framer-font-family":
															'"Urbanist", "Urbanist Placeholder", sans-serif',
														"--framer-font-size": "48px",
														"--framer-font-weight": "700",
														"--framer-letter-spacing": "-0.01em",
														"--framer-line-height": "120%",
														"--framer-text-color":
															"var(--extracted-hi0pf5, rgb(22, 22, 22))",
													}}
												>
													{"Beautiful"}
													<motion.span
														style={{
															"--framer-text-color":
																"var(--extracted-1orxqtn, rgb(255, 255, 255))",
														}}
													>
														{" Docs"}
													</motion.span>
												</motion.h2>
											</React.Fragment>
										</RichText>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-4n9kgd"}
											data-framer-name={"Simple Docs"}
											fonts={["GF;Urbanist-700"]}
											layoutDependency={layoutDependency}
											layoutId={"n0ycgagi_"}
											verticalAlignment={"top"}
											withExternalLayout={true}
											{...addPropertyOverrides(
												{
													yMPc50SXr: {
														children: (
															<React.Fragment>
																<motion.h2
																	style={{
																		"--font-selector": "R0Y7VXJiYW5pc3QtNzAw",
																		"--framer-font-family":
																			'"Urbanist", "Urbanist Placeholder", sans-serif',
																		"--framer-font-size": "32px",
																		"--framer-font-weight": "700",
																		"--framer-letter-spacing": "-0.01em",
																		"--framer-line-height": "120%",
																	}}
																>
																	<motion.span
																		data-text-fill={"true"}
																		style={{
																			backgroundImage:
																				"radial-gradient(83.1% 252.533% at 5.15601e-07% 8.85418%, rgb(82, 224, 255) 0%, rgb(0, 71, 255) 36.4964%, rgb(214, 97, 255) 69.5294%, rgb(255, 108, 178) 100%)",
																		}}
																	>
																		{"Simple & "}
																	</motion.span>
																</motion.h2>
																<motion.h2
																	style={{
																		"--font-selector": "R0Y7VXJiYW5pc3QtNzAw",
																		"--framer-font-family":
																			'"Urbanist", "Urbanist Placeholder", sans-serif',
																		"--framer-font-size": "32px",
																		"--framer-font-weight": "700",
																		"--framer-letter-spacing": "-0.01em",
																		"--framer-line-height": "120%",
																	}}
																>
																	<motion.span
																		data-text-fill={"true"}
																		style={{
																			backgroundImage:
																				"radial-gradient(83.1% 252.533% at 5.15601e-07% 8.85418%, rgb(82, 224, 255) 0%, rgb(0, 71, 255) 36.4964%, rgb(214, 97, 255) 69.5294%, rgb(255, 108, 178) 100%)",
																		}}
																	>
																		{"Beautiful"}
																	</motion.span>
																</motion.h2>
															</React.Fragment>
														),
														transformTemplate: transformTemplate1,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<React.Fragment>
												<motion.h2
													style={{
														"--font-selector": "R0Y7VXJiYW5pc3QtNzAw",
														"--framer-font-family":
															'"Urbanist", "Urbanist Placeholder", sans-serif',
														"--framer-font-size": "48px",
														"--framer-font-weight": "700",
														"--framer-letter-spacing": "-0.01em",
														"--framer-line-height": "120%",
													}}
												>
													<motion.span
														data-text-fill={"true"}
														style={{
															backgroundImage:
																"radial-gradient(83.1% 252.533% at 5.15601e-07% 8.85418%, rgb(82, 224, 255) 0%, rgb(0, 71, 255) 36.4964%, rgb(214, 97, 255) 69.5294%, rgb(255, 108, 178) 100%)",
														}}
													>
														{"Simple & "}
													</motion.span>
												</motion.h2>
												<motion.h2
													style={{
														"--font-selector": "R0Y7VXJiYW5pc3QtNzAw",
														"--framer-font-family":
															'"Urbanist", "Urbanist Placeholder", sans-serif',
														"--framer-font-size": "48px",
														"--framer-font-weight": "700",
														"--framer-letter-spacing": "-0.01em",
														"--framer-line-height": "120%",
													}}
												>
													<motion.span
														data-text-fill={"true"}
														style={{
															backgroundImage:
																"radial-gradient(83.1% 252.533% at 5.15601e-07% 8.85418%, rgb(82, 224, 255) 0%, rgb(0, 71, 255) 36.4964%, rgb(214, 97, 255) 69.5294%, rgb(255, 108, 178) 100%)",
														}}
													>
														{"Beautiful"}
													</motion.span>
												</motion.h2>
											</React.Fragment>
										</RichText>
									</motion.div>
								</motion.div>
							)}
							{isDisplayed1() && (
								<motion.div
									className={"framer-a22jyy"}
									layoutDependency={layoutDependency}
									layoutId={"rV_vS2UIB"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-ajhfxr"}
										data-framer-name={"Simple Docs"}
										fonts={["GF;Urbanist-700"]}
										layoutDependency={layoutDependency}
										layoutId={"SSSPbryib"}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector": "R0Y7VXJiYW5pc3QtNzAw",
													"--framer-font-family":
														'"Urbanist", "Urbanist Placeholder", sans-serif',
													"--framer-font-size": "40px",
													"--framer-font-weight": "700",
													"--framer-letter-spacing": "-0.01em",
													"--framer-line-height": "120%",
												}}
											>
												<motion.span
													data-text-fill={"true"}
													style={{
														backgroundImage:
															"radial-gradient(60.7843% 252.533% at 5.15601e-07% 8.85418%, rgb(82, 224, 255) 0%, rgb(0, 71, 255) 36.4964%, rgb(214, 97, 255) 69.5294%, rgb(255, 108, 178) 100%)",
													}}
												>
													{"Simple & Beautiful"}
												</motion.span>
											</motion.p>
										</React.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-zfahbc"}
										data-framer-name={"Simple Docs & 24x7 Support"}
										fonts={["GF;Urbanist-700"]}
										layoutDependency={layoutDependency}
										layoutId={"yBp6uGefL"}
										style={{
											"--extracted-r6o4lv": "rgb(255, 255, 255)",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector": "R0Y7VXJiYW5pc3QtNzAw",
													"--framer-font-family":
														'"Urbanist", "Urbanist Placeholder", sans-serif',
													"--framer-font-size": "40px",
													"--framer-font-weight": "700",
													"--framer-letter-spacing": "-0.01em",
													"--framer-line-height": "120%",
													"--framer-text-color":
														"var(--extracted-r6o4lv, rgb(255, 255, 255))",
												}}
											>
												{"Docs"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
							)}
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1yhz4lx"}
								data-framer-name={
									"Written by our founding engineers @vivek & @ashish"
								}
								fonts={["GF;Urbanist-regular"]}
								layoutDependency={layoutDependency}
								layoutId={"Vh6TVuHeP"}
								style={{
									opacity: 0.75,
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										style={{
											"--font-selector": "R0Y7VXJiYW5pc3QtcmVndWxhcg==",
											"--framer-font-family":
												'"Urbanist", "Urbanist Placeholder", sans-serif',
											"--framer-font-size": "18px",
											"--framer-letter-spacing": "-0.01em",
											"--framer-line-height": "150%",
										}}
									>
										<motion.span
											data-text-fill={"true"}
											style={{
												backgroundImage:
													"radial-gradient(104.3% 429.9% at -2.38095% 8.52451e-09%, rgb(255, 255, 255) 0%, rgba(255, 255, 255, 0.41) 100%)",
											}}
										>
											{"Clear docs with on demand support"}
										</motion.span>
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
						<motion.div
							className={"framer-2ytsxh"}
							data-framer-name={"Frame 1707478691"}
							layoutDependency={layoutDependency}
							layoutId={"p4mDvYAmn"}
							style={{
								opacity: 0.75,
							}}
						>
							<Link href={"https://docs.velt.dev/get-started/quickstart"}>
								<motion.a
									className={"framer-1rf4s0a framer-1efpc6r"}
									data-framer-name={"Frame 1707478598"}
									layoutDependency={layoutDependency}
									layoutId={"Vj_ZaVyst"}
									style={{
										opacity: 0.5,
									}}
									whileHover={animation}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1dx27i4"}
										data-framer-name={"Quick Start Guide"}
										fonts={["GF;Urbanist-regular"]}
										layoutDependency={layoutDependency}
										layoutId={"ghg6Mx07h"}
										style={{
											"--extracted-r6o4lv": "rgb(255, 255, 255)",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector": "R0Y7VXJiYW5pc3QtcmVndWxhcg==",
													"--framer-font-family":
														'"Urbanist", "Urbanist Placeholder", sans-serif',
													"--framer-letter-spacing": "-0.01em",
													"--framer-line-height": "100%",
													"--framer-text-color":
														"var(--extracted-r6o4lv, rgb(255, 255, 255))",
												}}
											>
												{"Quick Start Guide"}
											</motion.p>
										</React.Fragment>
									</RichText>
									<SVG
										className={"framer-19wmea1"}
										data-framer-name={"tabler-icon-arrow-narrow-right"}
										fill={"rgba(0,0,0,1)"}
										intrinsicHeight={19}
										intrinsicWidth={18}
										layoutDependency={layoutDependency}
										layoutId={"hAz3vqC6W"}
										svg={
											'<svg width="18" height="19" viewBox="0 0 18 19" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path d="M3.75 9.78125H14.25M14.25 9.78125L11.25 12.7812M14.25 9.78125L11.25 6.78125" stroke="white" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>\n</svg>\n'
										}
										withExternalLayout={true}
									/>
								</motion.a>
							</Link>
							<Link href={"https://docs.velt.dev/examples/overview"}>
								<motion.a
									className={"framer-1n5qvw framer-1efpc6r"}
									data-framer-name={"Frame 1707478599"}
									layoutDependency={layoutDependency}
									layoutId={"kZjr55A8u"}
									style={{
										opacity: 0.5,
									}}
									whileHover={animation}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1z0e5b5"}
										data-framer-name={"Examples"}
										fonts={["GF;Urbanist-regular"]}
										layoutDependency={layoutDependency}
										layoutId={"QPSHhUkOa"}
										style={{
											"--extracted-r6o4lv": "rgb(255, 255, 255)",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector": "R0Y7VXJiYW5pc3QtcmVndWxhcg==",
													"--framer-font-family":
														'"Urbanist", "Urbanist Placeholder", sans-serif',
													"--framer-letter-spacing": "-0.01em",
													"--framer-line-height": "100%",
													"--framer-text-color":
														"var(--extracted-r6o4lv, rgb(255, 255, 255))",
												}}
											>
												{"Examples"}
											</motion.p>
										</React.Fragment>
									</RichText>
									<SVG
										className={"framer-63o7uy"}
										data-framer-name={"tabler-icon-arrow-narrow-right"}
										fill={"rgba(0,0,0,1)"}
										intrinsicHeight={19}
										intrinsicWidth={18}
										layoutDependency={layoutDependency}
										layoutId={"P1exX9MZy"}
										svg={
											'<svg width="18" height="19" viewBox="0 0 18 19" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path d="M3.75 9.78125H14.25M14.25 9.78125L11.25 12.7812M14.25 9.78125L11.25 6.78125" stroke="white" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>\n</svg>\n'
										}
										withExternalLayout={true}
									/>
								</motion.a>
							</Link>
							<Link
								href={
									"https://docs.velt.dev/get-started/overview#popular-features"
								}
							>
								<motion.a
									className={"framer-1ic7nqs framer-1efpc6r"}
									data-framer-name={"Frame 1707478600"}
									layoutDependency={layoutDependency}
									layoutId={"vCPSTTyId"}
									style={{
										opacity: 0.5,
									}}
									whileHover={animation}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-108ntd6"}
										data-framer-name={"Popular Features"}
										fonts={["GF;Urbanist-regular"]}
										layoutDependency={layoutDependency}
										layoutId={"iJzUD6Zbu"}
										style={{
											"--extracted-r6o4lv": "rgb(255, 255, 255)",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector": "R0Y7VXJiYW5pc3QtcmVndWxhcg==",
													"--framer-font-family":
														'"Urbanist", "Urbanist Placeholder", sans-serif',
													"--framer-letter-spacing": "-0.01em",
													"--framer-line-height": "100%",
													"--framer-text-color":
														"var(--extracted-r6o4lv, rgb(255, 255, 255))",
												}}
											>
												{"Popular Features"}
											</motion.p>
										</React.Fragment>
									</RichText>
									<SVG
										className={"framer-webhcr"}
										data-framer-name={"tabler-icon-arrow-narrow-right"}
										fill={"rgba(0,0,0,1)"}
										intrinsicHeight={19}
										intrinsicWidth={18}
										layoutDependency={layoutDependency}
										layoutId={"NpdGWRGsD"}
										svg={
											'<svg width="18" height="19" viewBox="0 0 18 19" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path d="M3.75 9.78125H14.25M14.25 9.78125L11.25 12.7812M14.25 9.78125L11.25 6.78125" stroke="white" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>\n</svg>\n'
										}
										withExternalLayout={true}
									/>
								</motion.a>
							</Link>
							<Link href={"https://docs.velt.dev/notifications/email/overview"}>
								<motion.a
									className={"framer-19f2jr6 framer-1efpc6r"}
									data-framer-name={"Frame 1707478601"}
									layoutDependency={layoutDependency}
									layoutId={"eIP34FflY"}
									style={{
										opacity: 0.5,
									}}
									whileHover={animation}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-ayislt"}
										data-framer-name={"Notifications"}
										fonts={["GF;Urbanist-regular"]}
										layoutDependency={layoutDependency}
										layoutId={"SkolQeame"}
										style={{
											"--extracted-r6o4lv": "rgb(255, 255, 255)",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector": "R0Y7VXJiYW5pc3QtcmVndWxhcg==",
													"--framer-font-family":
														'"Urbanist", "Urbanist Placeholder", sans-serif',
													"--framer-letter-spacing": "-0.01em",
													"--framer-line-height": "100%",
													"--framer-text-color":
														"var(--extracted-r6o4lv, rgb(255, 255, 255))",
												}}
											>
												{"Notifications"}
											</motion.p>
										</React.Fragment>
									</RichText>
									<SVG
										className={"framer-128x2e2"}
										data-framer-name={"tabler-icon-arrow-narrow-right"}
										fill={"rgba(0,0,0,1)"}
										intrinsicHeight={19}
										intrinsicWidth={18}
										layoutDependency={layoutDependency}
										layoutId={"epLhIAK89"}
										svg={
											'<svg width="18" height="19" viewBox="0 0 18 19" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path d="M3.75 9.78125H14.25M14.25 9.78125L11.25 12.7812M14.25 9.78125L11.25 6.78125" stroke="white" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>\n</svg>\n'
										}
										withExternalLayout={true}
									/>
								</motion.a>
							</Link>
							<Link href={"https://docs.velt.dev/webhooks/overview"}>
								<motion.a
									className={"framer-1c6dnxx framer-1efpc6r"}
									data-framer-name={"Frame 1707478602"}
									layoutDependency={layoutDependency}
									layoutId={"yaq5d1Wst"}
									style={{
										opacity: 0.5,
									}}
									whileHover={animation}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-iviinz"}
										data-framer-name={"Web Hooks"}
										fonts={["GF;Urbanist-regular"]}
										layoutDependency={layoutDependency}
										layoutId={"Y2ud8_owX"}
										style={{
											"--extracted-r6o4lv": "rgb(255, 255, 255)",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector": "R0Y7VXJiYW5pc3QtcmVndWxhcg==",
													"--framer-font-family":
														'"Urbanist", "Urbanist Placeholder", sans-serif',
													"--framer-letter-spacing": "-0.01em",
													"--framer-line-height": "100%",
													"--framer-text-color":
														"var(--extracted-r6o4lv, rgb(255, 255, 255))",
												}}
											>
												{"Web Hooks"}
											</motion.p>
										</React.Fragment>
									</RichText>
									<SVG
										className={"framer-5xkrn"}
										data-framer-name={"tabler-icon-arrow-narrow-right"}
										fill={"rgba(0,0,0,1)"}
										intrinsicHeight={19}
										intrinsicWidth={18}
										layoutDependency={layoutDependency}
										layoutId={"ziTh_Rk2n"}
										svg={
											'<svg width="18" height="19" viewBox="0 0 18 19" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path d="M3.75 9.78125H14.25M14.25 9.78125L11.25 12.7812M14.25 9.78125L11.25 6.78125" stroke="white" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>\n</svg>\n'
										}
										withExternalLayout={true}
									/>
								</motion.a>
							</Link>
						</motion.div>
						<motion.div
							className={"framer-6tszrk"}
							data-framer-name={"Frame 1707478690"}
							layoutDependency={layoutDependency}
							layoutId={"p21eNkbUG"}
						>
							<ImageWithFX
								__framer__animate={{
									transition: transition1,
								}}
								__framer__animateOnce={true}
								__framer__enter={animation1}
								__framer__exit={animation2}
								__framer__styleAppearEffectEnabled={true}
								__framer__threshold={0}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								background={{
									alt: "",
									fit: "fill",
									sizes: "926px",
									...toResponsiveImage(JdNxW81k2),
								}}
								className={"framer-14ddaen"}
								data-framer-name={"image 2904"}
								layoutDependency={layoutDependency}
								layoutId={"g_WI1RKgN"}
								style={{
									borderBottomLeftRadius: 12,
									borderBottomRightRadius: 12,
									borderTopLeftRadius: 12,
									borderTopRightRadius: 12,
								}}
								transformTemplate={transformTemplate2}
								{...addPropertyOverrides(
									{
										GNTRH2pIC: {
											background: {
												alt: "",
												fit: "fill",
												sizes: "calc(min(309px, 100vw) * 0.8991)",
												src: "https://framerusercontent.com/images/hqAvxp9TgsLIi54OpUg87ofyAO0.png",
												srcSet:
													"https://framerusercontent.com/images/hqAvxp9TgsLIi54OpUg87ofyAO0.png?scale-down-to=1024 562w, https://framerusercontent.com/images/hqAvxp9TgsLIi54OpUg87ofyAO0.png 800w",
											},
											transformTemplate: transformTemplate3,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
							{isDisplayed1() && (
								<motion.div
									className={"framer-1sc3sub"}
									layoutDependency={layoutDependency}
									layoutId={"CBddN_gRf"}
									style={{
										background:
											"linear-gradient(180deg, rgba(0, 0, 0, 0) 0%, rgb(0, 0, 0) 100%)",
									}}
								/>
							)}
						</motion.div>
						{isDisplayed() && (
							<SVG
								className={"framer-za4nda"}
								data-framer-name={"Vector 280"}
								fill={"rgba(0,0,0,1)"}
								intrinsicHeight={471}
								intrinsicWidth={495}
								layoutDependency={layoutDependency}
								layoutId={"xIU2ej6Lx"}
								svg={
									'<svg width="495" height="471" viewBox="-1 -1 495 471" fill="none" xmlns="http://www.w3.org/2000/svg">\n<g opacity="0.08" filter="url(#filter0_f_1054_23529)">\n<path d="M5.00619 21.2845L0.5 468.496C5.21565 0.5 5.21567 0.496094 492.5 0.496094H26.0051C14.4897 0.496094 5.12221 9.76967 5.00619 21.2845Z" fill="white"/>\n</g>\n<defs>\n<filter id="filter0_f_1054_23529" x="-119.5" y="-119.504" width="732" height="708" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">\n<feFlood flood-opacity="0" result="BackgroundImageFix"/>\n<feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape"/>\n<feGaussianBlur stdDeviation="60" result="effect1_foregroundBlur_1054_23529"/>\n</filter>\n</defs>\n</svg>\n'
								}
								withExternalLayout={true}
							/>
						)}
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	'.framer-VAuK9[data-border="true"]::after, .framer-VAuK9 [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-VAuK9.framer-1efpc6r, .framer-VAuK9 .framer-1efpc6r { display: block; }",
	".framer-VAuK9.framer-fuymxz { height: 626px; overflow: hidden; position: relative; width: 984px; will-change: var(--framer-will-change-override, transform); }",
	".framer-VAuK9 .framer-1rvrywd { flex: none; height: 100%; left: 0px; overflow: visible; position: absolute; top: 0px; width: 100%; }",
	".framer-VAuK9 .framer-idz00w { flex: none; height: 100%; left: calc(50.00000000000002% - 100% / 2); overflow: visible; position: absolute; top: calc(50.00000000000002% - 100% / 2); width: 100%; }",
	".framer-VAuK9 .framer-o4eszn { bottom: 3px; flex: none; left: 3px; overflow: visible; position: absolute; right: 6px; top: 3px; }",
	".framer-VAuK9 .framer-giwkua { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: flex-start; left: 70px; overflow: visible; padding: 0px 0px 0px 0px; position: absolute; top: 72px; width: 357px; }",
	".framer-VAuK9 .framer-k2kym6 { flex: none; height: 114px; overflow: visible; position: relative; width: 357px; }",
	".framer-VAuK9 .framer-814kjm { bottom: -30px; flex: none; left: calc(49.85994397759106% - 100% / 2); overflow: visible; position: absolute; top: 0px; width: 100%; }",
	".framer-VAuK9 .framer-1ab36qn { flex: none; height: auto; left: 0px; position: absolute; top: 0px; white-space: pre-wrap; width: 357px; word-break: break-word; word-wrap: break-word; }",
	".framer-VAuK9 .framer-4n9kgd { flex: none; height: auto; left: 0px; position: absolute; top: 0px; white-space: pre-wrap; width: 329px; word-break: break-word; word-wrap: break-word; }",
	".framer-VAuK9 .framer-a22jyy { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px 0px 0px 0px; position: relative; width: 100%; }",
	".framer-VAuK9 .framer-ajhfxr, .framer-VAuK9 .framer-zfahbc { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-VAuK9 .framer-1yhz4lx { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 357px; word-break: break-word; word-wrap: break-word; }",
	".framer-VAuK9 .framer-2ytsxh { align-content: flex-start; align-items: flex-start; bottom: 66px; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; left: 70px; overflow: visible; padding: 0px 0px 0px 0px; position: absolute; width: 357px; }",
	".framer-VAuK9 .framer-1rf4s0a { -webkit-user-select: auto; align-content: center; align-items: center; cursor: pointer; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: visible; padding: 12px 0px 12px 0px; position: relative; text-decoration: none; user-select: auto; width: 100%; }",
	".framer-VAuK9 .framer-1dx27i4, .framer-VAuK9 .framer-1z0e5b5, .framer-VAuK9 .framer-108ntd6, .framer-VAuK9 .framer-ayislt, .framer-VAuK9 .framer-iviinz { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-VAuK9 .framer-19wmea1, .framer-VAuK9 .framer-63o7uy, .framer-VAuK9 .framer-webhcr, .framer-VAuK9 .framer-128x2e2, .framer-VAuK9 .framer-5xkrn { flex: none; height: 19px; position: relative; width: 18px; }",
	".framer-VAuK9 .framer-1n5qvw, .framer-VAuK9 .framer-1ic7nqs, .framer-VAuK9 .framer-19f2jr6, .framer-VAuK9 .framer-1c6dnxx { align-content: center; align-items: center; cursor: pointer; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: visible; padding: 12px 0px 12px 0px; position: relative; text-decoration: none; width: 100%; }",
	".framer-VAuK9 .framer-6tszrk { flex: none; height: 548px; overflow: hidden; position: absolute; right: 0px; top: calc(50.00000000000002% - 548px / 2); width: 50%; }",
	".framer-VAuK9 .framer-14ddaen { aspect-ratio: 1.6882406563354604 / 1; bottom: 0px; flex: none; left: 0px; position: absolute; top: 0px; width: var(--framer-aspect-ratio-supported, 925px); }",
	".framer-VAuK9 .framer-1sc3sub { bottom: 0px; flex: none; height: 113px; left: calc(49.88123515439432% - 89.90498812351544% / 2); overflow: visible; position: absolute; width: 90%; }",
	".framer-VAuK9 .framer-za4nda { flex: none; height: 471px; left: -1px; position: absolute; top: -1px; width: 495px; z-index: -1; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-VAuK9 .framer-giwkua, .framer-VAuK9 .framer-a22jyy, .framer-VAuK9 .framer-2ytsxh { gap: 0px; } .framer-VAuK9 .framer-giwkua > * { margin: 0px; margin-bottom: calc(12px / 2); margin-top: calc(12px / 2); } .framer-VAuK9 .framer-giwkua > :first-child, .framer-VAuK9 .framer-a22jyy > :first-child, .framer-VAuK9 .framer-2ytsxh > :first-child { margin-top: 0px; } .framer-VAuK9 .framer-giwkua > :last-child, .framer-VAuK9 .framer-a22jyy > :last-child, .framer-VAuK9 .framer-2ytsxh > :last-child { margin-bottom: 0px; } .framer-VAuK9 .framer-a22jyy > *, .framer-VAuK9 .framer-2ytsxh > * { margin: 0px; margin-bottom: calc(0px / 2); margin-top: calc(0px / 2); } }",
	".framer-VAuK9.framer-v-1nbyqef.framer-fuymxz { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; padding: 0px 0px 0px 0px; width: 309px; }",
	".framer-VAuK9.framer-v-1nbyqef .framer-giwkua { left: unset; order: 1; padding: 24px 24px 24px 24px; position: relative; top: unset; width: 100%; }",
	".framer-VAuK9.framer-v-1nbyqef .framer-1yhz4lx, .framer-VAuK9.framer-v-1jlveax .framer-1yhz4lx { width: 100%; }",
	".framer-VAuK9.framer-v-1nbyqef .framer-2ytsxh { bottom: unset; left: unset; order: 2; padding: 52px 24px 52px 24px; position: relative; width: 100%; }",
	".framer-VAuK9.framer-v-1nbyqef .framer-6tszrk { order: 3; position: relative; right: unset; top: unset; width: 100%; }",
	".framer-VAuK9.framer-v-1nbyqef .framer-14ddaen { aspect-ratio: 0.550185873605948 / 1; bottom: unset; height: var(--framer-aspect-ratio-supported, 505px); left: 50%; top: 12px; width: 90%; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-VAuK9.framer-v-1nbyqef.framer-fuymxz { gap: 0px; } .framer-VAuK9.framer-v-1nbyqef.framer-fuymxz > * { margin: 0px; margin-bottom: calc(0px / 2); margin-top: calc(0px / 2); } .framer-VAuK9.framer-v-1nbyqef.framer-fuymxz > :first-child { margin-top: 0px; } .framer-VAuK9.framer-v-1nbyqef.framer-fuymxz > :last-child { margin-bottom: 0px; } }",
	".framer-VAuK9.framer-v-1jlveax.framer-fuymxz { width: 500px; }",
	".framer-VAuK9.framer-v-1jlveax .framer-giwkua { left: 40px; top: 42px; width: 255px; }",
	".framer-VAuK9.framer-v-1jlveax .framer-k2kym6 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; padding: 0px 0px 0px 0px; width: 100%; }",
	".framer-VAuK9.framer-v-1jlveax .framer-814kjm { bottom: unset; height: 96px; left: unset; position: relative; top: unset; }",
	".framer-VAuK9.framer-v-1jlveax .framer-1ab36qn { left: 0px; top: 50%; width: 100%; }",
	".framer-VAuK9.framer-v-1jlveax .framer-4n9kgd { left: 1px; top: 50%; width: 255px; }",
	".framer-VAuK9.framer-v-1jlveax .framer-2ytsxh { left: 40px; width: 254px; }",
	".framer-VAuK9.framer-v-1jlveax .framer-6tszrk { right: -70px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-VAuK9.framer-v-1jlveax .framer-k2kym6 { gap: 0px; } .framer-VAuK9.framer-v-1jlveax .framer-k2kym6 > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-VAuK9.framer-v-1jlveax .framer-k2kym6 > :first-child { margin-left: 0px; } .framer-VAuK9.framer-v-1jlveax .framer-k2kym6 > :last-child { margin-right: 0px; } }",
];
var Framerb1FF1OSoZ = withCSS(Component, css, "framer-VAuK9");
var stdin_default = Framerb1FF1OSoZ;
Framerb1FF1OSoZ.displayName = "New / Docs";
Framerb1FF1OSoZ.defaultProps = {
	height: 626,
	width: 984,
};
addPropertyControls(Framerb1FF1OSoZ, {
	variant: {
		options: ["JZBdb6dZt", "GNTRH2pIC", "yMPc50SXr"],
		optionTitles: ["Desktop", "Mobile", "Tablet"],
		title: "Variant",
		type: ControlType.Enum,
	},
	JdNxW81k2: {
		__defaultAssetReference:
			"data:framer/asset-reference,III6HelzIbYe8CCUgwM08HcUsA.png?originalFilename=image+2904.png&preferredSize=auto",
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
});
addFonts(Framerb1FF1OSoZ, [
	{
		family: "Urbanist",
		source: "google",
		style: "normal",
		url: "https://fonts.gstatic.com/s/urbanist/v15/L0xjDF02iFML4hGCyOCpRdycFsGxSrqDLBkfE5OrS8SlKw.woff2",
		weight: "700",
	},
	{
		family: "Urbanist",
		source: "google",
		style: "normal",
		url: "https://fonts.gstatic.com/s/urbanist/v15/L0xjDF02iFML4hGCyOCpRdycFsGxSrqDyx4fE5OrS8SlKw.woff2",
		weight: "400",
	},
]);

// virtual:new/docs
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "GNTRH2pIC",
	md: "yMPc50SXr",
	"2xl": "JZBdb6dZt",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7e5af5d66397a8a15ce8ab3401cf6b1aee707f00a906595a26b5cba8a8c88d97"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders DocsFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7e5af5d66397a8a15ce8ab3401cf6b1aee707f00a906595a26b5cba8a8c88d97"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var docs_default = ComponentWithRoot;
export { docs_default as default };
