// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 7e5af5d66397a8a1 "Velt", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant 1' | 'Variant 2' | 'Variant 3' | 'Variant 4' | 'Mobile' | 'Variant 6' | 'Variant 7' | 'Variant 8' // Variant
}} Props

 */
import { stdin_default as stdin_default2 } from "./chunks/chunk-CTBEW7HV.js";
import { stdin_default } from "./chunks/chunk-YRWKAGDD.js";
import "./chunks/chunk-ACNUKPBG.js";
import "./chunks/chunk-BD734V3N.js";
import { routes } from "./chunks/chunk-K34BXH3K.js";
import "./chunks/chunk-WSFCRVEQ.js";

// virtual:integrations-listing
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/RMJ2DfGF1MVkBmKp6Ujr/7uyXYRDyQOalqomi8TwX/lGkovhK5l.js
import {
	jsx as _jsx,
	jsxs as _jsxs,
	Fragment as _Fragment,
} from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ChildrenCanSuspend,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	PathVariablesContext,
	ResolveLinks,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useQueryData,
	useRouter,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/Ts2kJ0i2pDyr8YGZ5OQK/bm2dBwmK4920s97Z00hB/Z1rTLexh0.js
import {
	addPropertyControls as e5,
	ControlType as l3,
	QueryEngine as t4,
} from "unframer";

// /:https://framerusercontent.com/modules/Ts2kJ0i2pDyr8YGZ5OQK/bm2dBwmK4920s97Z00hB/Z1rTLexh0-0.js
import { ControlType as y } from "unframer";
import { ControlType as P } from "unframer";
var __unframerWindow = typeof window !== "undefined" ? window : void 0;
var t;
var e = Object.create;
var r = Object.defineProperty;
var n = Object.getOwnPropertyDescriptor;
var i = Object.getOwnPropertyNames;
var s = Object.getPrototypeOf;
var a = Object.prototype.hasOwnProperty;
var o = (t32, e42, n22) =>
	e42 in t32
		? r(t32, e42, {
				enumerable: true,
				configurable: true,
				writable: true,
				value: n22,
			})
		: (t32[e42] = n22);
var u = (t32, e42) =>
	function () {
		return (
			e42 ||
				(0, t32[i(t32)[0]])(
					(e42 = {
						exports: {},
					}).exports,
					e42,
				),
			e42.exports
		);
	};
var l = (t32, e42, s22, o22) => {
	if ((e42 && "object" == typeof e42) || "function" == typeof e42)
		for (let u22 of i(e42))
			a.call(t32, u22) ||
				u22 === s22 ||
				r(t32, u22, {
					get: () => e42[u22],
					enumerable: !(o22 = n(e42, u22)) || o22.enumerable,
				});
	return t32;
};
var h = (t32, n22, i22) => (
	(i22 = null != t32 ? e(s(t32)) : {}),
	l(
		// If the importer is in node compatibility mode or this is not an ESM
		// file that has been converted to a CommonJS file using a Babel-
		// compatible transform (i.e. "__esModule" has not been set), then set
		// "default" to the CommonJS "module.exports" for node compatibility.
		!n22 && t32 && t32.__esModule
			? i22
			: r(i22, "default", {
					value: t32,
					enumerable: true,
				}),
		t32,
	)
);
var c = (t32, e42, r22) => o(t32, "symbol" != typeof e42 ? e42 + "" : e42, r22);
var f = u({
	"../../../node_modules/dataloader/index.js"(t32, e42) {
		var r22,
			n22 = /* @__PURE__ */ (function () {
				function t42(t5, e6) {
					if ("function" != typeof t5)
						throw TypeError(
							"DataLoader must be constructed with a function which accepts Array<key> and returns Promise<Array<value>>, but got: " +
								t5 +
								".",
						);
					(this._batchLoadFn = t5),
						(this._maxBatchSize = (function (t6) {
							if (!(!t6 || false !== t6.batch)) return 1;
							var e7 = t6 && t6.maxBatchSize;
							if (void 0 === e7) return 1 / 0;
							if ("number" != typeof e7 || e7 < 1)
								throw TypeError(
									"maxBatchSize must be a positive number: " + e7,
								);
							return e7;
						})(e6)),
						(this._batchScheduleFn = (function (t6) {
							var e7 = t6 && t6.batchScheduleFn;
							if (void 0 === e7) return i22;
							if ("function" != typeof e7)
								throw TypeError("batchScheduleFn must be a function: " + e7);
							return e7;
						})(e6)),
						(this._cacheKeyFn = (function (t6) {
							var e7 = t6 && t6.cacheKeyFn;
							if (void 0 === e7)
								return function (t7) {
									return t7;
								};
							if ("function" != typeof e7)
								throw TypeError("cacheKeyFn must be a function: " + e7);
							return e7;
						})(e6)),
						(this._cacheMap = (function (t6) {
							if (!(!t6 || false !== t6.cache)) return null;
							var e7 = t6 && t6.cacheMap;
							if (void 0 === e7) return /* @__PURE__ */ new Map();
							if (null !== e7) {
								var r3 = ["get", "set", "delete", "clear"].filter(
									function (t7) {
										return e7 && "function" != typeof e7[t7];
									},
								);
								if (0 !== r3.length)
									throw TypeError(
										"Custom cacheMap missing methods: " + r3.join(", "),
									);
							}
							return e7;
						})(e6)),
						(this._batch = null),
						(this.name = e6 && e6.name ? e6.name : null);
				}
				var e52 = t42.prototype;
				return (
					(e52.load = function (t5) {
						if (null == t5)
							throw TypeError(
								"The loader.load() function must be called with a value, but got: " +
									String(t5) +
									".",
							);
						var e6 = (function (t6) {
								var e7 = t6._batch;
								if (
									null !== e7 &&
									!e7.hasDispatched &&
									e7.keys.length < t6._maxBatchSize
								)
									return e7;
								var r4 = {
									hasDispatched: false,
									keys: [],
									callbacks: [],
								};
								return (
									(t6._batch = r4),
									t6._batchScheduleFn(function () {
										(function (t7, e8) {
											var r5;
											if (((e8.hasDispatched = true), 0 === e8.keys.length)) {
												a22(e8);
												return;
											}
											try {
												r5 = t7._batchLoadFn(e8.keys);
											} catch (r6) {
												return s22(
													t7,
													e8,
													TypeError(
														"DataLoader must be constructed with a function which accepts Array<key> and returns Promise<Array<value>>, but the function errored synchronously: " +
															String(r6) +
															".",
													),
												);
											}
											if (!r5 || "function" != typeof r5.then)
												return s22(
													t7,
													e8,
													TypeError(
														"DataLoader must be constructed with a function which accepts Array<key> and returns Promise<Array<value>>, but the function did not return a Promise: " +
															String(r5) +
															".",
													),
												);
											r5.then(function (t8) {
												if (!o22(t8))
													throw TypeError(
														"DataLoader must be constructed with a function which accepts Array<key> and returns Promise<Array<value>>, but the function did not return a Promise of an Array: " +
															String(t8) +
															".",
													);
												if (t8.length !== e8.keys.length)
													throw TypeError(
														"DataLoader must be constructed with a function which accepts Array<key> and returns Promise<Array<value>>, but the function did not return a Promise of an Array of the same length as the Array of keys.\n\nKeys:\n" +
															String(e8.keys) +
															"\n\nValues:\n" +
															String(t8),
													);
												a22(e8);
												for (var r6 = 0; r6 < e8.callbacks.length; r6++) {
													var n4 = t8[r6];
													n4 instanceof Error
														? e8.callbacks[r6].reject(n4)
														: e8.callbacks[r6].resolve(n4);
												}
											}).catch(function (r6) {
												s22(t7, e8, r6);
											});
										})(t6, r4);
									}),
									r4
								);
							})(this),
							r3 = this._cacheMap,
							n32 = this._cacheKeyFn(t5);
						if (r3) {
							var i3 = r3.get(n32);
							if (i3) {
								var u22 = e6.cacheHits || (e6.cacheHits = []);
								return new Promise(function (t6) {
									u22.push(function () {
										t6(i3);
									});
								});
							}
						}
						e6.keys.push(t5);
						var l22 = new Promise(function (t6, r4) {
							e6.callbacks.push({
								resolve: t6,
								reject: r4,
							});
						});
						return r3 && r3.set(n32, l22), l22;
					}),
					(e52.loadMany = function (t5) {
						if (!o22(t5))
							throw TypeError(
								"The loader.loadMany() function must be called with Array<key> but got: " +
									t5 +
									".",
							);
						for (var e6 = [], r3 = 0; r3 < t5.length; r3++)
							e6.push(
								this.load(t5[r3]).catch(function (t6) {
									return t6;
								}),
							);
						return Promise.all(e6);
					}),
					(e52.clear = function (t5) {
						var e6 = this._cacheMap;
						if (e6) {
							var r3 = this._cacheKeyFn(t5);
							e6.delete(r3);
						}
						return this;
					}),
					(e52.clearAll = function () {
						var t5 = this._cacheMap;
						return t5 && t5.clear(), this;
					}),
					(e52.prime = function (t5, e6) {
						var r3 = this._cacheMap;
						if (r3) {
							var n32,
								i3 = this._cacheKeyFn(t5);
							void 0 === r3.get(i3) &&
								(e6 instanceof Error
									? (n32 = Promise.reject(e6)).catch(function () {})
									: (n32 = Promise.resolve(e6)),
								r3.set(i3, n32));
						}
						return this;
					}),
					t42
				);
			})(),
			i22 =
				"object" == typeof process && "function" == typeof process.nextTick
					? function (t42) {
							r22 || (r22 = Promise.resolve()),
								r22.then(function () {
									process.nextTick(t42);
								});
						}
					: "function" == typeof setImmediate
						? function (t42) {
								setImmediate(t42);
							}
						: function (t42) {
								setTimeout(t42);
							};
		function s22(t42, e52, r3) {
			a22(e52);
			for (var n32 = 0; n32 < e52.keys.length; n32++)
				t42.clear(e52.keys[n32]), e52.callbacks[n32].reject(r3);
		}
		function a22(t42) {
			if (t42.cacheHits)
				for (var e52 = 0; e52 < t42.cacheHits.length; e52++)
					t42.cacheHits[e52]();
		}
		function o22(t42) {
			return (
				"object" == typeof t42 &&
				null !== t42 &&
				"number" == typeof t42.length &&
				(0 === t42.length ||
					(t42.length > 0 &&
						Object.prototype.hasOwnProperty.call(t42, t42.length - 1)))
			);
		}
		e42.exports = n22;
	},
});
var d = h(f());
var g = {
	Uint8: 1,
	Uint16: 2,
	Uint32: 4,
	BigUint64: 8,
	Int8: 1,
	Int16: 2,
	Int32: 4,
	BigInt64: 8,
	Float32: 4,
	Float64: 8,
};
var p = class {
	getOffset() {
		return this.offset;
	}
	ensureLength(t32) {
		let e42 = this.bytes.length;
		if (!(this.offset + t32 <= e42)) throw Error("Reading out of bounds");
	}
	readUint8() {
		let t32 = g.Uint8;
		this.ensureLength(t32);
		let e42 = this.view.getUint8(this.offset);
		return (this.offset += t32), e42;
	}
	readUint16() {
		let t32 = g.Uint16;
		this.ensureLength(t32);
		let e42 = this.view.getUint16(this.offset);
		return (this.offset += t32), e42;
	}
	readUint32() {
		let t32 = g.Uint32;
		this.ensureLength(t32);
		let e42 = this.view.getUint32(this.offset);
		return (this.offset += t32), e42;
	}
	readUint64() {
		let t32 = this.readBigUint64();
		return Number(t32);
	}
	readBigUint64() {
		let t32 = g.BigUint64;
		this.ensureLength(t32);
		let e42 = this.view.getBigUint64(this.offset);
		return (this.offset += t32), e42;
	}
	readInt8() {
		let t32 = g.Int8;
		this.ensureLength(t32);
		let e42 = this.view.getInt8(this.offset);
		return (this.offset += t32), e42;
	}
	readInt16() {
		let t32 = g.Int16;
		this.ensureLength(t32);
		let e42 = this.view.getInt16(this.offset);
		return (this.offset += t32), e42;
	}
	readInt32() {
		let t32 = g.Int32;
		this.ensureLength(t32);
		let e42 = this.view.getInt32(this.offset);
		return (this.offset += t32), e42;
	}
	readInt64() {
		let t32 = this.readBigInt64();
		return Number(t32);
	}
	readBigInt64() {
		let t32 = g.BigInt64;
		this.ensureLength(t32);
		let e42 = this.view.getBigInt64(this.offset);
		return (this.offset += t32), e42;
	}
	readFloat32() {
		let t32 = g.Float32;
		this.ensureLength(t32);
		let e42 = this.view.getFloat32(this.offset);
		return (this.offset += t32), e42;
	}
	readFloat64() {
		let t32 = g.Float64;
		this.ensureLength(t32);
		let e42 = this.view.getFloat64(this.offset);
		return (this.offset += t32), e42;
	}
	readBytes(t32) {
		let e42 = this.offset,
			r22 = e42 + t32,
			n22 = this.bytes.subarray(e42, r22);
		return (this.offset = r22), n22;
	}
	readString() {
		let t32 = this.readUint32(),
			e42 = this.readBytes(t32);
		return this.decoder.decode(e42);
	}
	readJson() {
		let t32 = this.readString();
		return JSON.parse(t32);
	}
	constructor(t32) {
		(this.bytes = t32),
			c(this, "offset", 0),
			c(this, "view"),
			c(this, "decoder", new TextDecoder()),
			(this.view = v(this.bytes));
	}
};
function v(t32) {
	return new DataView(t32.buffer, t32.byteOffset, t32.byteLength);
}
var m = "undefined" != typeof __unframerWindow;
var w = m && "function" == typeof __unframerWindow.requestIdleCallback;
function I(t32, ...e42) {
	if (!t32)
		throw Error(
			"Assertion Error" + (e42.length > 0 ? ": " + e42.join(" ") : ""),
		);
}
function b(t32) {
	throw Error(`Unexpected value: ${t32}`);
}
var U = 1024;
var S = 1.5;
var k = (t32) => 2 ** t32 - 1;
var L = (t32) => -(2 ** (t32 - 1));
var B = (t32) => 2 ** (t32 - 1) - 1;
var E = {
	Uint8: 0,
	Uint16: 0,
	Uint32: 0,
	Uint64: 0,
	BigUint64: 0,
	Int8: L(8),
	Int16: L(16),
	Int32: L(32),
	Int64: Number.MIN_SAFE_INTEGER,
	BigInt64: -(BigInt(2) ** BigInt(63)),
};
var M = {
	Uint8: k(8),
	Uint16: k(16),
	Uint32: k(32),
	Uint64: Number.MAX_SAFE_INTEGER,
	BigUint64: BigInt(2) ** BigInt(64) - BigInt(1),
	Int8: B(8),
	Int16: B(16),
	Int32: B(32),
	Int64: Number.MAX_SAFE_INTEGER,
	BigInt64: BigInt(2) ** BigInt(63) - BigInt(1),
};
function T(t32, e42, r22, n22) {
	I(t32 >= e42, t32, "outside lower bound for", n22),
		I(t32 <= r22, t32, "outside upper bound for", n22);
}
var F = class {
	getOffset() {
		return this.offset;
	}
	slice(t32 = 0, e42 = this.offset) {
		return this.bytes.slice(t32, e42);
	}
	subarray(t32 = 0, e42 = this.offset) {
		return this.bytes.subarray(t32, e42);
	}
	ensureLength(t32) {
		let e42 = this.bytes.length;
		if (this.offset + t32 <= e42) return;
		let r22 = new Uint8Array(Math.ceil(e42 * S) + t32);
		r22.set(this.bytes), (this.bytes = r22), (this.view = v(r22));
	}
	writeUint8(t32) {
		T(t32, E.Uint8, M.Uint8, "Uint8");
		let e42 = g.Uint8;
		this.ensureLength(e42),
			this.view.setUint8(this.offset, t32),
			(this.offset += e42);
	}
	writeUint16(t32) {
		T(t32, E.Uint16, M.Uint16, "Uint16");
		let e42 = g.Uint16;
		this.ensureLength(e42),
			this.view.setUint16(this.offset, t32),
			(this.offset += e42);
	}
	writeUint32(t32) {
		T(t32, E.Uint32, M.Uint32, "Uint32");
		let e42 = g.Uint32;
		this.ensureLength(e42),
			this.view.setUint32(this.offset, t32),
			(this.offset += e42);
	}
	writeUint64(t32) {
		T(t32, E.Uint64, M.Uint64, "Uint64");
		let e42 = BigInt(t32);
		this.writeBigUint64(e42);
	}
	writeBigUint64(t32) {
		T(t32, E.BigUint64, M.BigUint64, "BigUint64");
		let e42 = g.BigUint64;
		this.ensureLength(e42),
			this.view.setBigUint64(this.offset, t32),
			(this.offset += e42);
	}
	writeInt8(t32) {
		T(t32, E.Int8, M.Int8, "Int8");
		let e42 = g.Int8;
		this.ensureLength(e42),
			this.view.setInt8(this.offset, t32),
			(this.offset += e42);
	}
	writeInt16(t32) {
		T(t32, E.Int16, M.Int16, "Int16");
		let e42 = g.Int16;
		this.ensureLength(e42),
			this.view.setInt16(this.offset, t32),
			(this.offset += e42);
	}
	writeInt32(t32) {
		T(t32, E.Int32, M.Int32, "Int32");
		let e42 = g.Int32;
		this.ensureLength(e42),
			this.view.setInt32(this.offset, t32),
			(this.offset += e42);
	}
	writeInt64(t32) {
		T(t32, E.Int64, M.Int64, "Int64");
		let e42 = BigInt(t32);
		this.writeBigInt64(e42);
	}
	writeBigInt64(t32) {
		T(t32, E.BigInt64, M.BigInt64, "BigInt64");
		let e42 = g.BigInt64;
		this.ensureLength(e42),
			this.view.setBigInt64(this.offset, t32),
			(this.offset += e42);
	}
	writeFloat32(t32) {
		let e42 = g.Float32;
		this.ensureLength(e42),
			this.view.setFloat32(this.offset, t32),
			(this.offset += e42);
	}
	writeFloat64(t32) {
		let e42 = g.Float64;
		this.ensureLength(e42),
			this.view.setFloat64(this.offset, t32),
			(this.offset += e42);
	}
	writeBytes(t32) {
		let e42 = t32.length;
		this.ensureLength(e42),
			this.bytes.set(t32, this.offset),
			(this.offset += e42);
	}
	encodeString(t32) {
		let e42 = this.encodedStrings.get(t32);
		if (e42) return e42;
		let r22 = this.encoder.encode(t32);
		return this.encodedStrings.set(t32, r22), r22;
	}
	writeString(t32) {
		let e42 = this.encodeString(t32),
			r22 = e42.length;
		this.writeUint32(r22), this.writeBytes(e42);
	}
	writeJson(t32) {
		let e42 = JSON.stringify(t32);
		this.writeString(e42);
	}
	constructor() {
		c(this, "offset", 0),
			c(this, "bytes", new Uint8Array(U)),
			c(this, "view", v(this.bytes)),
			c(this, "encoder", new TextEncoder()),
			c(this, "encodedStrings", /* @__PURE__ */ new Map());
	}
};
function x(t32) {
	return "string" == typeof t32;
}
function N(t32) {
	return Number.isFinite(t32);
}
function A(t32) {
	return null === t32;
}
var O = class t2 {
	static fromString(e42) {
		let [r22, n22, i22] = e42.split("/").map(Number);
		return (
			I(N(r22), "Invalid chunkId"),
			I(N(n22), "Invalid offset"),
			I(N(i22), "Invalid length"),
			new t2(r22, n22, i22)
		);
	}
	toString() {
		return `${this.chunkId}/${this.offset}/${this.length}`;
	}
	static read(e42) {
		let r22 = e42.readUint16(),
			n22 = e42.readUint32(),
			i22 = e42.readUint32();
		return new t2(r22, n22, i22);
	}
	write(t32) {
		t32.writeUint16(this.chunkId),
			t32.writeUint32(this.offset),
			t32.writeUint32(this.length);
	}
	compare(t32) {
		return this.chunkId < t32.chunkId
			? -1
			: this.chunkId > t32.chunkId
				? 1
				: this.offset < t32.offset
					? -1
					: this.offset > t32.offset
						? 1
						: (I(this.length === t32.length), 0);
	}
	constructor(t32, e42, r22) {
		(this.chunkId = t32), (this.offset = e42), (this.length = r22);
	}
};
function R(t32) {
	if (A(t32)) return 0;
	switch (t32.type) {
		case P.Array:
			return 1;
		case P.Boolean:
			return 2;
		case P.Color:
			return 3;
		case P.Date:
			return 4;
		case P.Enum:
			return 5;
		case P.File:
			return 6;
		case P.ResponsiveImage:
			return 10;
		case P.Link:
			return 7;
		case P.Number:
			return 8;
		case P.Object:
			return 9;
		case P.RichText:
			return 11;
		case P.String:
			return 12;
		case P.VectorSetItem:
			return 13;
		default:
			b(t32);
	}
}
function q(e42) {
	let r22 = e42.readUint16(),
		n22 = [];
	for (let i22 = 0; i22 < r22; i22++) {
		let r3 = t.read(e42);
		n22.push(r3);
	}
	return {
		type: P.Array,
		value: n22,
	};
}
function _(e42, r22) {
	for (let n22 of (e42.writeUint16(r22.value.length), r22.value))
		t.write(e42, n22);
}
function D(e42, r22, n22) {
	let i22 = e42.value.length,
		s22 = r22.value.length;
	if (i22 < s22) return -1;
	if (i22 > s22) return 1;
	for (let s32 = 0; s32 < i22; s32++) {
		let i3 = e42.value[s32],
			a22 = r22.value[s32],
			o22 = t.compare(i3, a22, n22);
		if (0 !== o22) return o22;
	}
	return 0;
}
function j(t32) {
	return {
		type: P.Boolean,
		value: 0 !== t32.readUint8(),
	};
}
function C(t32, e42) {
	t32.writeUint8(e42.value ? 1 : 0);
}
function J(t32, e42) {
	return t32.value < e42.value ? -1 : t32.value > e42.value ? 1 : 0;
}
function V(t32) {
	return {
		type: P.Color,
		value: t32.readString(),
	};
}
function W(t32, e42) {
	t32.writeString(e42.value);
}
function $(t32, e42) {
	return t32.value < e42.value ? -1 : t32.value > e42.value ? 1 : 0;
}
function z(t32) {
	let e42 = t32.readInt64(),
		r22 = new Date(e42);
	return {
		type: P.Date,
		value: r22.toISOString(),
	};
}
function G(t32, e42) {
	let r22 = new Date(e42.value),
		n22 = r22.getTime();
	t32.writeInt64(n22);
}
function K(t32, e42) {
	let r22 = new Date(t32.value),
		n22 = new Date(e42.value);
	return r22 < n22 ? -1 : r22 > n22 ? 1 : 0;
}
function H(t32) {
	return {
		type: P.Enum,
		value: t32.readString(),
	};
}
function X(t32, e42) {
	t32.writeString(e42.value);
}
function Q(t32, e42) {
	return t32.value < e42.value ? -1 : t32.value > e42.value ? 1 : 0;
}
function Y(t32) {
	return {
		type: P.File,
		value: t32.readString(),
	};
}
function Z(t32, e42) {
	t32.writeString(e42.value);
}
function tt(t32, e42) {
	return t32.value < e42.value ? -1 : t32.value > e42.value ? 1 : 0;
}
function te(t32) {
	return {
		type: P.Link,
		value: t32.readJson(),
	};
}
function tr(t32, e42) {
	t32.writeJson(e42.value);
}
function tn(t32, e42) {
	let r22 = JSON.stringify(t32.value),
		n22 = JSON.stringify(e42.value);
	return r22 < n22 ? -1 : r22 > n22 ? 1 : 0;
}
function ti(t32) {
	return {
		type: P.Number,
		value: t32.readFloat64(),
	};
}
function ts(t32, e42) {
	t32.writeFloat64(e42.value);
}
function ta(t32, e42) {
	return t32.value < e42.value ? -1 : t32.value > e42.value ? 1 : 0;
}
function to(e42) {
	let r22 = e42.readUint16(),
		n22 = {};
	for (let i22 = 0; i22 < r22; i22++) {
		let r3 = e42.readString();
		n22[r3] = t.read(e42);
	}
	return {
		type: P.Object,
		value: n22,
	};
}
function tu(e42, r22) {
	let n22 = Object.entries(r22.value);
	for (let [r3, i22] of (e42.writeUint16(n22.length), n22))
		e42.writeString(r3), t.write(e42, i22);
}
function tl(e42, r22, n22) {
	let i22 = Object.keys(e42.value).sort(),
		s22 = Object.keys(r22.value).sort();
	if (i22.length < s22.length) return -1;
	if (i22.length > s22.length) return 1;
	for (let a22 = 0; a22 < i22.length; a22++) {
		let o22 = i22[a22],
			u22 = s22[a22];
		if (o22 < u22) return -1;
		if (o22 > u22) return 1;
		let l22 = e42.value[o22] ?? null,
			h22 = r22.value[u22] ?? null,
			c22 = t.compare(l22, h22, n22);
		if (0 !== c22) return c22;
	}
	return 0;
}
function th(t32) {
	return {
		type: P.ResponsiveImage,
		value: t32.readJson(),
	};
}
function tc(t32, e42) {
	t32.writeJson(e42.value);
}
function tf(t32, e42) {
	let r22 = JSON.stringify(t32.value),
		n22 = JSON.stringify(e42.value);
	return r22 < n22 ? -1 : r22 > n22 ? 1 : 0;
}
function td(t32) {
	let e42 = t32.readInt8();
	if (0 === e42)
		return {
			type: P.RichText,
			value: t32.readUint32(),
		};
	if (1 === e42)
		return {
			type: P.RichText,
			value: t32.readString(),
		};
	throw Error("Invalid rich text pointer");
}
function tg(t32, e42) {
	if (N(e42.value)) {
		t32.writeInt8(0), t32.writeUint32(e42.value);
		return;
	}
	if (x(e42.value)) {
		t32.writeInt8(1), t32.writeString(e42.value);
		return;
	}
	throw Error("Invalid rich text pointer");
}
function tp(t32, e42) {
	let r22 = t32.value,
		n22 = e42.value;
	if ((N(r22) && N(n22)) || (x(r22) && x(n22)))
		return r22 < n22 ? -1 : r22 > n22 ? 1 : 0;
	throw Error("Invalid rich text pointer");
}
function tv(t32) {
	return {
		type: P.String,
		value: t32.readString(),
	};
}
function ty(t32, e42) {
	t32.writeString(e42.value);
}
function tm(t32, e42, r22) {
	let n22 = t32.value,
		i22 = e42.value;
	return (0 === r22.type &&
		((n22 = t32.value.toLowerCase()), (i22 = e42.value.toLowerCase())),
	n22 < i22)
		? -1
		: n22 > i22
			? 1
			: 0;
}
function tw(t32) {
	return {
		type: P.VectorSetItem,
		value: t32.readUint32(),
	};
}
function tI(t32, e42) {
	t32.writeUint32(e42.value);
}
function tb(t32, e42) {
	let r22 = t32.value,
		n22 = e42.value;
	return r22 < n22 ? -1 : r22 > n22 ? 1 : 0;
}
((t32) => {
	(t32.read = function (t42) {
		let e42 = t42.readUint8();
		switch (e42) {
			case 0:
				return null;
			case 1:
				return q(t42);
			case 2:
				return j(t42);
			case 3:
				return V(t42);
			case 4:
				return z(t42);
			case 5:
				return H(t42);
			case 6:
				return Y(t42);
			case 7:
				return te(t42);
			case 8:
				return ti(t42);
			case 9:
				return to(t42);
			case 10:
				return th(t42);
			case 11:
				return td(t42);
			case 12:
				return tv(t42);
			case 13:
				return tw(t42);
			default:
				b(e42);
		}
	}),
		(t32.write = function (t42, e42) {
			let r22 = R(e42);
			if ((t42.writeUint8(r22), !A(e42)))
				switch (e42.type) {
					case P.Array:
						return _(t42, e42);
					case P.Boolean:
						return C(t42, e42);
					case P.Color:
						return W(t42, e42);
					case P.Date:
						return G(t42, e42);
					case P.Enum:
						return X(t42, e42);
					case P.File:
						return Z(t42, e42);
					case P.Link:
						return tr(t42, e42);
					case P.Number:
						return ts(t42, e42);
					case P.Object:
						return tu(t42, e42);
					case P.ResponsiveImage:
						return tc(t42, e42);
					case P.RichText:
						return tg(t42, e42);
					case P.VectorSetItem:
						return tI(t42, e42);
					case P.String:
						return ty(t42, e42);
					default:
						b(e42);
				}
		}),
		(t32.compare = function (t42, e42, r22) {
			let n22 = R(t42),
				i22 = R(e42);
			if (n22 < i22) return -1;
			if (n22 > i22) return 1;
			if (A(t42) || A(e42)) return 0;
			switch (t42.type) {
				case P.Array:
					return I(e42.type === P.Array), D(t42, e42, r22);
				case P.Boolean:
					return I(e42.type === P.Boolean), J(t42, e42);
				case P.Color:
					return I(e42.type === P.Color), $(t42, e42);
				case P.Date:
					return I(e42.type === P.Date), K(t42, e42);
				case P.Enum:
					return I(e42.type === P.Enum), Q(t42, e42);
				case P.File:
					return I(e42.type === P.File), tt(t42, e42);
				case P.Link:
					return I(e42.type === P.Link), tn(t42, e42);
				case P.Number:
					return I(e42.type === P.Number), ta(t42, e42);
				case P.Object:
					return I(e42.type === P.Object), tl(t42, e42, r22);
				case P.ResponsiveImage:
					return I(e42.type === P.ResponsiveImage), tf(t42, e42);
				case P.RichText:
					return I(e42.type === P.RichText), tp(t42, e42);
				case P.VectorSetItem:
					return I(e42.type === P.VectorSetItem), tb(t42, e42);
				case P.String:
					return I(e42.type === P.String), tm(t42, e42, r22);
				default:
					b(t42);
			}
		});
})(t || (t = {}));
var tU = class e2 {
	sortEntries() {
		this.entries.sort((e42, r22) => {
			for (let n22 = 0; n22 < this.fieldNames.length; n22++) {
				let i22 = e42.values[n22],
					s22 = r22.values[n22],
					a22 = t.compare(i22, s22, this.options.collation);
				if (0 !== a22) return a22;
			}
			return e42.pointer.compare(r22.pointer);
		});
	}
	static deserialize(r22) {
		let n22 = new p(r22),
			i22 = n22.readJson(),
			s22 = n22.readUint8(),
			a22 = [];
		for (let t32 = 0; t32 < s22; t32++) {
			let t42 = n22.readString();
			a22.push(t42);
		}
		let o22 = new e2(a22, {
				collation: i22,
			}),
			u22 = n22.readUint32();
		for (let e42 = 0; e42 < u22; e42++) {
			let e52 = [];
			for (let r4 = 0; r4 < s22; r4++) {
				let r5 = t.read(n22);
				e52.push(r5);
			}
			let r3 = O.read(n22);
			o22.entries.push({
				values: e52,
				pointer: r3,
			});
		}
		return o22;
	}
	serialize() {
		let e42 = new F();
		for (let t32 of (e42.writeJson(this.options.collation),
		e42.writeUint8(this.fieldNames.length),
		this.fieldNames))
			e42.writeString(t32);
		for (let r22 of (this.sortEntries(),
		e42.writeUint32(this.entries.length),
		this.entries)) {
			let { values: n22, pointer: i22 } = r22;
			for (let r3 of n22) t.write(e42, r3);
			i22.write(e42);
		}
		return e42.subarray();
	}
	addItem(t32, e42) {
		let r22 = this.fieldNames.map((e52) => t32.getField(e52) ?? null);
		this.entries.push({
			values: r22,
			pointer: e42,
		});
	}
	constructor(t32, e42) {
		(this.fieldNames = t32), (this.options = e42), c(this, "entries", []);
	}
};
var tS = 3;
var tk = 250;
var tL = [
	408,
	// Request Timeout
	429,
	// Too Many Requests
	500,
	// Internal Server Error
	502,
	// Bad Gateway
	503,
	// Service Unavailable
	504,
];
var tB = async (t32, e42) => {
	let r22 = 0;
	for (;;) {
		try {
			let n22 = await fetch(t32, e42);
			if (!tL.includes(n22.status) || ++r22 > tS) return n22;
		} catch (t42) {
			if (e42?.signal?.aborted || ++r22 > tS) throw t42;
		}
		await tE(r22);
	}
};
async function tE(t32) {
	let e42 = Math.floor(tk * (Math.random() + 1) * 2 ** (t32 - 1));
	await new Promise((t42) => {
		setTimeout(t42, e42);
	});
}
async function tM(t32, e42) {
	let r22 = tx(e42),
		n22 = [],
		i22 = 0;
	for (let t42 of r22)
		n22.push(`${t42.from}-${t42.to - 1}`), (i22 += t42.to - t42.from);
	let s22 = new URL(t32),
		a22 = n22.join(",");
	s22.searchParams.set("range", a22);
	let o22 = await tB(s22);
	if (200 !== o22.status)
		throw Error(`Request failed: ${o22.status} ${o22.statusText}`);
	let u22 = await o22.arrayBuffer(),
		l22 = new Uint8Array(u22);
	if (l22.length !== i22)
		throw Error("Request failed: Unexpected response length");
	let h22 = new tT(),
		c22 = 0;
	for (let t42 of r22) {
		let e52 = t42.to - t42.from,
			r3 = c22 + e52,
			n32 = l22.subarray(c22, r3);
		h22.write(t42.from, n32), (c22 = r3);
	}
	return e42.map((t42) => h22.read(t42.from, t42.to - t42.from));
}
var tT = class {
	read(t32, e42) {
		for (let r22 of this.chunks) {
			if (t32 < r22.start) break;
			if (t32 > r22.end) continue;
			if (t32 + e42 > r22.end) break;
			let n22 = t32 - r22.start,
				i22 = n22 + e42;
			return r22.data.slice(n22, i22);
		}
		throw Error("Missing data");
	}
	write(t32, e42) {
		let r22 = t32,
			n22 = r22 + e42.length,
			i22 = 0,
			s22 = this.chunks.length;
		for (; i22 < s22; i22++) {
			let t42 = this.chunks[i22];
			if ((I(t42, "Missing chunk"), !(r22 > t42.end))) {
				if (r22 > t42.start) {
					let n32 = r22 - t42.start,
						i3 = t42.data.subarray(0, n32);
					(e42 = tF(i3, e42)), (r22 = t42.start);
				}
				break;
			}
		}
		for (; s22 > i22; s22--) {
			let t42 = this.chunks[s22 - 1];
			if ((I(t42, "Missing chunk"), !(n22 < t42.start))) {
				if (n22 < t42.end) {
					let r3 = n22 - t42.start,
						i3 = t42.data.subarray(r3);
					(e42 = tF(e42, i3)), (n22 = t42.end);
				}
				break;
			}
		}
		let a22 = {
				start: r22,
				end: n22,
				data: e42,
			},
			o22 = s22 - i22;
		this.chunks.splice(i22, o22, a22);
	}
	constructor() {
		c(this, "chunks", []);
	}
};
function tF(t32, e42) {
	let r22 = t32.length + e42.length,
		n22 = new Uint8Array(r22);
	return n22.set(t32, 0), n22.set(e42, t32.length), n22;
}
function tx(t32) {
	I(t32.length > 0, "Must have at least one range");
	let e42 = [...t32].sort((t42, e52) => t42.from - e52.from),
		r22 = [];
	for (let t42 of e42) {
		let e52 = r22.length - 1,
			n22 = r22[e52];
		n22 && t42.from <= n22.to
			? (r22[e52] = {
					from: n22.from,
					to: Math.max(n22.to, t42.to),
				})
			: r22.push(t42);
	}
	return r22;
}
var tN = class {
	async loadModel() {
		let [t32] = await tM(this.options.url, [this.options.range]);
		return I(t32, "Failed to load model"), tU.deserialize(t32);
	}
	async getModel() {
		return (
			(this.modelPromise ??= this.loadModel()),
			(this.model ??= await this.modelPromise),
			this.model
		);
	}
	async lookupItems(t32) {
		I(t32.length === this.fields.length, "Invalid query length");
		let e42 = await this.getModel(),
			r22 = t32.reduce(
				(t42, e52, r3) =>
					t42.flatMap((t5) => {
						switch (e52.type) {
							case "All":
								return [t5];
							case "Equals":
								return this.queryEquals(t5, e52, r3);
							case "NotEquals":
								return this.queryNotEquals(t5, e52, r3);
							case "LessThan":
								return this.queryLessThan(t5, e52, r3);
							case "GreaterThan":
								return this.queryGreaterThan(t5, e52, r3);
							case "Contains":
								return this.queryContains(t5, e52, r3);
							case "StartsWith":
								return this.queryStartsWith(t5, e52, r3);
							case "EndsWith":
								return this.queryEndsWith(t5, e52, r3);
							default:
								b(e52);
						}
					}),
				[e42.entries],
			),
			n22 = [];
		for (let t42 of r22)
			for (let e52 of t42) {
				let t5 = {};
				for (let r3 = 0; r3 < this.options.fieldNames.length; r3++) {
					let n32 = this.options.fieldNames[r3],
						i22 = e52.values[r3];
					t5[n32] = i22;
				}
				n22.push({
					pointer: e52.pointer.toString(),
					data: t5,
				});
			}
		return n22;
	}
	queryEquals(t32, e42, r22) {
		let n22 = this.getLeftMost(t32, r22, e42.value),
			i22 = this.getRightMost(t32, r22, e42.value),
			s22 = t32.slice(n22, i22 + 1);
		return s22.length > 0 ? [s22] : [];
	}
	queryNotEquals(t32, e42, r22) {
		let n22 = this.getLeftMost(t32, r22, e42.value),
			i22 = this.getRightMost(t32, r22, e42.value),
			s22 = [],
			a22 = t32.slice(0, n22);
		a22.length > 0 && s22.push(a22);
		let o22 = t32.slice(i22 + 1);
		return o22.length > 0 && s22.push(o22), s22;
	}
	queryLessThan(t32, e42, r22) {
		let n22 = this.getRightMost(t32, r22, null);
		if (((t32 = t32.slice(n22 + 1)), e42.inclusive)) {
			let n32 = this.getRightMost(t32, r22, e42.value),
				i3 = t32.slice(0, n32 + 1);
			return i3.length > 0 ? [i3] : [];
		}
		let i22 = this.getLeftMost(t32, r22, e42.value),
			s22 = t32.slice(0, i22);
		return s22.length > 0 ? [s22] : [];
	}
	queryGreaterThan(t32, e42, r22) {
		let n22 = this.getRightMost(t32, r22, null);
		if (((t32 = t32.slice(n22 + 1)), e42.inclusive)) {
			let n32 = this.getLeftMost(t32, r22, e42.value),
				i3 = t32.slice(n32);
			return i3.length > 0 ? [i3] : [];
		}
		let i22 = this.getRightMost(t32, r22, e42.value),
			s22 = t32.slice(i22 + 1);
		return s22.length > 0 ? [s22] : [];
	}
	queryContains(t32, e42, r22) {
		return this.findItems(t32, r22, (t42) => {
			if (t42?.type !== y.String || e42.value?.type !== y.String) return false;
			let r3 = t42.value,
				n22 = e42.value.value;
			return (
				0 === this.collation.type &&
					((r3 = r3.toLowerCase()), (n22 = n22.toLowerCase())),
				r3.includes(n22)
			);
		});
	}
	queryStartsWith(t32, e42, r22) {
		return this.findItems(t32, r22, (t42) => {
			if (t42?.type !== y.String || e42.value?.type !== y.String) return false;
			let r3 = t42.value,
				n22 = e42.value.value;
			return (
				0 === this.collation.type &&
					((r3 = r3.toLowerCase()), (n22 = n22.toLowerCase())),
				r3.startsWith(n22)
			);
		});
	}
	queryEndsWith(t32, e42, r22) {
		return this.findItems(t32, r22, (t42) => {
			if (t42?.type !== y.String || e42.value?.type !== y.String) return false;
			let r3 = t42.value,
				n22 = e42.value.value;
			return (
				0 === this.collation.type &&
					((r3 = r3.toLowerCase()), (n22 = n22.toLowerCase())),
				r3.endsWith(n22)
			);
		});
	}
	/**
	 * Returns the index of the left most entry that is equal to the target.
	 *
	 * ```text
	 *   Left most
	 *       ↓
	 * ┌───┬───┬───┬───┬───┬───┐
	 * │ 1 │ 2 │ 2 │ 2 │ 2 │ 3 │
	 * └───┴───┴───┴───┴───┴───┘
	 * ```
	 *
	 * @param entries The entries array to search in.
	 * @param position The position of the value in the entry.
	 * @param target The target value to search for.
	 * @returns The index of the left most entry that is equal to the target.
	 */
	getLeftMost(e42, r22, n22) {
		let i22 = 0,
			s22 = e42.length;
		for (; i22 < s22; ) {
			let a22 = (i22 + s22) >> 1,
				o22 = e42[a22],
				u22 = o22.values[r22];
			0 > t.compare(u22, n22, this.collation) ? (i22 = a22 + 1) : (s22 = a22);
		}
		return i22;
	}
	/**
	 * Returns the index of the right most entry that is equal to the target.
	 *
	 * ```text
	 *              Right most
	 *                   ↓
	 * ┌───┬───┬───┬───┬───┬───┐
	 * │ 1 │ 2 │ 2 │ 2 │ 2 │ 3 │
	 * └───┴───┴───┴───┴───┴───┘
	 * ```
	 *
	 * @param entries The entries array to search in.
	 * @param position The position of the value in the entry.
	 * @param target The target value to search for.
	 * @returns The index of the right most entry that is equal to the target.
	 */
	getRightMost(e42, r22, n22) {
		let i22 = 0,
			s22 = e42.length;
		for (; i22 < s22; ) {
			let a22 = (i22 + s22) >> 1,
				o22 = e42[a22],
				u22 = o22.values[r22];
			t.compare(u22, n22, this.collation) > 0 ? (s22 = a22) : (i22 = a22 + 1);
		}
		return s22 - 1;
	}
	/**
	 * Finds all items that are matching the predicate and groups adjacent items together.
	 *
	 * @param entries The entries array to search in.
	 * @param position The position of the value in the entry.
	 * @param predicate The predicate to match the values against.
	 * @returns An array of chunks that match the predicate.
	 */
	findItems(t32, e42, r22) {
		let n22 = [],
			i22 = 0;
		for (let s22 = 0; s22 < t32.length; s22++) {
			let a22 = t32[s22],
				o22 = a22.values[e42],
				u22 = r22(o22);
			if (!u22) {
				if (i22 < s22) {
					let e52 = t32.slice(i22, s22);
					n22.push(e52);
				}
				i22 = s22 + 1;
			}
		}
		if (i22 < t32.length) {
			let e52 = t32.slice(i22);
			n22.push(e52);
		}
		return n22;
	}
	constructor(t32) {
		(this.options = t32),
			c(this, "schema"),
			c(this, "fields"),
			c(this, "supportedLookupTypes", [
				"All",
				"Equals",
				"NotEquals",
				"LessThan",
				"GreaterThan",
				"Contains",
				"StartsWith",
				"EndsWith",
				/* EndsWith */
			]),
			c(this, "modelPromise"),
			c(this, "model"),
			c(this, "collation");
		let e42 = {},
			r22 = [];
		for (let t42 of this.options.fieldNames) {
			let n22 = this.options.collectionSchema[t42];
			I(n22, "Missing definition for field", t42),
				(e42[t42] = n22),
				r22.push({
					type: "Identifier",
					name: t42,
				});
		}
		(this.schema = e42),
			(this.fields = r22),
			(this.collation = this.options.collation);
	}
};
var tA = class e3 {
	static read(r22) {
		let n22 = new e3(),
			i22 = r22.readUint16();
		for (let e42 = 0; e42 < i22; e42++) {
			let e52 = r22.readString(),
				i3 = t.read(r22);
			n22.setField(e52, i3);
		}
		return n22;
	}
	write(e42) {
		for (let [r22, n22] of (e42.writeUint16(this.fields.size), this.fields))
			e42.writeString(r22), t.write(e42, n22);
	}
	getData() {
		let t32 = {};
		for (let [e42, r22] of this.fields) t32[e42] = r22;
		return t32;
	}
	setField(t32, e42) {
		this.fields.set(t32, e42);
	}
	getField(t32) {
		return this.fields.get(t32);
	}
	constructor() {
		c(this, "fields", /* @__PURE__ */ new Map());
	}
};
var tO = class {
	scanItems() {
		return (
			(this.itemsPromise ??= tB(this.url).then(async (t32) => {
				if (!t32.ok)
					throw Error(`Request failed: ${t32.status} ${t32.statusText}`);
				let e42 = await t32.arrayBuffer(),
					r22 = new Uint8Array(e42),
					n22 = new p(r22),
					i22 = [],
					s22 = n22.readUint32();
				for (let t42 = 0; t42 < s22; t42++) {
					let t5 = n22.getOffset(),
						e52 = tA.read(n22),
						r3 = n22.getOffset() - t5,
						s32 = new O(this.id, t5, r3),
						a22 = s32.toString(),
						o22 = {
							pointer: a22,
							data: e52.getData(),
						};
					this.itemLoader.prime(a22, o22), i22.push(o22);
				}
				return i22;
			})),
			this.itemsPromise
		);
	}
	resolveItem(t32) {
		return this.itemLoader.load(t32);
	}
	constructor(t32, e42) {
		(this.id = t32),
			(this.url = e42),
			c(this, "itemsPromise"),
			c(
				this,
				"itemLoader",
				new d.default(async (t42) => {
					let e52 = t42.map((t5) => {
							let e6 = O.fromString(t5);
							return {
								from: e6.offset,
								to: e6.offset + e6.length,
							};
						}),
						r22 = await tM(this.url, e52);
					return r22.map((e6, r3) => {
						let n22 = new p(e6),
							i22 = tA.read(n22),
							s22 = t42[r3];
						return (
							I(s22, "Missing pointer"),
							{
								pointer: s22,
								data: i22.getData(),
							}
						);
					});
				}),
			);
	}
};
var tP = class {
	async scanItems() {
		let t32 = await Promise.all(
			this.chunks.map(async (t42) => t42.scanItems()),
		);
		return t32.flat();
	}
	resolveItems(t32) {
		return Promise.all(
			t32.map((t42) => {
				let e42 = O.fromString(t42),
					r22 = this.chunks[e42.chunkId];
				return I(r22, "Missing chunk"), r22.resolveItem(t42);
			}),
		);
	}
	compareItems(t32, e42) {
		let r22 = O.fromString(t32.pointer),
			n22 = O.fromString(e42.pointer);
		return r22.compare(n22);
	}
	compareValues(e42, r22, n22) {
		return t.compare(e42, r22, n22);
	}
	constructor(t32) {
		(this.options = t32),
			c(this, "id"),
			c(this, "schema"),
			c(this, "indexes"),
			c(this, "resolveRichText"),
			c(this, "resolveVectorSetItem"),
			c(this, "chunks"),
			(this.chunks = this.options.chunks.map((t42, e42) => new tO(e42, t42))),
			(this.schema = t32.schema),
			(this.indexes = t32.indexes),
			(this.resolveRichText = t32.resolveRichText),
			(this.resolveVectorSetItem = t32.resolveVectorSetItem),
			(this.id = t32.id);
	}
};

// /:https://framerusercontent.com/modules/Ts2kJ0i2pDyr8YGZ5OQK/bm2dBwmK4920s97Z00hB/Z1rTLexh0-1.js
import { jsx as e4 } from "react/jsx-runtime";
import {
	ComponentPresetsConsumer as t3,
	Link as r2,
	motion as n2,
} from "unframer";
import { isValidElement as o2 } from "react";
import { Fragment as c2, createElement as p2 } from "react";
var __unframerWindow2 = typeof window !== "undefined" ? window : void 0;
var i2;
var a2 = "undefined" != typeof __unframerWindow2;
var l2 = a2 && "function" == typeof __unframerWindow2.requestIdleCallback;
var u2 = "preload";
function f2(e22) {
	return (
		"object" == typeof e22 &&
		null !== e22 &&
		!(/* @__PURE__ */ o2(e22)) &&
		u2 in e22
	);
}
function s2(e22, ...t22) {
	if (!e22)
		throw Error(
			"Assertion Error" + (t22.length > 0 ? ": " + t22.join(" ") : ""),
		);
}
var m2 =
	(((i2 = m2 || {})[(i2.Fragment = 1)] = "Fragment"),
	(i2[(i2.Link = 2)] = "Link"),
	(i2[(i2.Module = 3)] = "Module"),
	(i2[(i2.Tag = 4)] = "Tag"),
	(i2[(i2.Text = 5)] = "Text"),
	i2);
function d2(o22) {
	let i22 = /* @__PURE__ */ new Map();
	return (a22) => {
		let l22 = i22.get(a22);
		if (l22) return l22;
		let u22 = JSON.parse(a22),
			m22 = (function i3(a3) {
				switch (a3[0]) {
					case 1: {
						let [, ...e22] = a3,
							t22 = e22.map(i3);
						return p2(c2, void 0, ...t22);
					}
					case 2: {
						let [, e22, ...t22] = a3,
							n22 = t22.map(i3);
						return p2(r2, e22, ...n22);
					}
					case 3: {
						let [, r22, n22, l32] = a3;
						for (let e22 of l32) {
							let t22 = n22[e22];
							t22 && (n22[e22] = i3(t22));
						}
						let u32 = o22[r22];
						return (
							s2(u32, "Module not found"),
							f2(u32) && u32.preload(),
							e4(t3, {
								componentIdentifier: r22,
								children: (t22) =>
									e4(u32, {
										...t22,
										...n22,
									}),
							})
						);
					}
					case 4: {
						let [, e22, t22, ...r22] = a3,
							o32 = r22.map(i3);
						if ("a" === e22) return <n2.a />;
						return p2(e22, t22, ...o32);
					}
					case 5: {
						let [, e22] = a3;
						return e22;
					}
				}
			})(u22);
		return i22.set(a22, m22), m22;
	};
}

// /:https://framerusercontent.com/modules/Ts2kJ0i2pDyr8YGZ5OQK/bm2dBwmK4920s97Z00hB/Z1rTLexh0.js
var o3 = {
	A1M36_wF7: {
		isNullable: true,
		type: l3.String,
	},
	AUvuAZKG6: {
		isNullable: true,
		type: l3.String,
	},
	bDGj1zhPG: {
		isNullable: true,
		type: l3.Link,
	},
	bPo7DuReu: {
		isNullable: true,
		type: l3.String,
	},
	createdAt: {
		isNullable: true,
		type: l3.Date,
	},
	dCamU91Hh: {
		isNullable: true,
		type: l3.String,
	},
	id: {
		isNullable: false,
		type: l3.String,
	},
	NA3gG2xfZ: {
		isNullable: true,
		type: l3.ResponsiveImage,
	},
	nextItemId: {
		isNullable: true,
		type: l3.String,
	},
	nlVlJRdFe: {
		isNullable: true,
		type: l3.String,
	},
	Obfhk6LhL: {
		isNullable: true,
		type: l3.String,
	},
	previousItemId: {
		isNullable: true,
		type: l3.String,
	},
	QPdQ7nnME: {
		isNullable: true,
		type: l3.ResponsiveImage,
	},
	QU_JfS62O: {
		isNullable: true,
		type: l3.String,
	},
	RAQ1Ki8_E: {
		isNullable: true,
		type: l3.String,
	},
	RAsd8Zr0l: {
		isNullable: true,
		type: l3.String,
	},
	rNkNL1QT6: {
		isNullable: true,
		type: l3.Enum,
	},
	sxTkt7WdT: {
		isNullable: true,
		type: l3.Link,
	},
	uoNRv8HSL: {
		isNullable: true,
		type: l3.ResponsiveImage,
	},
	updatedAt: {
		isNullable: true,
		type: l3.Date,
	},
	wbGwryVFD: {
		isNullable: true,
		type: l3.Link,
	},
	X2j9Ni0zk: {
		isNullable: true,
		type: l3.String,
	},
	Y20U6vsqH: {
		isNullable: true,
		type: l3.String,
	},
	zjAVjXMkb: {
		isNullable: true,
		type: l3.String,
	},
	ZlVUV9pZw: {
		isNullable: true,
		type: l3.ResponsiveImage,
	},
};
var n3 = ["id"];
var m3 = {
	type: 1,
};
var c3 = ["previousItemId"];
var s3 = ["nextItemId"];
var u3 = ["id", "zjAVjXMkb"];
var d3 = ["zjAVjXMkb", "id"];
var f3 = ["RAsd8Zr0l"];
var p3 = {
	type: 0,
};
var h2 = ["dCamU91Hh"];
var g2 = ["A1M36_wF7"];
var L2 = ["zjAVjXMkb"];
var y2 = ["AUvuAZKG6"];
var w2 = ["bDGj1zhPG"];
var N2 = ["sxTkt7WdT"];
var x2 = ["rNkNL1QT6"];
var S2 = ["QPdQ7nnME"];
var R2 = ["wbGwryVFD"];
var b2 = ["RAQ1Ki8_E"];
var Z2 = ["bPo7DuReu"];
var T2 = ["QU_JfS62O"];
var U2 = ["uoNRv8HSL"];
var k2 = ["X2j9Ni0zk"];
var A2 = ["Y20U6vsqH"];
var V2 = ["NA3gG2xfZ"];
var I2 = ["Obfhk6LhL"];
var v2 = ["nlVlJRdFe"];
var j2 = ["ZlVUV9pZw"];
var M2 = [];
var Q2 = (e22) => {
	let l22 = M2[e22];
	if (l22) return l22().then((e32) => e32.default);
};
var D2 = {};
var G2 = d2(D2);
var z2 = new t4();
var _2 = {
	collectionByLocaleId: {
		default: new tP({
			chunks: [
				new URL(
					"./Z1rTLexh0-chunk-default-0.framercms",
					"https://framerusercontent.com/modules/Ts2kJ0i2pDyr8YGZ5OQK/bm2dBwmK4920s97Z00hB/Z1rTLexh0.js",
				).href.replace("/modules/", "/cms/"),
			],
			id: "d02111a6-81a8-432e-9bb0-2169f1d8c909default",
			indexes: [
				new tN({
					collation: m3,
					collectionSchema: o3,
					fieldNames: n3,
					range: {
						from: 0,
						to: 433,
					},
					url: new URL(
						"./Z1rTLexh0-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/Ts2kJ0i2pDyr8YGZ5OQK/bm2dBwmK4920s97Z00hB/Z1rTLexh0.js",
					).href.replace("/modules/", "/cms/"),
				}),
				new tN({
					collation: m3,
					collectionSchema: o3,
					fieldNames: c3,
					range: {
						from: 433,
						to: 865,
					},
					url: new URL(
						"./Z1rTLexh0-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/Ts2kJ0i2pDyr8YGZ5OQK/bm2dBwmK4920s97Z00hB/Z1rTLexh0.js",
					).href.replace("/modules/", "/cms/"),
				}),
				new tN({
					collation: m3,
					collectionSchema: o3,
					fieldNames: s3,
					range: {
						from: 865,
						to: 1293,
					},
					url: new URL(
						"./Z1rTLexh0-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/Ts2kJ0i2pDyr8YGZ5OQK/bm2dBwmK4920s97Z00hB/Z1rTLexh0.js",
					).href.replace("/modules/", "/cms/"),
				}),
				new tN({
					collation: m3,
					collectionSchema: o3,
					fieldNames: u3,
					range: {
						from: 1293,
						to: 1979,
					},
					url: new URL(
						"./Z1rTLexh0-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/Ts2kJ0i2pDyr8YGZ5OQK/bm2dBwmK4920s97Z00hB/Z1rTLexh0.js",
					).href.replace("/modules/", "/cms/"),
				}),
				new tN({
					collation: m3,
					collectionSchema: o3,
					fieldNames: d3,
					range: {
						from: 1979,
						to: 2665,
					},
					url: new URL(
						"./Z1rTLexh0-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/Ts2kJ0i2pDyr8YGZ5OQK/bm2dBwmK4920s97Z00hB/Z1rTLexh0.js",
					).href.replace("/modules/", "/cms/"),
				}),
				new tN({
					collation: p3,
					collectionSchema: o3,
					fieldNames: f3,
					range: {
						from: 2665,
						to: 3107,
					},
					url: new URL(
						"./Z1rTLexh0-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/Ts2kJ0i2pDyr8YGZ5OQK/bm2dBwmK4920s97Z00hB/Z1rTLexh0.js",
					).href.replace("/modules/", "/cms/"),
				}),
				new tN({
					collation: p3,
					collectionSchema: o3,
					fieldNames: h2,
					range: {
						from: 3107,
						to: 3855,
					},
					url: new URL(
						"./Z1rTLexh0-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/Ts2kJ0i2pDyr8YGZ5OQK/bm2dBwmK4920s97Z00hB/Z1rTLexh0.js",
					).href.replace("/modules/", "/cms/"),
				}),
				new tN({
					collation: p3,
					collectionSchema: o3,
					fieldNames: g2,
					range: {
						from: 3855,
						to: 4752,
					},
					url: new URL(
						"./Z1rTLexh0-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/Ts2kJ0i2pDyr8YGZ5OQK/bm2dBwmK4920s97Z00hB/Z1rTLexh0.js",
					).href.replace("/modules/", "/cms/"),
				}),
				new tN({
					collation: p3,
					collectionSchema: o3,
					fieldNames: L2,
					range: {
						from: 4752,
						to: 5194,
					},
					url: new URL(
						"./Z1rTLexh0-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/Ts2kJ0i2pDyr8YGZ5OQK/bm2dBwmK4920s97Z00hB/Z1rTLexh0.js",
					).href.replace("/modules/", "/cms/"),
				}),
				new tN({
					collation: p3,
					collectionSchema: o3,
					fieldNames: y2,
					range: {
						from: 5194,
						to: 7555,
					},
					url: new URL(
						"./Z1rTLexh0-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/Ts2kJ0i2pDyr8YGZ5OQK/bm2dBwmK4920s97Z00hB/Z1rTLexh0.js",
					).href.replace("/modules/", "/cms/"),
				}),
				new tN({
					collation: p3,
					collectionSchema: o3,
					fieldNames: w2,
					range: {
						from: 7555,
						to: 8573,
					},
					url: new URL(
						"./Z1rTLexh0-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/Ts2kJ0i2pDyr8YGZ5OQK/bm2dBwmK4920s97Z00hB/Z1rTLexh0.js",
					).href.replace("/modules/", "/cms/"),
				}),
				new tN({
					collation: p3,
					collectionSchema: o3,
					fieldNames: N2,
					range: {
						from: 8573,
						to: 9880,
					},
					url: new URL(
						"./Z1rTLexh0-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/Ts2kJ0i2pDyr8YGZ5OQK/bm2dBwmK4920s97Z00hB/Z1rTLexh0.js",
					).href.replace("/modules/", "/cms/"),
				}),
				new tN({
					collation: p3,
					collectionSchema: o3,
					fieldNames: x2,
					range: {
						from: 9880,
						to: 10320,
					},
					url: new URL(
						"./Z1rTLexh0-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/Ts2kJ0i2pDyr8YGZ5OQK/bm2dBwmK4920s97Z00hB/Z1rTLexh0.js",
					).href.replace("/modules/", "/cms/"),
				}),
				new tN({
					collation: p3,
					collectionSchema: o3,
					fieldNames: S2,
					range: {
						from: 10320,
						to: 13496,
					},
					url: new URL(
						"./Z1rTLexh0-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/Ts2kJ0i2pDyr8YGZ5OQK/bm2dBwmK4920s97Z00hB/Z1rTLexh0.js",
					).href.replace("/modules/", "/cms/"),
				}),
				new tN({
					collation: p3,
					collectionSchema: o3,
					fieldNames: R2,
					range: {
						from: 13496,
						to: 14888,
					},
					url: new URL(
						"./Z1rTLexh0-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/Ts2kJ0i2pDyr8YGZ5OQK/bm2dBwmK4920s97Z00hB/Z1rTLexh0.js",
					).href.replace("/modules/", "/cms/"),
				}),
				new tN({
					collation: p3,
					collectionSchema: o3,
					fieldNames: b2,
					range: {
						from: 14888,
						to: 20665,
					},
					url: new URL(
						"./Z1rTLexh0-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/Ts2kJ0i2pDyr8YGZ5OQK/bm2dBwmK4920s97Z00hB/Z1rTLexh0.js",
					).href.replace("/modules/", "/cms/"),
				}),
				new tN({
					collation: p3,
					collectionSchema: o3,
					fieldNames: Z2,
					range: {
						from: 20665,
						to: 21564,
					},
					url: new URL(
						"./Z1rTLexh0-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/Ts2kJ0i2pDyr8YGZ5OQK/bm2dBwmK4920s97Z00hB/Z1rTLexh0.js",
					).href.replace("/modules/", "/cms/"),
				}),
				new tN({
					collation: p3,
					collectionSchema: o3,
					fieldNames: T2,
					range: {
						from: 21564,
						to: 22973,
					},
					url: new URL(
						"./Z1rTLexh0-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/Ts2kJ0i2pDyr8YGZ5OQK/bm2dBwmK4920s97Z00hB/Z1rTLexh0.js",
					).href.replace("/modules/", "/cms/"),
				}),
				new tN({
					collation: p3,
					collectionSchema: o3,
					fieldNames: U2,
					range: {
						from: 22973,
						to: 31318,
					},
					url: new URL(
						"./Z1rTLexh0-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/Ts2kJ0i2pDyr8YGZ5OQK/bm2dBwmK4920s97Z00hB/Z1rTLexh0.js",
					).href.replace("/modules/", "/cms/"),
				}),
				new tN({
					collation: p3,
					collectionSchema: o3,
					fieldNames: k2,
					range: {
						from: 31318,
						to: 32132,
					},
					url: new URL(
						"./Z1rTLexh0-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/Ts2kJ0i2pDyr8YGZ5OQK/bm2dBwmK4920s97Z00hB/Z1rTLexh0.js",
					).href.replace("/modules/", "/cms/"),
				}),
				new tN({
					collation: p3,
					collectionSchema: o3,
					fieldNames: A2,
					range: {
						from: 32132,
						to: 33796,
					},
					url: new URL(
						"./Z1rTLexh0-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/Ts2kJ0i2pDyr8YGZ5OQK/bm2dBwmK4920s97Z00hB/Z1rTLexh0.js",
					).href.replace("/modules/", "/cms/"),
				}),
				new tN({
					collation: p3,
					collectionSchema: o3,
					fieldNames: V2,
					range: {
						from: 33796,
						to: 42069,
					},
					url: new URL(
						"./Z1rTLexh0-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/Ts2kJ0i2pDyr8YGZ5OQK/bm2dBwmK4920s97Z00hB/Z1rTLexh0.js",
					).href.replace("/modules/", "/cms/"),
				}),
				new tN({
					collation: p3,
					collectionSchema: o3,
					fieldNames: I2,
					range: {
						from: 42069,
						to: 42985,
					},
					url: new URL(
						"./Z1rTLexh0-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/Ts2kJ0i2pDyr8YGZ5OQK/bm2dBwmK4920s97Z00hB/Z1rTLexh0.js",
					).href.replace("/modules/", "/cms/"),
				}),
				new tN({
					collation: p3,
					collectionSchema: o3,
					fieldNames: v2,
					range: {
						from: 42985,
						to: 44445,
					},
					url: new URL(
						"./Z1rTLexh0-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/Ts2kJ0i2pDyr8YGZ5OQK/bm2dBwmK4920s97Z00hB/Z1rTLexh0.js",
					).href.replace("/modules/", "/cms/"),
				}),
				new tN({
					collation: p3,
					collectionSchema: o3,
					fieldNames: j2,
					range: {
						from: 44445,
						to: 52730,
					},
					url: new URL(
						"./Z1rTLexh0-indexes-default-0.framercms",
						"https://framerusercontent.com/modules/Ts2kJ0i2pDyr8YGZ5OQK/bm2dBwmK4920s97Z00hB/Z1rTLexh0.js",
					).href.replace("/modules/", "/cms/"),
				}),
			],
			resolveRichText: G2,
			resolveVectorSetItem: Q2,
			schema: o3,
		}),
	},
	displayName: "Integrations",
	id: "d02111a6-81a8-432e-9bb0-2169f1d8c909",
};
var stdin_default3 = _2;
e5(_2, {
	RAsd8Zr0l: {
		defaultValue: "",
		title: "Lib name",
		type: l3.String,
	},
	dCamU91Hh: {
		defaultValue: "",
		title: "Title",
		type: l3.String,
	},
	A1M36_wF7: {
		defaultValue: "",
		title: "Desc",
		type: l3.String,
	},
	zjAVjXMkb: {
		preventLocalization: true,
		title: "Slug",
		type: l3.String,
	},
	AUvuAZKG6: {
		defaultValue: "",
		title: "MetaDescription",
		type: l3.String,
	},
	bDGj1zhPG: {
		title: "Demo Link",
		type: l3.Link,
	},
	sxTkt7WdT: {
		title: "GitHub Link",
		type: l3.Link,
	},
	rNkNL1QT6: {
		defaultValue: "WzlZLXQaw",
		options: [
			"WzlZLXQaw",
			"dBfhcaJ1v",
			"e__UfdGCc",
			"z_wSJ1nuW",
			"Ml3Ndg13p",
			"e8WqGScWM",
		],
		optionTitles: [
			"Messaging",
			"Storage",
			"CRM",
			"Analytics",
			"Workflow Automation",
			"Email",
		],
		title: "Category",
		type: l3.Enum,
	},
	QPdQ7nnME: {
		title: "Image",
		type: l3.ResponsiveImage,
	},
	wbGwryVFD: {
		title: "Docs Link",
		type: l3.Link,
	},
	RAQ1Ki8_E: {
		defaultValue: "",
		displayTextArea: true,
		title: "Code",
		type: l3.String,
	},
	bPo7DuReu: {
		defaultValue: "Connect Discord in your Velt Console",
		placeholder: "",
		title: "1 / title",
		type: l3.String,
	},
	QU_JfS62O: {
		defaultValue:
			"Go to advance web hook configs and create a new endpoint for Slack",
		title: "1 / desc",
		type: l3.String,
	},
	uoNRv8HSL: {
		__defaultAssetReference:
			"data:framer/asset-reference,ZJcR7DGCZJrD3VGIOxEJHSrMCqs.png?originalFilename=image.png&width=1160&height=756",
		title: "1 / image",
		type: l3.ResponsiveImage,
	},
	X2j9Ni0zk: {
		defaultValue: "In-built payload transformation",
		title: "2 / title",
		type: l3.String,
	},
	Y20U6vsqH: {
		defaultValue:
			"Take the event and model it for your consumption with simple javascript functions",
		title: "2 / desc",
		type: l3.String,
	},
	NA3gG2xfZ: {
		__defaultAssetReference:
			"data:framer/asset-reference,IQ7r5kXMUfsrLzaWBEOH6iJO14.png?originalFilename=image.png&width=1160&height=756",
		title: "2 / image",
		type: l3.ResponsiveImage,
	},
	Obfhk6LhL: {
		defaultValue: "Provide a unified customer experience",
		title: "3 / title",
		type: l3.String,
	},
	nlVlJRdFe: {
		defaultValue:
			"Build smarter customer flows by connecting services through webhooks.",
		placeholder: "",
		title: "3 / desc",
		type: l3.String,
	},
	ZlVUV9pZw: {
		__defaultAssetReference:
			"data:framer/asset-reference,AnYH1hoHhE4hS4fQrlPQqlioqPQ.png?originalFilename=image.png&width=1160&height=788",
		title: "3 / image",
		type: l3.ResponsiveImage,
	},
	createdAt: {
		title: "Created",
		type: l3.Date,
	},
	updatedAt: {
		title: "Updated",
		type: l3.Date,
	},
	previousItemId: {
		dataIdentifier: "local-module:collection/Z1rTLexh0:default",
		title: "Previous",
		type: l3.CollectionReference,
	},
	nextItemId: {
		dataIdentifier: "local-module:collection/Z1rTLexh0:default",
		title: "Next",
		type: l3.CollectionReference,
	},
});

// /:https://framerusercontent.com/modules/RMJ2DfGF1MVkBmKp6Ujr/7uyXYRDyQOalqomi8TwX/lGkovhK5l.js
var LibraryToggleLinkFonts = getFonts(stdin_default2);
var LibraryCardFonts = getFonts(stdin_default);
var cycleOrder = [
	"XPS0VWdZC",
	"pCY7IszQ1",
	"rCSrTIvRX",
	"pKmNOFtHN",
	"gcGEsr6wN",
	"Ob8l5wAYv",
	"MyiLHxvX_",
	"Y4aMApYN3",
];
var serializationHash = "framer-mmbvD";
var variantClassNames = {
	gcGEsr6wN: "framer-v-12xeefo",
	MyiLHxvX_: "framer-v-eqqpae",
	Ob8l5wAYv: "framer-v-f6zzdx",
	pCY7IszQ1: "framer-v-5efkic",
	pKmNOFtHN: "framer-v-qny1u0",
	rCSrTIvRX: "framer-v-1g817d2",
	XPS0VWdZC: "framer-v-1ut4d2y",
	Y4aMApYN3: "framer-v-edc8nv",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var QueryData = ({ query: query7, pageSize, children }) => {
	const data = useQueryData(query7);
	return children(data);
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Variant 1": "XPS0VWdZC",
	"Variant 2": "pCY7IszQ1",
	"Variant 3": "rCSrTIvRX",
	"Variant 4": "pKmNOFtHN",
	"Variant 6": "Ob8l5wAYv",
	"Variant 7": "MyiLHxvX_",
	"Variant 8": "Y4aMApYN3",
	Mobile: "gcGEsr6wN",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "XPS0VWdZC",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		wbGwryVFDikYy94ag2,
		zjAVjXMkbikYy94ag2,
		QPdQ7nnMEikYy94ag2,
		idikYy94ag2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "XPS0VWdZC",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const Ym4DLJw5D1hw9tff = activeVariantCallback(async (...args) => {
		setVariant("XPS0VWdZC");
	});
	const Ym4DLJw5D1n0pyca = activeVariantCallback(async (...args) => {
		setVariant("pCY7IszQ1");
	});
	const Ym4DLJw5D1ttp2kx = activeVariantCallback(async (...args) => {
		setVariant("rCSrTIvRX");
	});
	const Ym4DLJw5D1d0ea57 = activeVariantCallback(async (...args) => {
		setVariant("pKmNOFtHN");
	});
	const Ym4DLJw5Dwvers0 = activeVariantCallback(async (...args) => {
		setVariant("Ob8l5wAYv");
	});
	const Ym4DLJw5Dxxrbix = activeVariantCallback(async (...args) => {
		setVariant("MyiLHxvX_");
	});
	const Ym4DLJw5D1lz1tgl = activeVariantCallback(async (...args) => {
		setVariant("Y4aMApYN3");
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "gcGEsr6wN") return false;
		return true;
	};
	const router = useRouter();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1ut4d2y",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"XPS0VWdZC"}
						ref={refBinding}
						style={{
							backgroundColor: "rgb(255, 255, 255)",
							...style,
						}}
						{...addPropertyOverrides(
							{
								gcGEsr6wN: {
									"data-framer-name": "Mobile",
								},
								MyiLHxvX_: {
									"data-framer-name": "Variant 7",
								},
								Ob8l5wAYv: {
									"data-framer-name": "Variant 6",
								},
								pCY7IszQ1: {
									"data-framer-name": "Variant 2",
								},
								pKmNOFtHN: {
									"data-framer-name": "Variant 4",
								},
								rCSrTIvRX: {
									"data-framer-name": "Variant 3",
								},
								Y4aMApYN3: {
									"data-framer-name": "Variant 8",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						{isDisplayed() && (
							<motion.div
								className={"framer-1xxd029"}
								data-border={true}
								layoutDependency={layoutDependency}
								layoutId={"UYIubc00P"}
								style={{
									"--border-bottom-width": "1px",
									"--border-color": "rgba(34, 34, 34, 0.08)",
									"--border-left-width": "0px",
									"--border-right-width": "0px",
									"--border-style": "solid",
									"--border-top-width": "0px",
								}}
							>
								<ComponentViewportProvider
									height={38}
									width={`max((${componentViewport?.width || "100vw"} - 60px) / 7, 1px)`}
								>
									<SmartComponentScopedContainer
										className={"framer-6ayckh-container"}
										layoutDependency={layoutDependency}
										layoutId={"xRwDcmA9H-container"}
										nodeId={"xRwDcmA9H"}
										rendersWithMotion={true}
										scopeId={"lGkovhK5l"}
									>
										{_jsx(stdin_default2, {
											height: "100%",
											id: "xRwDcmA9H",
											layoutId: "xRwDcmA9H",
											lcP4DJ6hY: "All",
											style: {
												width: "100%",
											},
											variant: "rMMaHcRS8",
											width: "100%",
											Ym4DLJw5D: Ym4DLJw5D1hw9tff,
											...addPropertyOverrides(
												{
													MyiLHxvX_: {
														variant: "bRPYbZR1K",
													},
													Ob8l5wAYv: {
														variant: "bRPYbZR1K",
													},
													pCY7IszQ1: {
														variant: "bRPYbZR1K",
													},
													pKmNOFtHN: {
														variant: "bRPYbZR1K",
													},
													rCSrTIvRX: {
														variant: "bRPYbZR1K",
													},
													Y4aMApYN3: {
														variant: "bRPYbZR1K",
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
								<ComponentViewportProvider
									height={38}
									width={`max((${componentViewport?.width || "100vw"} - 60px) / 7, 1px)`}
								>
									<SmartComponentScopedContainer
										className={"framer-vfnc5f-container"}
										layoutDependency={layoutDependency}
										layoutId={"dzoSOvRnq-container"}
										nodeId={"dzoSOvRnq"}
										rendersWithMotion={true}
										scopeId={"lGkovhK5l"}
									>
										{_jsx(stdin_default2, {
											height: "100%",
											id: "dzoSOvRnq",
											layoutId: "dzoSOvRnq",
											lcP4DJ6hY: "Messaging",
											style: {
												width: "100%",
											},
											variant: "bRPYbZR1K",
											width: "100%",
											Ym4DLJw5D: Ym4DLJw5D1n0pyca,
											...addPropertyOverrides(
												{
													pCY7IszQ1: {
														variant: "rMMaHcRS8",
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
								<ComponentViewportProvider
									height={38}
									width={`max((${componentViewport?.width || "100vw"} - 60px) / 7, 1px)`}
								>
									<SmartComponentScopedContainer
										className={"framer-1gep1y0-container"}
										layoutDependency={layoutDependency}
										layoutId={"dgW4yOJB0-container"}
										nodeId={"dgW4yOJB0"}
										rendersWithMotion={true}
										scopeId={"lGkovhK5l"}
									>
										{_jsx(stdin_default2, {
											height: "100%",
											id: "dgW4yOJB0",
											layoutId: "dgW4yOJB0",
											lcP4DJ6hY: "Storage",
											style: {
												width: "100%",
											},
											variant: "bRPYbZR1K",
											width: "100%",
											Ym4DLJw5D: Ym4DLJw5D1ttp2kx,
											...addPropertyOverrides(
												{
													rCSrTIvRX: {
														variant: "rMMaHcRS8",
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
								<ComponentViewportProvider
									height={38}
									width={`max((${componentViewport?.width || "100vw"} - 60px) / 7, 1px)`}
								>
									<SmartComponentScopedContainer
										className={"framer-rkqvl-container"}
										layoutDependency={layoutDependency}
										layoutId={"xKYZl12LG-container"}
										nodeId={"xKYZl12LG"}
										rendersWithMotion={true}
										scopeId={"lGkovhK5l"}
									>
										{_jsx(stdin_default2, {
											height: "100%",
											id: "xKYZl12LG",
											layoutId: "xKYZl12LG",
											lcP4DJ6hY: "CRM",
											style: {
												width: "100%",
											},
											variant: "bRPYbZR1K",
											width: "100%",
											Ym4DLJw5D: Ym4DLJw5D1d0ea57,
											...addPropertyOverrides(
												{
													pKmNOFtHN: {
														variant: "rMMaHcRS8",
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
								<ComponentViewportProvider
									height={38}
									width={`max((${componentViewport?.width || "100vw"} - 60px) / 7, 1px)`}
								>
									<SmartComponentScopedContainer
										className={"framer-1f9rvhh-container"}
										layoutDependency={layoutDependency}
										layoutId={"Iy3sW76I4-container"}
										nodeId={"Iy3sW76I4"}
										rendersWithMotion={true}
										scopeId={"lGkovhK5l"}
									>
										{_jsx(stdin_default2, {
											height: "100%",
											id: "Iy3sW76I4",
											layoutId: "Iy3sW76I4",
											lcP4DJ6hY: "Analytics",
											style: {
												width: "100%",
											},
											variant: "bRPYbZR1K",
											width: "100%",
											Ym4DLJw5D: Ym4DLJw5Dwvers0,
											...addPropertyOverrides(
												{
													Ob8l5wAYv: {
														variant: "rMMaHcRS8",
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
								<ComponentViewportProvider
									height={38}
									width={`max((${componentViewport?.width || "100vw"} - 60px) / 7, 1px)`}
								>
									<SmartComponentScopedContainer
										className={"framer-th0roi-container"}
										layoutDependency={layoutDependency}
										layoutId={"ewCbyEW8f-container"}
										nodeId={"ewCbyEW8f"}
										rendersWithMotion={true}
										scopeId={"lGkovhK5l"}
									>
										{_jsx(stdin_default2, {
											height: "100%",
											id: "ewCbyEW8f",
											layoutId: "ewCbyEW8f",
											lcP4DJ6hY: "Workflows",
											style: {
												width: "100%",
											},
											variant: "bRPYbZR1K",
											width: "100%",
											Ym4DLJw5D: Ym4DLJw5Dxxrbix,
											...addPropertyOverrides(
												{
													MyiLHxvX_: {
														variant: "rMMaHcRS8",
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
								<ComponentViewportProvider
									height={38}
									width={`max((${componentViewport?.width || "100vw"} - 60px) / 7, 1px)`}
								>
									<SmartComponentScopedContainer
										className={"framer-1q7yicf-container"}
										layoutDependency={layoutDependency}
										layoutId={"v5ds_RC0Y-container"}
										nodeId={"v5ds_RC0Y"}
										rendersWithMotion={true}
										scopeId={"lGkovhK5l"}
									>
										{_jsx(stdin_default2, {
											height: "100%",
											id: "v5ds_RC0Y",
											layoutId: "v5ds_RC0Y",
											lcP4DJ6hY: "Emails",
											style: {
												width: "100%",
											},
											variant: "bRPYbZR1K",
											width: "100%",
											Ym4DLJw5D: Ym4DLJw5D1lz1tgl,
											...addPropertyOverrides(
												{
													Y4aMApYN3: {
														variant: "rMMaHcRS8",
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							</motion.div>
						)}
						<motion.div
							className={"framer-moe8ch"}
							layoutDependency={layoutDependency}
							layoutId={"ikYy94ag2"}
						>
							<ChildrenCanSuspend>
								<QueryData
									query={{
										from: {
											alias: "ikYy94ag2",
											data: stdin_default3,
											type: "Collection",
										},
										select: [
											{
												collection: "ikYy94ag2",
												name: "wbGwryVFD",
												type: "Identifier",
											},
											{
												collection: "ikYy94ag2",
												name: "zjAVjXMkb",
												type: "Identifier",
											},
											{
												collection: "ikYy94ag2",
												name: "QPdQ7nnME",
												type: "Identifier",
											},
											{
												collection: "ikYy94ag2",
												name: "id",
												type: "Identifier",
											},
										],
									}}
									{...addPropertyOverrides(
										{
											MyiLHxvX_: {
												query: {
													from: {
														alias: "ikYy94ag2",
														data: stdin_default3,
														type: "Collection",
													},
													select: [
														{
															collection: "ikYy94ag2",
															name: "wbGwryVFD",
															type: "Identifier",
														},
														{
															collection: "ikYy94ag2",
															name: "zjAVjXMkb",
															type: "Identifier",
														},
														{
															collection: "ikYy94ag2",
															name: "QPdQ7nnME",
															type: "Identifier",
														},
														{
															collection: "ikYy94ag2",
															name: "id",
															type: "Identifier",
														},
													],
													where: {
														left: {
															collection: "ikYy94ag2",
															name: "rNkNL1QT6",
															type: "Identifier",
														},
														operator: "==",
														right: {
															type: "LiteralValue",
															value: "Ml3Ndg13p",
														},
														type: "BinaryOperation",
													},
												},
											},
											Ob8l5wAYv: {
												query: {
													from: {
														alias: "ikYy94ag2",
														data: stdin_default3,
														type: "Collection",
													},
													select: [
														{
															collection: "ikYy94ag2",
															name: "wbGwryVFD",
															type: "Identifier",
														},
														{
															collection: "ikYy94ag2",
															name: "zjAVjXMkb",
															type: "Identifier",
														},
														{
															collection: "ikYy94ag2",
															name: "QPdQ7nnME",
															type: "Identifier",
														},
														{
															collection: "ikYy94ag2",
															name: "id",
															type: "Identifier",
														},
													],
													where: {
														left: {
															collection: "ikYy94ag2",
															name: "rNkNL1QT6",
															type: "Identifier",
														},
														operator: "==",
														right: {
															type: "LiteralValue",
															value: "z_wSJ1nuW",
														},
														type: "BinaryOperation",
													},
												},
											},
											pCY7IszQ1: {
												query: {
													from: {
														alias: "ikYy94ag2",
														data: stdin_default3,
														type: "Collection",
													},
													select: [
														{
															collection: "ikYy94ag2",
															name: "wbGwryVFD",
															type: "Identifier",
														},
														{
															collection: "ikYy94ag2",
															name: "zjAVjXMkb",
															type: "Identifier",
														},
														{
															collection: "ikYy94ag2",
															name: "QPdQ7nnME",
															type: "Identifier",
														},
														{
															collection: "ikYy94ag2",
															name: "id",
															type: "Identifier",
														},
													],
													where: {
														left: {
															collection: "ikYy94ag2",
															name: "rNkNL1QT6",
															type: "Identifier",
														},
														operator: "==",
														right: {
															type: "LiteralValue",
															value: "WzlZLXQaw",
														},
														type: "BinaryOperation",
													},
												},
											},
											pKmNOFtHN: {
												query: {
													from: {
														alias: "ikYy94ag2",
														data: stdin_default3,
														type: "Collection",
													},
													select: [
														{
															collection: "ikYy94ag2",
															name: "wbGwryVFD",
															type: "Identifier",
														},
														{
															collection: "ikYy94ag2",
															name: "zjAVjXMkb",
															type: "Identifier",
														},
														{
															collection: "ikYy94ag2",
															name: "QPdQ7nnME",
															type: "Identifier",
														},
														{
															collection: "ikYy94ag2",
															name: "id",
															type: "Identifier",
														},
													],
													where: {
														left: {
															collection: "ikYy94ag2",
															name: "rNkNL1QT6",
															type: "Identifier",
														},
														operator: "==",
														right: {
															type: "LiteralValue",
															value: "e__UfdGCc",
														},
														type: "BinaryOperation",
													},
												},
											},
											rCSrTIvRX: {
												query: {
													from: {
														alias: "ikYy94ag2",
														data: stdin_default3,
														type: "Collection",
													},
													select: [
														{
															collection: "ikYy94ag2",
															name: "wbGwryVFD",
															type: "Identifier",
														},
														{
															collection: "ikYy94ag2",
															name: "zjAVjXMkb",
															type: "Identifier",
														},
														{
															collection: "ikYy94ag2",
															name: "QPdQ7nnME",
															type: "Identifier",
														},
														{
															collection: "ikYy94ag2",
															name: "id",
															type: "Identifier",
														},
													],
													where: {
														left: {
															collection: "ikYy94ag2",
															name: "rNkNL1QT6",
															type: "Identifier",
														},
														operator: "==",
														right: {
															type: "LiteralValue",
															value: "dBfhcaJ1v",
														},
														type: "BinaryOperation",
													},
												},
											},
											Y4aMApYN3: {
												query: {
													from: {
														alias: "ikYy94ag2",
														data: stdin_default3,
														type: "Collection",
													},
													select: [
														{
															collection: "ikYy94ag2",
															name: "wbGwryVFD",
															type: "Identifier",
														},
														{
															collection: "ikYy94ag2",
															name: "zjAVjXMkb",
															type: "Identifier",
														},
														{
															collection: "ikYy94ag2",
															name: "QPdQ7nnME",
															type: "Identifier",
														},
														{
															collection: "ikYy94ag2",
															name: "id",
															type: "Identifier",
														},
													],
													where: {
														left: {
															collection: "ikYy94ag2",
															name: "rNkNL1QT6",
															type: "Identifier",
														},
														operator: "==",
														right: {
															type: "LiteralValue",
															value: "e8WqGScWM",
														},
														type: "BinaryOperation",
													},
												},
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									{(collection, paginationInfo, loadMore) => (
										<_Fragment>
											{collection?.map(
												(
													{
														id: idikYy94ag22,
														QPdQ7nnME: QPdQ7nnMEikYy94ag22,
														wbGwryVFD: wbGwryVFDikYy94ag22,
														zjAVjXMkb: zjAVjXMkbikYy94ag22,
													},
													index,
												) => {
													wbGwryVFDikYy94ag22 ??= "";
													zjAVjXMkbikYy94ag22 ??= "";
													return (
														<LayoutGroup id={`ikYy94ag2-${idikYy94ag22}`}>
															<PathVariablesContext.Provider
																value={{
																	zjAVjXMkb: zjAVjXMkbikYy94ag22,
																}}
															>
																<motion.div
																	className={"framer-fu7lns"}
																	layoutDependency={layoutDependency}
																	layoutId={"yLA7g9aeV"}
																	style={{
																		backgroundColor: "rgb(247, 247, 247)",
																		borderBottomLeftRadius: 16,
																		borderBottomRightRadius: 16,
																		borderTopLeftRadius: 16,
																		borderTopRightRadius: 16,
																	}}
																>
																	<ResolveLinks
																		links={[
																			{
																				href: wbGwryVFDikYy94ag22,
																				implicitPathVariables: {
																					zjAVjXMkb: zjAVjXMkbikYy94ag22,
																				},
																			},
																			{
																				href: {
																					pathVariables: {
																						zjAVjXMkb: zjAVjXMkbikYy94ag22,
																					},
																					webPageId: "Mb9PNznan",
																				},
																				implicitPathVariables: {
																					zjAVjXMkb: zjAVjXMkbikYy94ag22,
																				},
																			},
																			{
																				href: wbGwryVFDikYy94ag22,
																				implicitPathVariables: {
																					zjAVjXMkb: zjAVjXMkbikYy94ag22,
																				},
																			},
																			{
																				href: {
																					pathVariables: {
																						zjAVjXMkb: zjAVjXMkbikYy94ag22,
																					},
																					webPageId: "Mb9PNznan",
																				},
																				implicitPathVariables: {
																					zjAVjXMkb: zjAVjXMkbikYy94ag22,
																				},
																			},
																			{
																				href: wbGwryVFDikYy94ag22,
																				implicitPathVariables: {
																					zjAVjXMkb: zjAVjXMkbikYy94ag22,
																				},
																			},
																			{
																				href: {
																					pathVariables: {
																						zjAVjXMkb: zjAVjXMkbikYy94ag22,
																					},
																					webPageId: "Mb9PNznan",
																				},
																				implicitPathVariables: {
																					zjAVjXMkb: zjAVjXMkbikYy94ag22,
																				},
																			},
																			{
																				href: wbGwryVFDikYy94ag22,
																				implicitPathVariables: {
																					zjAVjXMkb: zjAVjXMkbikYy94ag22,
																				},
																			},
																			{
																				href: {
																					pathVariables: {
																						zjAVjXMkb: zjAVjXMkbikYy94ag22,
																					},
																					webPageId: "Mb9PNznan",
																				},
																				implicitPathVariables: {
																					zjAVjXMkb: zjAVjXMkbikYy94ag22,
																				},
																			},
																			{
																				href: wbGwryVFDikYy94ag22,
																				implicitPathVariables: {
																					zjAVjXMkb: zjAVjXMkbikYy94ag22,
																				},
																			},
																			{
																				href: {
																					pathVariables: {
																						zjAVjXMkb: zjAVjXMkbikYy94ag22,
																					},
																					webPageId: "Mb9PNznan",
																				},
																				implicitPathVariables: {
																					zjAVjXMkb: zjAVjXMkbikYy94ag22,
																				},
																			},
																			{
																				href: wbGwryVFDikYy94ag22,
																				implicitPathVariables: {
																					zjAVjXMkb: zjAVjXMkbikYy94ag22,
																				},
																			},
																			{
																				href: {
																					pathVariables: {
																						zjAVjXMkb: zjAVjXMkbikYy94ag22,
																					},
																					webPageId: "Mb9PNznan",
																				},
																				implicitPathVariables: {
																					zjAVjXMkb: zjAVjXMkbikYy94ag22,
																				},
																			},
																			{
																				href: wbGwryVFDikYy94ag22,
																				implicitPathVariables: {
																					zjAVjXMkb: zjAVjXMkbikYy94ag22,
																				},
																			},
																			{
																				href: {
																					pathVariables: {
																						zjAVjXMkb: zjAVjXMkbikYy94ag22,
																					},
																					webPageId: "Mb9PNznan",
																				},
																				implicitPathVariables: {
																					zjAVjXMkb: zjAVjXMkbikYy94ag22,
																				},
																			},
																			{
																				href: wbGwryVFDikYy94ag22,
																				implicitPathVariables: {
																					zjAVjXMkb: zjAVjXMkbikYy94ag22,
																				},
																			},
																			{
																				href: {
																					pathVariables: {
																						zjAVjXMkb: zjAVjXMkbikYy94ag22,
																					},
																					webPageId: "Mb9PNznan",
																				},
																				implicitPathVariables: {
																					zjAVjXMkb: zjAVjXMkbikYy94ag22,
																				},
																			},
																		]}
																	>
																		{(resolvedLinks) => (
																			<ComponentViewportProvider
																				height={180}
																				width={`max((${componentViewport?.width || "100vw"} - 40px) / 3, 50px)`}
																				{...addPropertyOverrides(
																					{
																						gcGEsr6wN: {
																							height: 90,
																						},
																					},
																					baseVariant,
																					gestureVariant,
																				)}
																			>
																				<SmartComponentScopedContainer
																					className={"framer-sthuj1-container"}
																					layoutDependency={layoutDependency}
																					layoutId={"gyX45mUCy-container"}
																					nodeId={"gyX45mUCy"}
																					rendersWithMotion={true}
																					scopeId={"lGkovhK5l"}
																				>
																					{_jsx(stdin_default, {
																						height: "100%",
																						id: "gyX45mUCy",
																						IeZ409Uc3:
																							toResponsiveImage(
																								QPdQ7nnMEikYy94ag22,
																							),
																						layoutId: "gyX45mUCy",
																						oQ3OB6P99: resolvedLinks[1],
																						style: {
																							height: "100%",
																							width: "100%",
																						},
																						UmTpyap_n: resolvedLinks[0],
																						width: "100%",
																						...addPropertyOverrides(
																							{
																								gcGEsr6wN: {
																									oQ3OB6P99: resolvedLinks[9],
																									UmTpyap_n: resolvedLinks[8],
																								},
																								MyiLHxvX_: {
																									oQ3OB6P99: resolvedLinks[13],
																									UmTpyap_n: resolvedLinks[12],
																								},
																								Ob8l5wAYv: {
																									oQ3OB6P99: resolvedLinks[11],
																									UmTpyap_n: resolvedLinks[10],
																								},
																								pCY7IszQ1: {
																									oQ3OB6P99: resolvedLinks[3],
																									UmTpyap_n: resolvedLinks[2],
																								},
																								pKmNOFtHN: {
																									oQ3OB6P99: resolvedLinks[7],
																									UmTpyap_n: resolvedLinks[6],
																								},
																								rCSrTIvRX: {
																									oQ3OB6P99: resolvedLinks[5],
																									UmTpyap_n: resolvedLinks[4],
																								},
																								Y4aMApYN3: {
																									oQ3OB6P99: resolvedLinks[15],
																									UmTpyap_n: resolvedLinks[14],
																								},
																							},
																							baseVariant,
																							gestureVariant,
																						),
																					})}
																				</SmartComponentScopedContainer>
																			</ComponentViewportProvider>
																		)}
																	</ResolveLinks>
																</motion.div>
															</PathVariablesContext.Provider>
														</LayoutGroup>
													);
												},
											)}
										</_Fragment>
									)}
								</QueryData>
							</ChildrenCanSuspend>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-mmbvD.framer-203er5, .framer-mmbvD .framer-203er5 { display: block; }",
	".framer-mmbvD.framer-1ut4d2y { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; max-width: 1280px; overflow: visible; padding: 0px; position: relative; width: 820px; }",
	".framer-mmbvD .framer-1xxd029 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-mmbvD .framer-6ayckh-container, .framer-mmbvD .framer-vfnc5f-container, .framer-mmbvD .framer-1gep1y0-container, .framer-mmbvD .framer-rkqvl-container, .framer-mmbvD .framer-1f9rvhh-container, .framer-mmbvD .framer-th0roi-container, .framer-mmbvD .framer-1q7yicf-container { flex: 1 0 0px; height: auto; position: relative; width: 1px; }",
	".framer-mmbvD .framer-moe8ch { display: grid; flex: none; gap: 20px; grid-auto-rows: minmax(0, 1fr); grid-template-columns: repeat(3, minmax(50px, 1fr)); height: min-content; justify-content: center; padding: 0px; position: relative; width: 100%; }",
	".framer-mmbvD .framer-fu7lns { align-content: center; align-items: center; align-self: start; display: flex; flex: none; flex-direction: row; flex-wrap: wrap; gap: 10px; height: min-content; justify-content: center; justify-self: start; padding: 0px; position: relative; width: 100%; }",
	".framer-mmbvD .framer-sthuj1-container { flex: 1 0 0px; height: 180px; position: relative; width: 1px; }",
	".framer-mmbvD.framer-v-12xeefo.framer-1ut4d2y { width: 320px; }",
	".framer-mmbvD.framer-v-12xeefo .framer-sthuj1-container { height: 90px; }",
	'.framer-mmbvD[data-border="true"]::after, .framer-mmbvD [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerlGkovhK5l = withCSS(Component, css, "framer-mmbvD");
var stdin_default4 = FramerlGkovhK5l;
FramerlGkovhK5l.displayName = "Integrations Listing";
FramerlGkovhK5l.defaultProps = {
	height: 1242,
	width: 820,
};
addPropertyControls(FramerlGkovhK5l, {
	variant: {
		options: [
			"XPS0VWdZC",
			"pCY7IszQ1",
			"rCSrTIvRX",
			"pKmNOFtHN",
			"gcGEsr6wN",
			"Ob8l5wAYv",
			"MyiLHxvX_",
			"Y4aMApYN3",
		],
		optionTitles: [
			"Variant 1",
			"Variant 2",
			"Variant 3",
			"Variant 4",
			"Mobile",
			"Variant 6",
			"Variant 7",
			"Variant 8",
		],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerlGkovhK5l,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...LibraryToggleLinkFonts,
		...LibraryCardFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:integrations-listing
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "XPS0VWdZC",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7e5af5d66397a8a15ce8ab3401cf6b1aee707f00a906595a26b5cba8a8c88d97"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default4, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders IntegrationsListingFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7e5af5d66397a8a15ce8ab3401cf6b1aee707f00a906595a26b5cba8a8c88d97"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default4}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default4);
var integrations_listing_default = ComponentWithRoot;
export { integrations_listing_default as default };
