// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 7e5af5d66397a8a1 "Velt", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * gitHubRepoURL?: string // GitHub Repo URL
}} Props

 */
import { routes } from "./chunks/chunk-K34BXH3K.js";
import "./chunks/chunk-WSFCRVEQ.js";

// virtual:miri-code
import { Fragment } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/bsHsaZ6OMvPpUQo9G9ST/SnsgErpJ3PR0HnJuS38g/Miri_code.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useEffect, useState } from "react";
import { addPropertyControls, ControlType } from "unframer";
async function fetchRepoContents(owner, repo, path = "") {
	const apiUrl = `https://api.github.com/repos/${owner}/${repo}/contents/${path}`;
	const response = await fetch(apiUrl);
	return await response.json();
}
function createFolderStructure(items) {
	const itemsArray = Array.isArray(items) ? items : [items];
	return (
		<ul>
			{itemsArray.map((item) => (
				<li>
					<span className={item.type === "dir" ? "folder" : "file"}>
						<i className={item.type === "dir" ? "folder-icon" : "file-icon"} />
						{item.name}
					</span>
					{item.type === "dir" && (
						<div
							style={{
								display: "none",
							}}
						/>
					)}
				</li>
			))}
		</ul>
	);
}
function Miri_code(props) {
	const { repoUrl } = props;
	const [repoContents, setRepoContents] = useState(null);
	useEffect(() => {
		async function loadRepoContents() {
			const [, , , owner, repo] = repoUrl.split("/");
			const contents = await fetchRepoContents(owner, repo);
			setRepoContents(contents);
		}
		loadRepoContents();
	}, [repoUrl]);
	return (
		<div className={"github-repo-viewer"}>
			<div id={"repoStructure"}>
				{repoContents && createFolderStructure(repoContents)}
			</div>
			<style>{`
        .github-repo-viewer {
          font-family: 'SF Pro', Helvetica, 'Inter', -apple-system, Tahoma, Geneva, Verdana, sans-serif;
          background-color: #1A2A7C;
          color: #d4d4d4;
          height: 100%;
          overflow: auto;
        }

        #repoStructure {
          padding: 8px;
          font-size: 13px;
        }

        ul {
          list-style-type: none;
          padding-left: 20px;
        }

        li {
          margin: 2px 0;
        }

        .folder, .file {
          display: flex;
          align-items: center;
          padding: 8px 10px;
          border-radius: 0.5rem;
          gap: 4px;
          cursor: pointer;
          color: rgba(255, 255, 255, 0.5);
          transition: all 300ms ease-in-out;
        }

        .folder:hover, .file:hover {
          background-color: rgba(255, 255, 255, 0.04);
        }

        .folder-icon, .file-icon {
          display: inline-block;
          width: 16px;
          height: 16px;
          margin-right: 5px;
          background-size: contain;
          background-repeat: no-repeat;
        }

        .folder-icon {
          background-image: url('data:image/svg+xml;base64,PHN2ZyB2aWV3Qm94PSIwIDAgMjQgMjQiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHBhdGggZD0iTTEwIDRINGMtMS4xMSAwLTIgLjg5LTIgMnYxMmEyIDIgMCAwIDAgMiAyaDE2YTIgMiAwIDAgMCAyLTJWOGMwLTEuMTEtLjktMi0yLTJoLThsLTItMnoiIGZpbGw9IiM0NTQwM2QiIC8+PC9zdmc+');
        }

        .file-icon {
          background-image: url('data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiI+PHRpdGxlPmZpbGVfdHlwZV90ZXh0PC90aXRsZT48cGF0aCBkPSJNMjAuNzUsMjhIMy4yNUEyLjI1MiwyLjI1MiwwLDAsMSwxLDI1Ljc1VjYuMjVBMi4yNTIsMi4yNTIsMCwwLDEsMy4yNSw0aDEzLjVMOTMsOC4yNXYxNy41QTIuMjUyLDIuMjUyLDAsMCwxLDIwLjc1LDI4WiIgc3R5bGU9ImZpbGw6IzQ1NDAzZCIvPjxwYXRoIGQ9Ik0xNi43NSw0djQuMjVIMjFaIiBzdHlsZT0iZmlsbDojZjFmMWYxIi8+PHBhdGggZD0iTTYsMTJoMTJ2MUg2Wm0wLDRoMTJ2MUg2Wm0wLDRoMTJ2MUg2WiIgc3R5bGU9ImZpbGw6I2YxZjFmMSIvPjwvc3ZnPg==');
        }
      `}</style>
		</div>
	);
}
addPropertyControls(Miri_code, {
	repoUrl: {
		type: ControlType.String,
		title: "GitHub Repo URL",
		defaultValue: "",
	},
});

// virtual:miri-code
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7e5af5d66397a8a15ce8ab3401cf6b1aee707f00a906595a26b5cba8a8c88d97"
			}
			locale={locale}
			locales={locales}
		>
			<Miri_code {...rest} />
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders MiriCodeFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7e5af5d66397a8a15ce8ab3401cf6b1aee707f00a906595a26b5cba8a8c88d97"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={Miri_code}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, Miri_code);
var miri_code_default = ComponentWithRoot;
export { miri_code_default as default };
