// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 7e5af5d66397a8a1 "Velt", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant 1' | 'Mobile' // Variant
 * title?: string // Title
}} Props

 */
import { routes } from "./chunks/chunk-K34BXH3K.js";
import "./chunks/chunk-WSFCRVEQ.js";

// virtual:user
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/1APsj3i7ex6dSimvpUyT/7zCVFnwt8cbEOofusP5i/JNDB0IU1J.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	RichText,
	SVG,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["o61mtHpxk", "E14JKJfdp"];
var serializationHash = "framer-oObiB";
var variantClassNames = {
	E14JKJfdp: "framer-v-1y411lz",
	o61mtHpxk: "framer-v-o0rdgr",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0.7,
	duration: 1,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Variant 1": "o61mtHpxk",
	Mobile: "E14JKJfdp",
};
var getProps = ({ height, id, title, width, ...props }) => {
	return {
		...props,
		ru5clSYY1: title ?? props.ru5clSYY1 ?? "User",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "o61mtHpxk",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ru5clSYY1, ...restProps } =
		getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "o61mtHpxk",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "E14JKJfdp") return false;
		return true;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-o0rdgr",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"o61mtHpxk"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								E14JKJfdp: {
									"data-framer-name": "Mobile",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-mkftwy"}
							layoutDependency={layoutDependency}
							layoutId={"X0r8aBi8Z"}
						>
							<SVG
								className={"framer-uf8p9u"}
								data-framer-name={"pointer"}
								layout={"position"}
								layoutDependency={layoutDependency}
								layoutId={"lsqUwofh0"}
								opacity={1}
								svg={
									'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 27 30"><g transform="translate(0.837 1.792)"><path d="M 4.866 22.858 L 0.911 2.973 C 0.619 1.501 2.193 0.368 3.496 1.112 L 20.95 11.086 C 22.31 11.863 22.043 13.899 20.529 14.298 L 13.086 16.261 C 12.654 16.375 12.281 16.65 12.045 17.03 L 8.069 23.439 C 7.232 24.788 5.175 24.415 4.866 22.858 Z" fill="rgb(55,114,255)"></path><path d="M 0.053 3.144 L 4.008 23.028 C 4.472 25.364 7.557 25.924 8.813 23.9 L 12.789 17.492 C 12.907 17.302 13.093 17.164 13.309 17.107 L 20.752 15.144 C 23.023 14.545 23.424 11.492 21.385 10.327 L 3.93 0.353 C 1.976 -0.764 -0.386 0.936 0.053 3.144 Z" fill="transparent" stroke-width="1.75" stroke="rgb(255,255,255)" stroke-linecap="square" stroke-miterlimit="10" stroke-dasharray=""></path></g></svg>'
								}
								svgContentId={9617993442}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										E14JKJfdp: {
											svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 18 20"><g transform="translate(0.837 1.792)"><path d="M 2.965 14.641 L 0.329 1.385 C 0.133 0.403 1.183 -0.352 2.052 0.144 L 13.688 6.793 C 14.594 7.311 14.416 8.668 13.407 8.934 L 8.445 10.243 C 8.157 10.319 7.908 10.503 7.751 10.756 L 5.1 15.028 C 4.542 15.928 3.171 15.679 2.965 14.641 Z" fill="rgb(55,114,255)"></path><path d="M -0.244 1.498 L 2.393 14.755 C 2.702 16.312 4.759 16.685 5.596 15.336 L 8.247 11.064 C 8.325 10.937 8.45 10.845 8.594 10.807 L 13.555 9.499 C 15.07 9.099 15.337 7.064 13.977 6.287 L 2.341 -0.362 C 1.038 -1.107 -0.536 0.027 -0.244 1.498 Z" fill="transparent" stroke-width="1.17" stroke="rgb(255,255,255)" stroke-linecap="square" stroke-miterlimit="10"></path></g></svg>',
											svgContentId: 11099994215,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
						</motion.div>
						{isDisplayed() && (
							<motion.div
								className={"framer-1xazxh6"}
								data-framer-name={"Frame 64"}
								layoutDependency={layoutDependency}
								layoutId={"BnKZZKRsR"}
								style={{
									backgroundColor: "rgb(55, 114, 255)",
									borderBottomLeftRadius: 29,
									borderBottomRightRadius: 29,
									borderTopLeftRadius: 29,
									borderTopRightRadius: 29,
								}}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-7t2u4g"}
									data-framer-name={"User"}
									fonts={["GF;Urbanist-600"]}
									layoutDependency={layoutDependency}
									layoutId={"esZ6K8yb_"}
									text={ru5clSYY1}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											style={{
												"--font-selector": "R0Y7VXJiYW5pc3QtNjAw",
												"--framer-font-family":
													'"Urbanist", "Urbanist Placeholder", sans-serif',
												"--framer-font-weight": "600",
												"--framer-text-alignment": "center",
											}}
										>
											{"User"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
						)}
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-oObiB.framer-un4ifs, .framer-oObiB .framer-un4ifs { display: block; }",
	".framer-oObiB.framer-o0rdgr { height: 56px; overflow: visible; position: relative; width: 72px; }",
	".framer-oObiB .framer-mkftwy { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 30px; justify-content: center; left: -1px; overflow: visible; padding: 0px; position: absolute; top: -1px; width: 27px; }",
	".framer-oObiB .framer-uf8p9u { flex: none; height: 30px; position: relative; width: 27px; }",
	".framer-oObiB .framer-1xazxh6 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; left: 21px; overflow: hidden; padding: 4px 9px 5px 9px; position: absolute; top: 28px; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-oObiB .framer-7t2u4g { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-oObiB.framer-v-1y411lz.framer-o0rdgr { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; padding: 0px; width: min-content; }",
	".framer-oObiB.framer-v-1y411lz .framer-mkftwy { height: min-content; left: unset; position: relative; top: unset; width: min-content; }",
	".framer-oObiB.framer-v-1y411lz .framer-uf8p9u { height: 20px; width: 18px; }",
];
var FramerJNDB0IU1J = withCSS(Component, css, "framer-oObiB");
var stdin_default = FramerJNDB0IU1J;
FramerJNDB0IU1J.displayName = "User";
FramerJNDB0IU1J.defaultProps = {
	height: 56,
	width: 72,
};
addPropertyControls(FramerJNDB0IU1J, {
	variant: {
		options: ["o61mtHpxk", "E14JKJfdp"],
		optionTitles: ["Variant 1", "Mobile"],
		title: "Variant",
		type: ControlType.Enum,
	},
	ru5clSYY1: {
		defaultValue: "User",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
});
addFonts(
	FramerJNDB0IU1J,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Urbanist",
					source: "google",
					style: "normal",
					url: "https://fonts.gstatic.com/s/urbanist/v18/L0xjDF02iFML4hGCyOCpRdycFsGxSrqDFRkfE5OrS8SlKw.woff2",
					weight: "600",
				},
			],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:user
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "E14JKJfdp",
	"2xl": "o61mtHpxk",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7e5af5d66397a8a15ce8ab3401cf6b1aee707f00a906595a26b5cba8a8c88d97"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders UserFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7e5af5d66397a8a15ce8ab3401cf6b1aee707f00a906595a26b5cba8a8c88d97"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var user_default = ComponentWithRoot;
export { user_default as default };
