// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 7e5af5d66397a8a1 "Velt", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant 1' | 'Mobile' // Variant
}} Props

 */
import { stdin_default } from "../chunks/chunk-KR3M4VYF.js";
import { routes } from "../chunks/chunk-K34BXH3K.js";
import "../chunks/chunk-WSFCRVEQ.js";

// virtual:2025/get-started-steps
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/kt1ec9GAEsE8OT0ytwC2/UIvJwKtJ3ra7Ay9BbwHY/YTXCkfC2C.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	SmartComponentScopedContainer,
	SVG,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var TestimonialFonts = getFonts(stdin_default);
var cycleOrder = ["unk9GXHYp", "qAZ1cdPNM"];
var serializationHash = "framer-jR7Cu";
var variantClassNames = {
	qAZ1cdPNM: "framer-v-1im1pi9",
	unk9GXHYp: "framer-v-sgewes",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Variant 1": "unk9GXHYp",
	Mobile: "qAZ1cdPNM",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "unk9GXHYp",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "unk9GXHYp",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-sgewes",
							className,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"unk9GXHYp"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "2px",
							"--border-color": "rgb(26, 26, 26)",
							"--border-left-width": "2px",
							"--border-right-width": "2px",
							"--border-style": "solid",
							"--border-top-width": "2px",
							backgroundColor: "rgb(17, 17, 17)",
							borderBottomLeftRadius: 24,
							borderBottomRightRadius: 24,
							borderTopLeftRadius: 24,
							borderTopRightRadius: 24,
							...style,
						}}
						{...addPropertyOverrides(
							{
								qAZ1cdPNM: {
									"data-framer-name": "Mobile",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-13f3g02"}
							data-framer-name={"Frame 1707482246"}
							layoutDependency={layoutDependency}
							layoutId={"E526zmL_O"}
							style={{
								backgroundColor: "rgb(17, 17, 17)",
								borderBottomLeftRadius: 24,
								borderBottomRightRadius: 24,
								borderTopLeftRadius: 24,
								borderTopRightRadius: 24,
							}}
						>
							<motion.div
								className={"framer-11hv13i"}
								data-framer-name={"Frame 1707482238"}
								layoutDependency={layoutDependency}
								layoutId={"WTqoHgFhs"}
								style={{
									backgroundColor: "rgb(13, 13, 13)",
								}}
							>
								<motion.div
									className={"framer-10n0qb0"}
									data-framer-name={"Frame 1707482256"}
									layoutDependency={layoutDependency}
									layoutId={"FMF73oRxr"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1ltbucp"}
										data-framer-name={"1. Initialize Velt"}
										fonts={["GF;Urbanist-700"]}
										layoutDependency={layoutDependency}
										layoutId={"S9YkNcvnE"}
										style={{
											"--extracted-r6o4lv": "rgb(255, 255, 255)",
											"--framer-paragraph-spacing": "0px",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector": "R0Y7VXJiYW5pc3QtNzAw",
													"--framer-font-family":
														'"Urbanist", "Urbanist Placeholder", sans-serif',
													"--framer-font-size": "20px",
													"--framer-font-weight": "700",
													"--framer-line-height": "120%",
													"--framer-text-color":
														"var(--extracted-r6o4lv, rgb(255, 255, 255))",
												}}
											>
												{"1. Initialize Velt"}
											</motion.p>
										</React.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-13re0tl"}
										data-framer-name={"Setting up velt takes 2 minutes"}
										fonts={["GF;Urbanist-regular"]}
										layoutDependency={layoutDependency}
										layoutId={"nZCUdrHZs"}
										style={{
											"--extracted-r6o4lv": "rgb(255, 255, 255)",
											"--framer-paragraph-spacing": "0px",
											opacity: 0.52,
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector": "R0Y7VXJiYW5pc3QtcmVndWxhcg==",
													"--framer-font-family":
														'"Urbanist", "Urbanist Placeholder", sans-serif',
													"--framer-font-size": "14px",
													"--framer-line-height": "100%",
													"--framer-text-color":
														"var(--extracted-r6o4lv, rgb(255, 255, 255))",
												}}
											>
												{"Install Velt and setup API key"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
								<motion.div
									className={"framer-1ogmjhu"}
									data-framer-name={"Frame 1707482240"}
									layoutDependency={layoutDependency}
									layoutId={"XjbCTb_rm"}
									style={{
										background:
											"linear-gradient(180deg, rgb(30, 30, 30) 0%, rgba(20, 20, 20, 0) 100%)",
										borderTopLeftRadius: 24,
									}}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1lcjo4f"}
										data-framer-name={"app > npm i @veltdev/client"}
										fonts={["GF;Fira Code-500"]}
										layoutDependency={layoutDependency}
										layoutId={"I_0xkJW1B"}
										style={{
											"--extracted-1w3ko1f": "rgba(255, 255, 255, 0.32)",
											"--extracted-3sq8v0": "rgb(255, 255, 255)",
											"--extracted-r6o4lv": "rgb(179, 135, 247)",
											"--framer-paragraph-spacing": "0px",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector": "R0Y7RmlyYSBDb2RlLTUwMA==",
													"--framer-font-family": '"Fira Code", monospace',
													"--framer-font-size": "20px",
													"--framer-font-weight": "500",
													"--framer-letter-spacing": "-0.02em",
													"--framer-line-height": "120%",
													"--framer-text-color":
														"var(--extracted-r6o4lv, rgb(179, 135, 247))",
												}}
											>
												<motion.span
													style={{
														"--framer-text-color":
															"var(--extracted-1w3ko1f, rgba(255, 255, 255, 0.32))",
													}}
												>
													{"app >"}
												</motion.span>
												<motion.span
													style={{
														"--framer-text-color":
															"var(--extracted-3sq8v0, rgb(255, 255, 255))",
													}}
												>
													{" npm i "}
												</motion.span>
												{"@veltdev/client"}
											</motion.p>
										</React.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-142c9hc"}
										data-framer-name={"app > Enter your API Key:"}
										fonts={["GF;Fira Code-500"]}
										layoutDependency={layoutDependency}
										layoutId={"dECsMQ2Jl"}
										style={{
											"--extracted-1w3ko1f": "rgba(255, 255, 255, 0.32)",
											"--extracted-r6o4lv": "rgb(255, 255, 255)",
											"--framer-paragraph-spacing": "0px",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector": "R0Y7RmlyYSBDb2RlLTUwMA==",
													"--framer-font-family": '"Fira Code", monospace',
													"--framer-font-size": "20px",
													"--framer-font-weight": "500",
													"--framer-letter-spacing": "-0.02em",
													"--framer-line-height": "120%",
													"--framer-text-color":
														"var(--extracted-r6o4lv, rgb(255, 255, 255))",
												}}
											>
												<motion.span
													style={{
														"--framer-text-color":
															"var(--extracted-1w3ko1f, rgba(255, 255, 255, 0.32))",
													}}
												>
													{"app > "}
												</motion.span>
												{"Enter your API Key:"}
											</motion.p>
										</React.Fragment>
									</RichText>
									<motion.div
										className={"framer-wx1lu"}
										data-framer-name={"Frame 1707480222"}
										layoutDependency={layoutDependency}
										layoutId={"CIcKdx0kF"}
									>
										<motion.div
											className={"framer-1lcxrlr"}
											data-framer-name={"Rectangle 34630164"}
											layoutDependency={layoutDependency}
											layoutId={"odTvMgQ4k"}
											style={{
												backgroundColor: "rgb(255, 78, 84)",
												borderBottomLeftRadius: 32,
												borderBottomRightRadius: 32,
												borderTopLeftRadius: 32,
												borderTopRightRadius: 32,
											}}
										/>
										<motion.div
											className={"framer-12eur9l"}
											data-framer-name={"Rectangle 34630165"}
											layoutDependency={layoutDependency}
											layoutId={"AhmQqQTQh"}
											style={{
												backgroundColor: "rgb(231, 188, 0)",
												borderBottomLeftRadius: 32,
												borderBottomRightRadius: 32,
												borderTopLeftRadius: 32,
												borderTopRightRadius: 32,
											}}
										/>
										<motion.div
											className={"framer-my2nx4"}
											data-framer-name={"Rectangle 34630166"}
											layoutDependency={layoutDependency}
											layoutId={"STMff852A"}
											style={{
												backgroundColor: "rgb(0, 197, 0)",
												borderBottomLeftRadius: 32,
												borderBottomRightRadius: 32,
												borderTopLeftRadius: 32,
												borderTopRightRadius: 32,
											}}
										/>
									</motion.div>
								</motion.div>
								<motion.div
									className={"framer-110b6da"}
									data-framer-name={"Rectangle 34630172"}
									layoutDependency={layoutDependency}
									layoutId={"gQVr8WvZZ"}
									style={{
										background:
											"linear-gradient(270deg, rgb(13, 13, 13) 0%, rgba(13, 13, 13, 0) 100%)",
										opacity: 0.8,
									}}
								/>
							</motion.div>
							<motion.div
								className={"framer-1uge1v2"}
								data-framer-name={"Frame 1707482233"}
								layoutDependency={layoutDependency}
								layoutId={"CuEvWOrNJ"}
								style={{
									backgroundColor: "rgb(13, 13, 13)",
								}}
							>
								<motion.div
									className={"framer-19ojnw"}
									data-framer-name={"Frame 1707482255"}
									layoutDependency={layoutDependency}
									layoutId={"wJzmbegXI"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1pdewwk"}
										data-framer-name={"2. Add Component"}
										fonts={["GF;Urbanist-700"]}
										layoutDependency={layoutDependency}
										layoutId={"uZy7XjEJ4"}
										style={{
											"--extracted-r6o4lv": "rgb(255, 255, 255)",
											"--framer-paragraph-spacing": "0px",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector": "R0Y7VXJiYW5pc3QtNzAw",
													"--framer-font-family":
														'"Urbanist", "Urbanist Placeholder", sans-serif',
													"--framer-font-size": "20px",
													"--framer-font-weight": "700",
													"--framer-line-height": "120%",
													"--framer-text-color":
														"var(--extracted-r6o4lv, rgb(255, 255, 255))",
												}}
											>
												{"2. Add Components"}
											</motion.p>
										</React.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-zbeohw"}
										data-framer-name={"Copy paste from 15+ components"}
										fonts={["GF;Urbanist-regular"]}
										layoutDependency={layoutDependency}
										layoutId={"dIG_6JC0x"}
										style={{
											"--extracted-r6o4lv": "rgb(255, 255, 255)",
											"--framer-paragraph-spacing": "0px",
											opacity: 0.52,
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector": "R0Y7VXJiYW5pc3QtcmVndWxhcg==",
													"--framer-font-family":
														'"Urbanist", "Urbanist Placeholder", sans-serif',
													"--framer-font-size": "14px",
													"--framer-line-height": "100%",
													"--framer-text-color":
														"var(--extracted-r6o4lv, rgb(255, 255, 255))",
												}}
											>
												{"Choose from over 15 feature components"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
								<motion.div
									className={"framer-13bkw8f"}
									data-framer-name={"Group 1707480240"}
									layoutDependency={layoutDependency}
									layoutId={"m6nsdvEjM"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1qc1om7"}
										data-framer-name={"<VeltComments>"}
										fonts={["GF;Fira Code-regular"]}
										layoutDependency={layoutDependency}
										layoutId={"qQ2SRVhct"}
										style={{
											"--extracted-1w3ko1f": "rgba(255, 255, 255, 0.52)",
											"--extracted-3sq8v0": "rgba(255, 255, 255, 0.52)",
											"--extracted-r6o4lv": "rgb(103, 248, 200)",
											"--framer-paragraph-spacing": "0px",
										}}
										verticalAlignment={"center"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector": "R0Y7RmlyYSBDb2RlLXJlZ3VsYXI=",
													"--framer-font-family": '"Fira Code", monospace',
													"--framer-font-size": "14px",
													"--framer-letter-spacing": "0.01em",
													"--framer-line-height": "20.4px",
													"--framer-text-color":
														"var(--extracted-r6o4lv, rgb(103, 248, 200))",
												}}
											>
												<motion.span
													style={{
														"--framer-text-color":
															"var(--extracted-1w3ko1f, rgba(255, 255, 255, 0.52))",
													}}
												>
													{"<"}
												</motion.span>
												{"VeltComments"}
												<motion.span
													style={{
														"--framer-text-color":
															"var(--extracted-3sq8v0, rgba(255, 255, 255, 0.52))",
													}}
												>
													{">"}
												</motion.span>
											</motion.p>
										</React.Fragment>
									</RichText>
									<motion.div
										className={"framer-o5zqkc"}
										data-border={true}
										data-framer-name={"Comments"}
										layoutDependency={layoutDependency}
										layoutId={"uvwTVKgN8"}
										style={{
											"--border-bottom-width": "1.2000000476837158px",
											"--border-color": "rgba(229, 232, 235, 0.08)",
											"--border-left-width": "1.2000000476837158px",
											"--border-right-width": "1.2000000476837158px",
											"--border-style": "solid",
											"--border-top-width": "1.2000000476837158px",
											backgroundColor: "rgb(27, 27, 27)",
											borderBottomLeftRadius: 14.4,
											borderBottomRightRadius: 14.4,
											borderTopLeftRadius: 14.4,
											borderTopRightRadius: 14.4,
											boxShadow:
												"0px 9.600000381469727px 19.200000762939453px 0px rgba(14, 14, 14, 0.1)",
										}}
									>
										<motion.div
											className={"framer-1pzl8hw"}
											data-framer-name={"Comment"}
											layoutDependency={layoutDependency}
											layoutId={"OfQ3qmG8x"}
										>
											<motion.div
												className={"framer-z19gts"}
												data-framer-name={"line"}
												layoutDependency={layoutDependency}
												layoutId={"c9XQSvNPw"}
												style={{
													backgroundColor: "rgb(229, 232, 235)",
													opacity: 0,
												}}
											/>
											<motion.div
												className={"framer-x1ggn7"}
												data-framer-name={"Content"}
												layoutDependency={layoutDependency}
												layoutId={"P6zj2ZKak"}
											>
												<motion.div
													className={"framer-fyr3pg"}
													data-framer-name={"content"}
													layoutDependency={layoutDependency}
													layoutId={"PHA49mxxf"}
												>
													<motion.div
														className={"framer-4ztmbq"}
														data-framer-name={"Frame 6191"}
														layoutDependency={layoutDependency}
														layoutId={"jm_l_tUvd"}
													>
														<Image
															background={{
																alt: "User Profile Wireframe",
																fit: "fit",
																loading: getLoadingLazyAtYPosition(
																	(componentViewport?.y || 0) +
																		0 +
																		0 +
																		2 +
																		175 +
																		41 +
																		0 +
																		0 +
																		0 +
																		20.4 +
																		0 +
																		0 +
																		0 +
																		0 +
																		0,
																),
																pixelHeight: 154,
																pixelWidth: 1580,
																positionX: "center",
																positionY: "center",
																sizes: "395px",
																src: "https://framerusercontent.com/images/pBjlgRDXamNA8oDLb9AvJCov9w.png?width=1580&height=154",
																srcSet:
																	"https://framerusercontent.com/images/pBjlgRDXamNA8oDLb9AvJCov9w.png?scale-down-to=512&width=1580&height=154 512w,https://framerusercontent.com/images/pBjlgRDXamNA8oDLb9AvJCov9w.png?scale-down-to=1024&width=1580&height=154 1024w,https://framerusercontent.com/images/pBjlgRDXamNA8oDLb9AvJCov9w.png?width=1580&height=154 1580w",
															}}
															className={"framer-1p38j7c"}
															data-framer-name={"Avatar & info"}
															layoutDependency={layoutDependency}
															layoutId={"oc3FEGmod"}
															{...addPropertyOverrides(
																{
																	qAZ1cdPNM: {
																		background: {
																			alt: "User Profile Wireframe",
																			fit: "fit",
																			loading: getLoadingLazyAtYPosition(
																				(componentViewport?.y || 0) +
																					0 +
																					0 +
																					2 +
																					449 +
																					175 +
																					41 +
																					0 +
																					0 +
																					0 +
																					20.4 +
																					0 +
																					0 +
																					0 +
																					0 +
																					0,
																			),
																			pixelHeight: 154,
																			pixelWidth: 1580,
																			positionX: "center",
																			positionY: "center",
																			sizes: "395px",
																			src: "https://framerusercontent.com/images/pBjlgRDXamNA8oDLb9AvJCov9w.png?width=1580&height=154",
																			srcSet:
																				"https://framerusercontent.com/images/pBjlgRDXamNA8oDLb9AvJCov9w.png?scale-down-to=512&width=1580&height=154 512w,https://framerusercontent.com/images/pBjlgRDXamNA8oDLb9AvJCov9w.png?scale-down-to=1024&width=1580&height=154 1024w,https://framerusercontent.com/images/pBjlgRDXamNA8oDLb9AvJCov9w.png?width=1580&height=154 1580w",
																		},
																	},
																},
																baseVariant,
																gestureVariant,
															)}
														/>
														<SVG
															className={"framer-14nrtv5"}
															data-framer-name={"Frame 6191"}
															fill={"rgba(0,0,0,1)"}
															intrinsicHeight={27}
															intrinsicWidth={395}
															layoutDependency={layoutDependency}
															layoutId={"tneBQvhGn"}
															svg={
																'<svg width="395" height="27" viewBox="0 0 395 27" fill="none" xmlns="http://www.w3.org/2000/svg">\n<rect x="48.1992" y="3.19971" width="167" height="21" rx="10.5" fill="white" fill-opacity="0.04"/>\n</svg>\n'
															}
															withExternalLayout={true}
														/>
													</motion.div>
												</motion.div>
											</motion.div>
										</motion.div>
									</motion.div>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-15mlk5f"}
										data-framer-name={"</VeltComments>"}
										fonts={["GF;Fira Code-regular"]}
										layoutDependency={layoutDependency}
										layoutId={"lxAZ0v5xE"}
										style={{
											"--extracted-1w3ko1f": "rgba(255, 255, 255, 0.52)",
											"--extracted-3sq8v0": "rgba(255, 255, 255, 0.52)",
											"--extracted-r6o4lv": "rgb(103, 248, 200)",
											"--framer-paragraph-spacing": "0px",
										}}
										verticalAlignment={"center"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector": "R0Y7RmlyYSBDb2RlLXJlZ3VsYXI=",
													"--framer-font-family": '"Fira Code", monospace',
													"--framer-font-size": "14px",
													"--framer-letter-spacing": "0.01em",
													"--framer-line-height": "20.4px",
													"--framer-text-color":
														"var(--extracted-r6o4lv, rgb(103, 248, 200))",
												}}
											>
												<motion.span
													style={{
														"--framer-text-color":
															"var(--extracted-1w3ko1f, rgba(255, 255, 255, 0.52))",
													}}
												>
													{"</"}
												</motion.span>
												{"VeltComments"}
												<motion.span
													style={{
														"--framer-text-color":
															"var(--extracted-3sq8v0, rgba(255, 255, 255, 0.52))",
													}}
												>
													{">"}
												</motion.span>
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
								<motion.div
									className={"framer-13xru2b"}
									data-framer-name={"Rectangle 34630172"}
									layoutDependency={layoutDependency}
									layoutId={"FqwGCys3o"}
									style={{
										background:
											"linear-gradient(270deg, rgb(13, 13, 13) 0%, rgba(13, 13, 13, 0) 100%)",
										opacity: 0.8,
									}}
								/>
							</motion.div>
							<motion.div
								className={"framer-1d3eo9t"}
								data-framer-name={"Frame 1707482234"}
								layoutDependency={layoutDependency}
								layoutId={"JoP39TfDj"}
								style={{
									backgroundColor: "rgb(13, 13, 13)",
								}}
							>
								<motion.div
									className={"framer-1w58zkw"}
									data-framer-name={"Frame 1707482257"}
									layoutDependency={layoutDependency}
									layoutId={"dvpAhaO1r"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1g0i0kj"}
										data-framer-name={"3. Style Your Components"}
										fonts={["GF;Urbanist-700"]}
										layoutDependency={layoutDependency}
										layoutId={"iYGbJ61LU"}
										style={{
											"--extracted-r6o4lv": "rgb(255, 255, 255)",
											"--framer-paragraph-spacing": "0px",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector": "R0Y7VXJiYW5pc3QtNzAw",
													"--framer-font-family":
														'"Urbanist", "Urbanist Placeholder", sans-serif',
													"--framer-font-size": "20px",
													"--framer-font-weight": "700",
													"--framer-line-height": "120%",
													"--framer-text-color":
														"var(--extracted-r6o4lv, rgb(255, 255, 255))",
												}}
											>
												{"3. Style Your Experience"}
											</motion.p>
										</React.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-dwx5q7"}
										data-framer-name={"Match your UI language with CSS"}
										fonts={["GF;Urbanist-regular"]}
										layoutDependency={layoutDependency}
										layoutId={"jNL1Zjjox"}
										style={{
											"--extracted-r6o4lv": "rgb(255, 255, 255)",
											"--framer-paragraph-spacing": "0px",
											opacity: 0.52,
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector": "R0Y7VXJiYW5pc3QtcmVndWxhcg==",
													"--framer-font-family":
														'"Urbanist", "Urbanist Placeholder", sans-serif',
													"--framer-font-size": "14px",
													"--framer-line-height": "100%",
													"--framer-text-color":
														"var(--extracted-r6o4lv, rgb(255, 255, 255))",
												}}
											>
												{"Adjust their look and feel"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
								<motion.div
									className={"framer-14cdzar"}
									data-framer-name={"Group 1707479644"}
									layoutDependency={layoutDependency}
									layoutId={"cOEMC87Ap"}
								>
									<motion.div
										className={"framer-6i3bpt"}
										data-border={true}
										data-framer-name={"Comments"}
										layoutDependency={layoutDependency}
										layoutId={"h4HGYfDLP"}
										style={{
											"--border-bottom-width": "1.2959998846054077px",
											"--border-color": "rgba(225, 225, 225, 0.06)",
											"--border-left-width": "1.2959998846054077px",
											"--border-right-width": "1.2959998846054077px",
											"--border-style": "solid",
											"--border-top-width": "1.2959998846054077px",
											backgroundColor: "rgb(21, 21, 21)",
											borderBottomLeftRadius: 11.2,
											borderBottomRightRadius: 11.2,
											borderTopLeftRadius: 11.2,
											borderTopRightRadius: 11.2,
										}}
									>
										<motion.div
											className={"framer-1uasr2m"}
											data-framer-name={"Group 1707479394"}
											layoutDependency={layoutDependency}
											layoutId={"V0f6IIUX1"}
										>
											<motion.div
												className={"framer-bb0lib"}
												data-border={true}
												data-framer-name={"Progress Status"}
												layoutDependency={layoutDependency}
												layoutId={"ZZnY_tJlk"}
												style={{
													"--border-bottom-width": "0.9719999432563782px",
													"--border-color": "rgb(65, 65, 65)",
													"--border-left-width": "0.9719999432563782px",
													"--border-right-width": "0.9719999432563782px",
													"--border-style": "solid",
													"--border-top-width": "0.9719999432563782px",
													borderBottomLeftRadius: 93.34,
													borderBottomRightRadius: 93.34,
													borderTopLeftRadius: 93.34,
													borderTopRightRadius: 93.34,
												}}
											>
												<motion.div
													className={"framer-gzbpz"}
													data-framer-name={"icons/Arrow Down Simple/Line"}
													layoutDependency={layoutDependency}
													layoutId={"lIOEBih69"}
												>
													<SVG
														className={"framer-pd6xid"}
														data-framer-name={"Shape"}
														fill={"rgba(0,0,0,1)"}
														intrinsicHeight={8}
														intrinsicWidth={11}
														layoutDependency={layoutDependency}
														layoutId={"I7518:25969;643:5539"}
														svg={
															'<svg width="11" height="8" viewBox="-1 -1 11 8" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path fill-rule="evenodd" clip-rule="evenodd" d="M8.26958 0.936525C7.90506 0.572007 7.31406 0.572007 6.94954 0.936525L4.34264 3.54343L1.73573 0.936525C1.37121 0.572006 0.780211 0.572006 0.415694 0.936525C0.0511749 1.30104 0.0511749 1.89204 0.415694 2.25656L3.68262 5.52349C4.04714 5.888 4.63814 5.888 5.00266 5.52349L8.26958 2.25656C8.6341 1.89204 8.6341 1.30104 8.26958 0.936525Z" fill="#414141"/>\n</svg>\n'
														}
														withExternalLayout={true}
													/>
												</motion.div>
												<RichText
													__fromCanvasComponent={true}
													className={"framer-ui3292"}
													data-framer-name={"Open"}
													fonts={["GF;Poppins-600"]}
													layoutDependency={layoutDependency}
													layoutId={"QjpUeO2u6"}
													style={{
														"--extracted-r6o4lv": "rgb(65, 65, 65)",
														"--framer-paragraph-spacing": "0px",
													}}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													<React.Fragment>
														<motion.p
															style={{
																"--font-selector": "R0Y7UG9wcGlucy02MDA=",
																"--framer-font-family":
																	'"Poppins", "Poppins Placeholder", sans-serif',
																"--framer-font-size": "11.66px",
																"--framer-font-weight": "600",
																"--framer-letter-spacing": "-0.02em",
																"--framer-line-height": "22.4px",
																"--framer-text-alignment": "center",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, rgb(65, 65, 65))",
															}}
														>
															{"Open"}
														</motion.p>
													</React.Fragment>
												</RichText>
											</motion.div>
											<motion.div
												className={"framer-en1efk"}
												data-border={true}
												data-framer-name={"Assigning comment priority / status"}
												layoutDependency={layoutDependency}
												layoutId={"Rs3NQTlAy"}
												style={{
													"--border-bottom-width": "0.9719999432563782px",
													"--border-color": "rgb(65, 65, 65)",
													"--border-left-width": "0.9719999432563782px",
													"--border-right-width": "0.9719999432563782px",
													"--border-style": "solid",
													"--border-top-width": "0.9719999432563782px",
													borderBottomLeftRadius: 93.34,
													borderBottomRightRadius: 93.34,
													borderTopLeftRadius: 93.34,
													borderTopRightRadius: 93.34,
												}}
											>
												<motion.div
													className={"framer-x4p8qn"}
													data-framer-name={"Frame 47952"}
													layoutDependency={layoutDependency}
													layoutId={"SWilw5q7h"}
												>
													<motion.div
														className={"framer-13trj11"}
														data-framer-name={"icons/Arrow Down Simple/Line"}
														layoutDependency={layoutDependency}
														layoutId={"mLGNqoodl"}
													>
														<SVG
															className={"framer-y376ce"}
															data-framer-name={"Shape"}
															fill={"rgba(0,0,0,1)"}
															intrinsicHeight={8}
															intrinsicWidth={11}
															layoutDependency={layoutDependency}
															layoutId={"I7518:25973;643:5539"}
															svg={
																'<svg width="11" height="8" viewBox="-1 -1 11 8" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path fill-rule="evenodd" clip-rule="evenodd" d="M8.16802 1.0752C7.8035 0.710679 7.2125 0.710679 6.84798 1.0752L4.24107 3.6821L1.63417 1.0752C1.26965 0.710678 0.678649 0.710678 0.314131 1.0752C-0.0503876 1.43971 -0.0503876 2.03071 0.314131 2.39523L3.58106 5.66216C3.94557 6.02668 4.53657 6.02668 4.90109 5.66216L8.16802 2.39523C8.53254 2.03072 8.53254 1.43971 8.16802 1.0752Z" fill="#414141"/>\n</svg>\n'
															}
															withExternalLayout={true}
														/>
													</motion.div>
												</motion.div>
												<RichText
													__fromCanvasComponent={true}
													className={"framer-frksjb"}
													data-framer-name={"P0"}
													fonts={["GF;Poppins-600"]}
													layoutDependency={layoutDependency}
													layoutId={"tSJDvjnE1"}
													style={{
														"--extracted-r6o4lv": "rgb(65, 65, 65)",
														"--framer-paragraph-spacing": "0px",
													}}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													<React.Fragment>
														<motion.p
															style={{
																"--font-selector": "R0Y7UG9wcGlucy02MDA=",
																"--framer-font-family":
																	'"Poppins", "Poppins Placeholder", sans-serif',
																"--framer-font-size": "11.66px",
																"--framer-font-weight": "600",
																"--framer-letter-spacing": "-0.02em",
																"--framer-line-height": "22.4px",
																"--framer-text-alignment": "center",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, rgb(65, 65, 65))",
															}}
														>
															{"P0"}
														</motion.p>
													</React.Fragment>
												</RichText>
											</motion.div>
										</motion.div>
										<motion.div
											className={"framer-1y9ldq9"}
											data-border={true}
											data-framer-name={"Rectangle 34626372"}
											layoutDependency={layoutDependency}
											layoutId={"D2MNdSX9t"}
											style={{
												"--border-bottom-width": "0.9719999432563782px",
												"--border-color": "rgb(75, 75, 75)",
												"--border-left-width": "0.9719999432563782px",
												"--border-right-width": "0.9719999432563782px",
												"--border-style": "solid",
												"--border-top-width": "0.9719999432563782px",
												borderBottomLeftRadius: 20.74,
												borderBottomRightRadius: 20.74,
												borderTopLeftRadius: 20.74,
												borderTopRightRadius: 20.74,
											}}
										/>
										<motion.div
											className={"framer-ukj3ra"}
											data-framer-name={"Frame 1707480492"}
											layoutDependency={layoutDependency}
											layoutId={"ebPTo51dH"}
										>
											<motion.div
												className={"framer-8p61xx"}
												data-framer-name={"Frame 1707479592"}
												layoutDependency={layoutDependency}
												layoutId={"tA1qGhe57"}
											>
												<RichText
													__fromCanvasComponent={true}
													className={"framer-afcvo2"}
													data-framer-name={"Name"}
													fonts={["GF;Poppins-600"]}
													layoutDependency={layoutDependency}
													layoutId={"hd9qUqctN"}
													style={{
														"--framer-paragraph-spacing": "0px",
													}}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													<React.Fragment>
														<motion.p
															style={{
																"--font-selector": "R0Y7UG9wcGlucy02MDA=",
																"--framer-font-family":
																	'"Poppins", "Poppins Placeholder", sans-serif',
																"--framer-font-size": "18.14px",
																"--framer-font-weight": "600",
																"--framer-letter-spacing": "0.08em",
																"--framer-line-height": "22.4px",
																"--framer-text-alignment": "center",
															}}
														>
															{"Me"}
														</motion.p>
													</React.Fragment>
												</RichText>
											</motion.div>
											<motion.div
												className={"framer-16007zv"}
												data-framer-name={"Frame 1707480491"}
												layoutDependency={layoutDependency}
												layoutId={"slM3aTb1x"}
											>
												<motion.div
													className={"framer-1e5fabi"}
													data-framer-name={"Label device"}
													layoutDependency={layoutDependency}
													layoutId={"RTcOK1j__"}
													style={{
														backgroundColor: "rgb(40, 40, 40)",
														borderBottomLeftRadius: 20.74,
														borderBottomRightRadius: 20.74,
														borderTopLeftRadius: 20.74,
														borderTopRightRadius: 20.74,
													}}
												/>
											</motion.div>
										</motion.div>
										<motion.div
											className={"framer-18b8ce5"}
											data-framer-name={"Frame 1707481127"}
											layoutDependency={layoutDependency}
											layoutId={"v9Cbv0mHi"}
											style={{
												backgroundColor: "rgb(40, 40, 40)",
												borderBottomLeftRadius: 7.78,
												borderBottomRightRadius: 7.78,
												borderTopLeftRadius: 7.78,
												borderTopRightRadius: 7.78,
											}}
										/>
										<motion.div
											className={"framer-czmry7"}
											data-framer-name={"Frame 1707481128"}
											layoutDependency={layoutDependency}
											layoutId={"Bhio0vaij"}
											style={{
												backgroundColor: "rgb(249, 249, 249)",
												borderBottomLeftRadius: 20.74,
												borderBottomRightRadius: 20.74,
												borderTopLeftRadius: 20.74,
												borderTopRightRadius: 20.74,
											}}
										/>
										<motion.div
											className={"framer-9abeh8"}
											data-framer-name={"Frame 1707481129"}
											layoutDependency={layoutDependency}
											layoutId={"kWD77WJpu"}
										>
											<motion.div
												className={"framer-1i59z36"}
												data-framer-name={"Ellipse 3188"}
												layoutDependency={layoutDependency}
												layoutId={"rUTwzTsGP"}
												style={{
													backgroundColor: "rgb(255, 255, 255)",
													borderBottomLeftRadius: "100%",
													borderBottomRightRadius: "100%",
													borderTopLeftRadius: "100%",
													borderTopRightRadius: "100%",
												}}
											/>
											<motion.div
												className={"framer-wuf52f"}
												data-framer-name={"Ellipse 3189"}
												layoutDependency={layoutDependency}
												layoutId={"UyRmqcp1P"}
												style={{
													backgroundColor: "rgb(255, 255, 255)",
													borderBottomLeftRadius: "100%",
													borderBottomRightRadius: "100%",
													borderTopLeftRadius: "100%",
													borderTopRightRadius: "100%",
												}}
											/>
											<motion.div
												className={"framer-j7k0os"}
												data-framer-name={"Ellipse 3190"}
												layoutDependency={layoutDependency}
												layoutId={"j2uWh1Di6"}
												style={{
													backgroundColor: "rgb(255, 255, 255)",
													borderBottomLeftRadius: "100%",
													borderBottomRightRadius: "100%",
													borderTopLeftRadius: "100%",
													borderTopRightRadius: "100%",
												}}
											/>
										</motion.div>
									</motion.div>
									<motion.div
										className={"framer-4168a9"}
										data-framer-name={"Group 1707479642"}
										layoutDependency={layoutDependency}
										layoutId={"R7a_oKLBx"}
									>
										<SVG
											className={"framer-17h32vh"}
											data-framer-name={"Anchor"}
											fill={"rgba(0,0,0,1)"}
											intrinsicHeight={94}
											intrinsicWidth={95}
											layoutDependency={layoutDependency}
											layoutId={"agwVeg6Sw"}
											svg={
												'<svg width="95" height="94" viewBox="0 0 95 94" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path d="M94.464 76.7764H29.2009C23.0148 76.7764 18 71.7616 18 65.5755V0.312373" stroke="url(#paint0_radial_7518_25988)" stroke-width="1.296"/>\n<line y1="-0.648" x2="42.1549" y2="-0.648" transform="matrix(0.707107 0.707107 0.707107 -0.707107 5.25781 58.1367)" stroke="#646464" stroke-width="1.296"/>\n<rect x="0.648" y="-0.648" width="5.832" height="5.832" transform="matrix(1 0 0 -1 32.4727 92.4804)" fill="#141414" stroke="#0085FF" stroke-width="1.296"/>\n<rect x="0.324" y="-0.324" width="4.536" height="4.536" rx="2.268" transform="matrix(1 0 0 -1 17.5703 75.6323)" fill="#0085FF" stroke="white" stroke-width="0.648"/>\n<rect x="0.648" y="-0.648" width="5.832" height="5.832" transform="matrix(1 0 0 -1 0.0742188 60.081)" fill="#141414" stroke="#0085FF" stroke-width="1.296"/>\n<defs>\n<radialGradient id="paint0_radial_7518_25988" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="translate(21.564 74.5084) rotate(-47.9508) scale(66.7574)">\n<stop stop-color="#0085FF"/>\n<stop offset="1" stop-color="#1E1E1E"/>\n</radialGradient>\n</defs>\n</svg>\n'
											}
											withExternalLayout={true}
										/>
										<Image
											background={{
												alt: "",
												fit: "stretch",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) +
														0 +
														0 +
														2 +
														178 +
														50.4004 +
														121.5996,
												),
												pixelHeight: 116,
												pixelWidth: 252,
												positionX: "center",
												positionY: "center",
												src: "https://framerusercontent.com/images/E0sEkEFVzNuHDMiNETPAoZuZTUY.png?width=252&height=116",
											}}
											className={"framer-15fvql3"}
											data-border={true}
											data-framer-name={"Frame 1707481124"}
											layoutDependency={layoutDependency}
											layoutId={"JdX5pEmMc"}
											style={{
												"--border-bottom-width": "1.2959998846054077px",
												"--border-color": "rgb(0, 132, 255)",
												"--border-left-width": "1.2959998846054077px",
												"--border-right-width": "1.2959998846054077px",
												"--border-style": "solid",
												"--border-top-width": "1.2959998846054077px",
												borderBottomLeftRadius: 7.78,
												borderBottomRightRadius: 7.78,
												borderTopLeftRadius: 7.78,
												borderTopRightRadius: 7.78,
												boxShadow:
													"0px 2.5919997692108154px 33.69599914550781px 0px rgba(0, 133, 255, 0.12)",
											}}
											{...addPropertyOverrides(
												{
													qAZ1cdPNM: {
														background: {
															alt: "",
															fit: "stretch",
															loading: getLoadingLazyAtYPosition(
																(componentViewport?.y || 0) +
																	0 +
																	0 +
																	2 +
																	898 +
																	178 +
																	50.4004 +
																	121.5996,
															),
															pixelHeight: 116,
															pixelWidth: 252,
															positionX: "center",
															positionY: "center",
															src: "https://framerusercontent.com/images/E0sEkEFVzNuHDMiNETPAoZuZTUY.png?width=252&height=116",
														},
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<SVG
												className={"framer-1jfjxvx"}
												data-framer-name={"Frame 1707481125"}
												fill={"rgba(0,0,0,1)"}
												intrinsicHeight={22}
												intrinsicWidth={22}
												layoutDependency={layoutDependency}
												layoutId={"dYbMwnqSA"}
												svg={
													'<svg width="22" height="22" viewBox="0 0 22 22" fill="none" xmlns="http://www.w3.org/2000/svg">\n<rect x="0.886719" y="0.888184" width="20.25" height="20.25" rx="5.184" fill="#0085FF"/>\n<g clip-path="url(#clip0_7518_25998)">\n<path d="M8.6875 22.1929C8.6875 16.6587 8.6875 13.8921 10.0611 11.9312C10.5692 11.2056 11.2003 10.5746 11.9258 10.0665C13.8867 8.69287 16.6525 8.69287 22.1875 8.69287" stroke="white" stroke-width="2.025" stroke-linecap="round" stroke-linejoin="round"/>\n</g>\n<defs>\n<clipPath id="clip0_7518_25998">\n<rect width="20.25" height="20.25" fill="white" transform="translate(0.886719 0.888184)"/>\n</clipPath>\n</defs>\n</svg>\n'
												}
												withExternalLayout={true}
											/>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-j1q132"}
												data-framer-name={"16px"}
												fonts={["GF;Urbanist-700"]}
												layoutDependency={layoutDependency}
												layoutId={"i3icEY2pP"}
												style={{
													"--extracted-r6o4lv": "rgb(255, 255, 255)",
													"--framer-paragraph-spacing": "0px",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														style={{
															"--font-selector": "R0Y7VXJiYW5pc3QtNzAw",
															"--framer-font-family":
																'"Urbanist", "Urbanist Placeholder", sans-serif',
															"--framer-font-size": "14.18px",
															"--framer-font-weight": "700",
															"--framer-text-color":
																"var(--extracted-r6o4lv, rgb(255, 255, 255))",
														}}
													>
														{"16px"}
													</motion.p>
												</React.Fragment>
											</RichText>
										</Image>
										<Image
											background={{
												alt: "",
												fit: "stretch",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) +
														0 +
														0 +
														2 +
														178 +
														50.4004 +
														2.4004,
												),
												pixelHeight: 116,
												pixelWidth: 316,
												positionX: "center",
												positionY: "center",
												src: "https://framerusercontent.com/images/isShETFgBopCDZ0WATpB4vtPB4.png?width=316&height=116",
											}}
											className={"framer-yorlea"}
											data-border={true}
											data-framer-name={"Frame 1707481126"}
											layoutDependency={layoutDependency}
											layoutId={"iZDOJvsOt"}
											style={{
												"--border-bottom-width": "1.2959998846054077px",
												"--border-color": "rgb(252, 132, 68)",
												"--border-left-width": "1.2959998846054077px",
												"--border-right-width": "1.2959998846054077px",
												"--border-style": "solid",
												"--border-top-width": "1.2959998846054077px",
												borderBottomLeftRadius: 7.78,
												borderBottomRightRadius: 7.78,
												borderTopLeftRadius: 7.78,
												borderTopRightRadius: 7.78,
												boxShadow:
													"0px 2.5919997692108154px 33.69599914550781px 0px rgba(252, 132, 68, 0.12)",
											}}
											{...addPropertyOverrides(
												{
													qAZ1cdPNM: {
														background: {
															alt: "",
															fit: "stretch",
															loading: getLoadingLazyAtYPosition(
																(componentViewport?.y || 0) +
																	0 +
																	0 +
																	2 +
																	898 +
																	178 +
																	50.4004 +
																	2.4004,
															),
															pixelHeight: 116,
															pixelWidth: 316,
															positionX: "center",
															positionY: "center",
															src: "https://framerusercontent.com/images/isShETFgBopCDZ0WATpB4vtPB4.png?width=316&height=116",
														},
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<motion.div
												className={"framer-136op6g"}
												data-framer-name={"Frame 1707481125"}
												layoutDependency={layoutDependency}
												layoutId={"SWaKR7XLl"}
												style={{
													backgroundColor: "rgb(252, 132, 68)",
													borderBottomLeftRadius: 5.18,
													borderBottomRightRadius: 5.18,
													borderTopLeftRadius: 5.18,
													borderTopRightRadius: 5.18,
												}}
											>
												<RichText
													__fromCanvasComponent={true}
													className={"framer-8iwubd"}
													data-framer-name={"Tt"}
													fonts={["GF;Poppins-600"]}
													layoutDependency={layoutDependency}
													layoutId={"SK9cxYSce"}
													style={{
														"--extracted-r6o4lv": "rgb(255, 255, 255)",
														"--framer-paragraph-spacing": "0px",
													}}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													<React.Fragment>
														<motion.p
															style={{
																"--font-selector": "R0Y7UG9wcGlucy02MDA=",
																"--framer-font-family":
																	'"Poppins", "Poppins Placeholder", sans-serif',
																"--framer-font-size": "10.37px",
																"--framer-font-weight": "600",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, rgb(255, 255, 255))",
															}}
														>
															{"Tt"}
														</motion.p>
													</React.Fragment>
												</RichText>
											</motion.div>
											<motion.div
												className={"framer-8qe201"}
												data-framer-name={"Frame 1707481126"}
												layoutDependency={layoutDependency}
												layoutId={"eaCcJcwQ4"}
											>
												<RichText
													__fromCanvasComponent={true}
													className={"framer-y03t8f"}
													data-framer-name={"Poppins"}
													fonts={["GF;Urbanist-700"]}
													layoutDependency={layoutDependency}
													layoutId={"HnrwdPMK4"}
													style={{
														"--extracted-r6o4lv": "rgb(75, 75, 75)",
														"--framer-paragraph-spacing": "0px",
													}}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													<React.Fragment>
														<motion.p
															style={{
																"--font-selector": "R0Y7VXJiYW5pc3QtNzAw",
																"--framer-font-family":
																	'"Urbanist", "Urbanist Placeholder", sans-serif',
																"--framer-font-size": "11.66px",
																"--framer-font-weight": "700",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, rgb(75, 75, 75))",
															}}
														>
															{"Poppins"}
														</motion.p>
													</React.Fragment>
												</RichText>
											</motion.div>
										</Image>
										<Image
											background={{
												alt: "",
												fit: "stretch",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) +
														0 +
														0 +
														2 +
														178 +
														50.4004 +
														0,
												),
												pixelHeight: 116,
												pixelWidth: 400,
												positionX: "center",
												positionY: "center",
												src: "https://framerusercontent.com/images/n2RjoAfVfnu5S9YATFgiPfulfI.png?width=400&height=116",
											}}
											className={"framer-vwrvev"}
											data-border={true}
											data-framer-name={"Frame 1707481125"}
											layoutDependency={layoutDependency}
											layoutId={"oKg_7_24b"}
											style={{
												"--border-bottom-width": "1.2959998846054077px",
												"--border-color": "rgb(245, 93, 103)",
												"--border-left-width": "1.2959998846054077px",
												"--border-right-width": "1.2959998846054077px",
												"--border-style": "solid",
												"--border-top-width": "1.2959998846054077px",
												borderBottomLeftRadius: 7.78,
												borderBottomRightRadius: 7.78,
												borderTopLeftRadius: 7.78,
												borderTopRightRadius: 7.78,
												boxShadow:
													"0px 2.5919997692108154px 33.69599914550781px 0px rgba(245, 93, 103, 0.12)",
											}}
											{...addPropertyOverrides(
												{
													qAZ1cdPNM: {
														background: {
															alt: "",
															fit: "stretch",
															loading: getLoadingLazyAtYPosition(
																(componentViewport?.y || 0) +
																	0 +
																	0 +
																	2 +
																	898 +
																	178 +
																	50.4004 +
																	0,
															),
															pixelHeight: 116,
															pixelWidth: 400,
															positionX: "center",
															positionY: "center",
															src: "https://framerusercontent.com/images/n2RjoAfVfnu5S9YATFgiPfulfI.png?width=400&height=116",
														},
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<motion.div
												className={"framer-1rblcz0"}
												data-framer-name={"Frame 1707481125"}
												layoutDependency={layoutDependency}
												layoutId={"YeyhHTacF"}
												style={{
													backgroundColor: "rgb(245, 93, 103)",
													borderBottomLeftRadius: 5.18,
													borderBottomRightRadius: 5.18,
													borderTopLeftRadius: 5.18,
													borderTopRightRadius: 5.18,
												}}
											/>
											<motion.div
												className={"framer-apwxo7"}
												data-framer-name={"Frame 1707481126"}
												layoutDependency={layoutDependency}
												layoutId={"wirf6MKfW"}
											>
												<RichText
													__fromCanvasComponent={true}
													className={"framer-w5aqet"}
													data-framer-name={"Primary / 6"}
													fonts={["GF;Urbanist-700"]}
													layoutDependency={layoutDependency}
													layoutId={"k9bzVpRLg"}
													style={{
														"--extracted-r6o4lv": "rgb(255, 255, 255)",
														"--framer-paragraph-spacing": "0px",
													}}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													<React.Fragment>
														<motion.p
															style={{
																"--font-selector": "R0Y7VXJiYW5pc3QtNzAw",
																"--framer-font-family":
																	'"Urbanist", "Urbanist Placeholder", sans-serif',
																"--framer-font-size": "11.66px",
																"--framer-font-weight": "700",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, rgb(255, 255, 255))",
															}}
														>
															{"Primary / 6"}
														</motion.p>
													</React.Fragment>
												</RichText>
											</motion.div>
										</Image>
									</motion.div>
								</motion.div>
								<motion.div
									className={"framer-ry7bff"}
									data-framer-name={"Rectangle 34630172"}
									layoutDependency={layoutDependency}
									layoutId={"DSLqSElBb"}
									style={{
										background:
											"linear-gradient(270deg, rgb(13, 13, 13) 0%, rgba(13, 13, 13, 0) 100%)",
										opacity: 0.8,
									}}
								/>
							</motion.div>
						</motion.div>
						<ComponentViewportProvider
							height={137}
							width={componentViewport?.width || "100vw"}
							y={(componentViewport?.y || 0) + 0 + 449}
							{...addPropertyOverrides(
								{
									qAZ1cdPNM: {
										y: (componentViewport?.y || 0) + 0 + 1347,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<SmartComponentScopedContainer
								className={"framer-1mp58k8-container"}
								layoutDependency={layoutDependency}
								layoutId={"Dxmm_UD3h-container"}
								nodeId={"Dxmm_UD3h"}
								rendersWithMotion={true}
								scopeId={"YTXCkfC2C"}
							>
								{_jsx(stdin_default, {
									height: "100%",
									HqL9mij6w: "40px 52px 40px 52px",
									i_teJhZkv: "Hope Callaway",
									id: "Dxmm_UD3h",
									layoutId: "Dxmm_UD3h",
									style: {
										width: "100%",
									},
									tOog67OOf: "0px",
									TYxU1hJzn:
										"With Velt, Implementation took weeks, instead of the quarters it would have taken, even with 3 FTEs",
									variant: "ku4873b63",
									width: "100%",
									xIRwUNeNp: "Senior PM @Leadpages",
									...addPropertyOverrides(
										{
											qAZ1cdPNM: {
												variant: "V2RnAcOC4",
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-jR7Cu.framer-sx6qfm, .framer-jR7Cu .framer-sx6qfm { display: block; }",
	".framer-jR7Cu.framer-sgewes { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 1280px; will-change: var(--framer-will-change-override, transform); }",
	".framer-jR7Cu .framer-13f3g02 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 2px; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
	".framer-jR7Cu .framer-11hv13i { flex: 1 0 0px; gap: 0px; height: 445px; overflow: hidden; position: relative; width: 1px; }",
	".framer-jR7Cu .framer-10n0qb0, .framer-jR7Cu .framer-19ojnw, .framer-jR7Cu .framer-1w58zkw { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: flex-start; left: 36px; overflow: visible; padding: 0px; position: absolute; top: 36px; width: min-content; }",
	".framer-jR7Cu .framer-1ltbucp, .framer-jR7Cu .framer-13re0tl { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 188px; word-break: break-word; word-wrap: break-word; }",
	".framer-jR7Cu .framer-1ogmjhu { flex: none; gap: 0px; height: 270px; left: 57px; overflow: visible; position: absolute; top: calc(68.31460674157303% - 270px / 2); width: 378px; }",
	".framer-jR7Cu .framer-1lcjo4f { flex: none; height: auto; left: 21px; position: absolute; top: 72px; white-space: pre; width: auto; }",
	".framer-jR7Cu .framer-142c9hc { flex: none; height: auto; left: 21px; position: absolute; top: 125px; white-space: pre; width: auto; }",
	".framer-jR7Cu .framer-wx1lu { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; left: 21px; overflow: visible; padding: 0px; position: absolute; top: 21px; width: min-content; }",
	".framer-jR7Cu .framer-1lcxrlr, .framer-jR7Cu .framer-12eur9l, .framer-jR7Cu .framer-my2nx4 { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 12px); position: relative; width: 12px; }",
	".framer-jR7Cu .framer-110b6da { flex: none; height: 445px; position: absolute; right: 0px; top: 0px; width: 94px; }",
	".framer-jR7Cu .framer-1uge1v2, .framer-jR7Cu .framer-1d3eo9t { flex: 1 0 0px; gap: 10px; height: 445px; overflow: hidden; position: relative; width: 1px; }",
	".framer-jR7Cu .framer-1pdewwk { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 207px; word-break: break-word; word-wrap: break-word; }",
	".framer-jR7Cu .framer-zbeohw, .framer-jR7Cu .framer-dwx5q7, .framer-jR7Cu .framer-j1q132, .framer-jR7Cu .framer-8iwubd, .framer-jR7Cu .framer-y03t8f, .framer-jR7Cu .framer-w5aqet { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-jR7Cu .framer-13bkw8f { flex: none; height: 186px; left: 76px; overflow: visible; position: absolute; top: 175px; width: 407px; }",
	".framer-jR7Cu .framer-1qc1om7 { flex: none; height: auto; left: 0px; position: absolute; top: 0px; white-space: pre-wrap; width: 387px; word-break: break-word; word-wrap: break-word; }",
	".framer-jR7Cu .framer-o5zqkc { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; left: 20px; overflow: hidden; padding: 0px; position: absolute; top: 41px; width: 387px; will-change: var(--framer-will-change-override, transform); }",
	".framer-jR7Cu .framer-1pzl8hw { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 19.200000762939453px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px 19.200000762939453px 19.200000762939453px 19.200000762939453px; position: relative; width: 433px; }",
	".framer-jR7Cu .framer-z19gts { flex: none; gap: 0px; height: 1px; overflow: hidden; position: relative; width: 100%; }",
	".framer-jR7Cu .framer-x1ggn7 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-jR7Cu .framer-fyr3pg { align-content: flex-end; align-items: flex-end; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 9.600000381469727px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-jR7Cu .framer-4ztmbq { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-jR7Cu .framer-1p38j7c { flex: none; height: 39px; position: relative; width: 395px; }",
	".framer-jR7Cu .framer-14nrtv5 { flex: none; height: 27px; position: relative; width: 395px; }",
	".framer-jR7Cu .framer-15mlk5f { flex: none; height: auto; left: 0px; position: absolute; top: 165px; white-space: pre-wrap; width: 387px; word-break: break-word; word-wrap: break-word; }",
	".framer-jR7Cu .framer-13xru2b { flex: none; height: 270px; position: absolute; right: 0px; top: calc(60.92916081460674% - 270px / 2); width: 80px; }",
	".framer-jR7Cu .framer-1g0i0kj { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 230px; word-break: break-word; word-wrap: break-word; }",
	".framer-jR7Cu .framer-14cdzar { flex: none; height: 200px; left: 70px; overflow: visible; position: absolute; top: 178px; width: 435px; }",
	".framer-jR7Cu .framer-6i3bpt { flex: none; gap: 0px; height: 170px; overflow: hidden; position: absolute; right: 33px; top: 0px; width: 337px; will-change: var(--framer-will-change-override, transform); }",
	".framer-jR7Cu .framer-1uasr2m { flex: none; height: 30px; left: 15px; overflow: visible; position: absolute; top: 11px; width: 143px; }",
	".framer-jR7Cu .framer-bb0lib { flex: none; gap: 9.334071159362793px; height: 30px; left: 0px; overflow: visible; position: absolute; top: 0px; width: 83px; }",
	".framer-jR7Cu .framer-gzbpz { flex: none; gap: 0px; height: 22px; left: 57px; overflow: hidden; position: absolute; top: 4px; width: 22px; }",
	".framer-jR7Cu .framer-pd6xid, .framer-jR7Cu .framer-y376ce { bottom: 7px; flex: none; left: 6px; position: absolute; right: 12px; top: 7px; }",
	".framer-jR7Cu .framer-ui3292 { flex: none; height: auto; left: 9px; position: absolute; top: 4px; white-space: pre; width: auto; }",
	".framer-jR7Cu .framer-en1efk { flex: none; gap: 9.334071159362793px; height: 30px; left: 91px; overflow: visible; position: absolute; top: 0px; width: 52px; }",
	".framer-jR7Cu .framer-x4p8qn { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: absolute; right: 4px; top: 4px; width: min-content; }",
	".framer-jR7Cu .framer-13trj11 { flex: none; gap: 0px; height: 22px; overflow: hidden; position: relative; width: 22px; }",
	".framer-jR7Cu .framer-frksjb { flex: none; height: auto; left: 10px; position: absolute; top: 4px; white-space: pre; width: auto; }",
	".framer-jR7Cu .framer-1y9ldq9 { flex: none; height: 30px; left: 15px; position: absolute; top: 65px; width: 30px; }",
	".framer-jR7Cu .framer-ukj3ra { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 5.183999538421631px; height: min-content; justify-content: flex-start; left: 52px; overflow: visible; padding: 0px; position: absolute; top: 69px; width: min-content; }",
	".framer-jR7Cu .framer-8p61xx { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 6.479999542236328px; height: min-content; justify-content: center; overflow: visible; padding: 0px 1.2959998846054077px 0px 1.2959998846054077px; position: relative; width: min-content; }",
	".framer-jR7Cu .framer-afcvo2 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 31px; word-break: break-word; word-wrap: break-word; }",
	".framer-jR7Cu .framer-16007zv { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 9.071999549865723px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-jR7Cu .framer-1e5fabi { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 3.733628511428833px; height: 16px; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 80px; }",
	".framer-jR7Cu .framer-18b8ce5 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 6.479999542236328px; height: min-content; justify-content: center; left: 52px; min-height: 32px; overflow: visible; padding: 6.479999542236328px; position: absolute; top: 119px; width: 235px; }",
	".framer-jR7Cu .framer-czmry7 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 6.479999542236328px; height: min-content; justify-content: center; left: 294px; min-height: 32px; overflow: visible; padding: 6.479999542236328px; position: absolute; top: 119px; width: 32px; }",
	".framer-jR7Cu .framer-9abeh8 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 3.8879997730255127px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: absolute; right: 17px; top: 23px; width: min-content; }",
	".framer-jR7Cu .framer-1i59z36, .framer-jR7Cu .framer-wuf52f, .framer-jR7Cu .framer-j7k0os { flex: none; height: 4px; position: relative; width: 4px; }",
	".framer-jR7Cu .framer-4168a9 { flex: none; height: 150px; left: 0px; overflow: visible; position: absolute; top: 50px; width: 435px; }",
	".framer-jR7Cu .framer-17h32vh { flex: none; height: 94px; left: 47px; position: absolute; top: 43px; width: 95px; }",
	".framer-jR7Cu .framer-15fvql3 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 5.183999538421631px; height: min-content; justify-content: flex-start; overflow: visible; padding: 3.8879997730255127px; position: absolute; right: 372px; top: 122px; width: min-content; }",
	".framer-jR7Cu .framer-1jfjxvx { flex: none; height: 22px; position: relative; width: 22px; }",
	".framer-jR7Cu .framer-yorlea { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 5.183999538421631px; height: min-content; justify-content: flex-start; overflow: visible; padding: 3.8879997730255127px 7.775999546051025px 3.8879997730255127px 3.8879997730255127px; position: absolute; right: 0px; top: 2px; width: min-content; }",
	".framer-jR7Cu .framer-136op6g { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 4.050000190734863px; height: 21px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 21px; }",
	".framer-jR7Cu .framer-8qe201, .framer-jR7Cu .framer-apwxo7 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 2.5919997692108154px; height: min-content; justify-content: center; overflow: visible; padding: 2.5919997692108154px 0px 2.5919997692108154px 0px; position: relative; width: min-content; }",
	".framer-jR7Cu .framer-vwrvev { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 5.183999538421631px; height: min-content; justify-content: flex-start; overflow: visible; padding: 3.8879997730255127px 10.367999076843262px 3.8879997730255127px 3.8879997730255127px; position: absolute; right: 323px; top: 0px; width: min-content; }",
	".framer-jR7Cu .framer-1rblcz0 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 4.050000190734863px; height: 21px; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 21px; }",
	".framer-jR7Cu .framer-ry7bff { flex: none; height: 270px; position: absolute; right: 0px; top: calc(57.333655196629216% - 270px / 2); width: 104px; }",
	".framer-jR7Cu .framer-1mp58k8-container { flex: none; height: auto; position: relative; width: 100%; }",
	".framer-jR7Cu.framer-v-1im1pi9.framer-sgewes { width: 320px; }",
	".framer-jR7Cu.framer-v-1im1pi9 .framer-13f3g02 { flex-direction: column; }",
	".framer-jR7Cu.framer-v-1im1pi9 .framer-11hv13i, .framer-jR7Cu.framer-v-1im1pi9 .framer-1uge1v2, .framer-jR7Cu.framer-v-1im1pi9 .framer-1d3eo9t { flex: none; width: 100%; }",
	".framer-jR7Cu.framer-v-1im1pi9 .framer-10n0qb0, .framer-jR7Cu.framer-v-1im1pi9 .framer-19ojnw, .framer-jR7Cu.framer-v-1im1pi9 .framer-1w58zkw { left: 24px; top: 24px; }",
	'.framer-jR7Cu[data-border="true"]::after, .framer-jR7Cu [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerYTXCkfC2C = withCSS(Component, css, "framer-jR7Cu");
var stdin_default2 = FramerYTXCkfC2C;
FramerYTXCkfC2C.displayName = "2025/Get Started Steps";
FramerYTXCkfC2C.defaultProps = {
	height: 615.5,
	width: 1280,
};
addPropertyControls(FramerYTXCkfC2C, {
	variant: {
		options: ["unk9GXHYp", "qAZ1cdPNM"],
		optionTitles: ["Variant 1", "Mobile"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerYTXCkfC2C,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Urbanist",
					source: "google",
					style: "normal",
					url: "https://fonts.gstatic.com/s/urbanist/v18/L0xjDF02iFML4hGCyOCpRdycFsGxSrqDLBkfE5OrS8SlKw.woff2",
					weight: "700",
				},
				{
					family: "Urbanist",
					source: "google",
					style: "normal",
					url: "https://fonts.gstatic.com/s/urbanist/v18/L0xjDF02iFML4hGCyOCpRdycFsGxSrqDyx4fE5OrS8SlKw.woff2",
					weight: "400",
				},
				{
					family: "Fira Code",
					source: "google",
					style: "normal",
					url: "https://fonts.gstatic.com/s/firacode/v27/uU9eCBsR6Z2vfE9aq3bL0fxyUs4tcw4W_A9sFVLxN87gsj0.woff2",
					weight: "500",
				},
				{
					family: "Fira Code",
					source: "google",
					style: "normal",
					url: "https://fonts.gstatic.com/s/firacode/v27/uU9eCBsR6Z2vfE9aq3bL0fxyUs4tcw4W_D1sFVLxN87gsj0.woff2",
					weight: "400",
				},
				{
					family: "Poppins",
					source: "google",
					style: "normal",
					url: "https://fonts.gstatic.com/s/poppins/v24/pxiByp8kv8JHgFVrLEj6V15vFP-KUEg.woff2",
					weight: "600",
				},
			],
		},
		...TestimonialFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:2025/get-started-steps
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "qAZ1cdPNM",
	xl: "unk9GXHYp",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7e5af5d66397a8a15ce8ab3401cf6b1aee707f00a906595a26b5cba8a8c88d97"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders GetStartedStepsFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7e5af5d66397a8a15ce8ab3401cf6b1aee707f00a906595a26b5cba8a8c88d97"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var get_started_steps_default = ComponentWithRoot;
export { get_started_steps_default as default };
